import { mkdir, readFile, readdir, stat, writeFile } from 'node:fs/promises';
import path from 'node:path';

import { format as formatWithPrettier, resolveConfig } from 'prettier';

import {
  assertBlogSlug,
  assertUniqueBlogSlugs,
  parseBlogArticleMetadata,
} from '../../apps/website/src/blog/schema';
import type { BlogArticleMetadata } from '../../apps/website/src/blog/types';

const BLOG_CONTENT_RELATIVE_PATH = path.join(
  'apps',
  'website',
  'content',
  'blog'
);
const BLOG_REGISTRY_RELATIVE_PATH = path.join(
  'apps',
  'website',
  'src',
  'blog',
  'article-modules.ts'
);
const WEBSITE_PUBLIC_RELATIVE_PATH = path.join('apps', 'website', 'public');
const METADATA_FILE = 'metadata.json';
const ARTICLE_FILE = 'article.mdx';
const DEFAULT_AUTHOR = 'Roman Bakurov';
const DEFAULT_TAGS = ['Vellira'] as const;

export interface CreateBlogArticleOptions {
  root: string;
  slug: string;
  today: string;
}

export interface CreateBlogArticleResult {
  articleDirectory: string;
  articlePath: string;
  metadataPath: string;
  registryPath: string;
}

export interface BlogCheckResult {
  articleCount: number;
  issues: string[];
}

interface BlogCorpusEntry {
  body: string;
  directorySlug: string;
  metadata: BlogArticleMetadata;
}

function isNodeError(error: unknown): error is NodeJS.ErrnoException {
  return error instanceof Error && 'code' in error;
}

async function pathExists(targetPath: string): Promise<boolean> {
  try {
    await stat(targetPath);
    return true;
  } catch (error) {
    if (isNodeError(error) && error.code === 'ENOENT') {
      return false;
    }

    throw error;
  }
}

function resolveBlogContentDirectory(root: string): string {
  return path.join(root, BLOG_CONTENT_RELATIVE_PATH);
}

function resolveBlogRegistryPath(root: string): string {
  return path.join(root, BLOG_REGISTRY_RELATIVE_PATH);
}

function resolveWebsitePublicDirectory(root: string): string {
  return path.join(root, WEBSITE_PUBLIC_RELATIVE_PATH);
}

function titleFromSlug(slug: string): string {
  return slug
    .split('-')
    .map((part) => `${part.slice(0, 1).toUpperCase()}${part.slice(1)}`)
    .join(' ');
}

function metadataImportIdentifier(slug: string): string {
  const [first = '', ...rest] = slug.split('-');
  return `${first}${rest
    .map((part) => `${part.slice(0, 1).toUpperCase()}${part.slice(1)}`)
    .join('')}Metadata`;
}

export function buildBlogArticleRegistry(slugs: readonly string[]): string {
  const normalizedSlugs = [...slugs].sort((left, right) =>
    left.localeCompare(right)
  );
  const metadataImports = normalizedSlugs.map(
    (slug) =>
      `import ${metadataImportIdentifier(slug)} from '../../content/blog/${slug}/metadata.json';`
  );
  const metadataEntries = normalizedSlugs.map(
    (slug) =>
      `  { slug: '${slug}', metadata: ${metadataImportIdentifier(slug)} },`
  );
  const loaderEntries = normalizedSlugs.map(
    (slug) =>
      `    '${slug}': () => import('../../content/blog/${slug}/article.mdx'),`
  );
  const metadataRegistryBody =
    metadataEntries.length === 0
      ? '  [] as const satisfies readonly BlogArticleMetadataRegistryEntry[];'
      : `  [\n${metadataEntries.join('\n')}\n  ] as const satisfies readonly BlogArticleMetadataRegistryEntry[];`;
  const loaderRegistryBody =
    loaderEntries.length === 0
      ? '  {};'
      : `  {\n${loaderEntries.join('\n')}\n  };`;

  return [
    "import type { ComponentType } from 'react';",
    ...(metadataImports.length > 0 ? ['', ...metadataImports] : []),
    '',
    'export interface BlogMDXModule {',
    '  default: ComponentType;',
    '}',
    '',
    'export type BlogMDXModuleLoader = () => Promise<BlogMDXModule>;',
    '',
    'export interface BlogArticleMetadataRegistryEntry {',
    '  slug: string;',
    '  metadata: unknown;',
    '}',
    '',
    '/**',
    ' * Generated by Blog V1 authoring tooling.',
    ' *',
    ' * Keep MDX and metadata imports statically analyzable for Next.js/Turbopack',
    ' * and Cloudflare Workers. Runtime rendering must not depend on repository fs.',
    ' */',
    'const blogArticleMetadataRegistryEntries =',
    metadataRegistryBody,
    '',
    'const blogArticleModuleLoaders: Readonly<Record<string, BlogMDXModuleLoader>> =',
    loaderRegistryBody,
    '',
    'export function getBlogArticleMetadataRegistryEntries(): readonly BlogArticleMetadataRegistryEntry[] {',
    '  return blogArticleMetadataRegistryEntries;',
    '}',
    '',
    'export function getBlogArticleModuleLoader(',
    '  slug: string',
    '): BlogMDXModuleLoader | null {',
    '  return blogArticleModuleLoaders[slug] ?? null;',
    '}',
    '',
  ].join('\n');
}

function buildDraftMetadata(slug: string, today: string): BlogArticleMetadata {
  const title = titleFromSlug(slug);

  return {
    title,
    description: `TODO: Write a concise description for ${title}.`,
    slug,
    publishedAt: today,
    author: DEFAULT_AUTHOR,
    tags: [...DEFAULT_TAGS],
    draft: true,
  };
}

function buildDraftBody(slug: string): string {
  return `# ${titleFromSlug(slug)}\n\nTODO: Write the article.\n`;
}

async function listArticleDirectorySlugs(
  contentDirectory: string
): Promise<string[]> {
  const entries = await readdir(contentDirectory, { withFileTypes: true });

  return entries
    .filter((entry) => entry.isDirectory())
    .map((entry) =>
      assertBlogSlug(entry.name, path.join(contentDirectory, entry.name))
    )
    .sort((left, right) => left.localeCompare(right));
}

export async function createBlogArticle(
  options: CreateBlogArticleOptions
): Promise<CreateBlogArticleResult> {
  const slug = assertBlogSlug(options.slug, 'blog:new');
  const contentDirectory = resolveBlogContentDirectory(options.root);
  const registryPath = resolveBlogRegistryPath(options.root);
  const articleDirectory = path.join(contentDirectory, slug);
  const metadataPath = path.join(articleDirectory, METADATA_FILE);
  const articlePath = path.join(articleDirectory, ARTICLE_FILE);

  parseBlogArticleMetadata(buildDraftMetadata(slug, options.today), 'blog:new');

  if (!(await pathExists(contentDirectory))) {
    throw new Error(
      `${contentDirectory}: blog content directory does not exist`
    );
  }

  if (!(await pathExists(registryPath))) {
    throw new Error(`${registryPath}: blog article registry does not exist`);
  }

  if (await pathExists(articleDirectory)) {
    throw new Error(
      `${articleDirectory}: article already exists; refusing to overwrite`
    );
  }

  const existingSlugs = await listArticleDirectorySlugs(contentDirectory);
  const expectedRegistry = buildBlogArticleRegistry([...existingSlugs, slug]);
  const metadata = `${JSON.stringify(buildDraftMetadata(slug, options.today), null, 2)}\n`;

  await mkdir(articleDirectory);
  await writeFile(metadataPath, metadata, 'utf8');
  await writeFile(articlePath, buildDraftBody(slug), 'utf8');
  await writeFile(registryPath, expectedRegistry, 'utf8');

  return {
    articleDirectory,
    articlePath,
    metadataPath,
    registryPath,
  };
}

async function readCorpusEntry(
  contentDirectory: string,
  directorySlug: string
): Promise<BlogCorpusEntry> {
  const articleDirectory = path.join(contentDirectory, directorySlug);
  const metadataPath = path.join(articleDirectory, METADATA_FILE);
  const articlePath = path.join(articleDirectory, ARTICLE_FILE);

  const [rawMetadata, body] = await Promise.all([
    readFile(metadataPath, 'utf8'),
    readFile(articlePath, 'utf8'),
  ]);
  let parsedMetadata: unknown;

  try {
    parsedMetadata = JSON.parse(rawMetadata) as unknown;
  } catch {
    throw new Error(`${metadataPath}: metadata must contain valid JSON`);
  }

  return {
    body,
    directorySlug,
    metadata: parseBlogArticleMetadata(parsedMetadata, metadataPath),
  };
}

function collectInternalBlogLinks(body: string): string[] {
  const slugs = new Set<string>();
  const linkPattern = /\]\(\/blog\/([a-z0-9]+(?:-[a-z0-9]+)*)(?:[#?][^)]*)?\)/g;

  for (const match of body.matchAll(linkPattern)) {
    if (match[1] !== undefined) {
      slugs.add(match[1]);
    }
  }

  return [...slugs].sort((left, right) => left.localeCompare(right));
}

async function validateSocialImage(
  root: string,
  entry: BlogCorpusEntry,
  issues: string[]
): Promise<void> {
  const socialImage = entry.metadata.socialImage;

  if (socialImage === undefined || !socialImage.startsWith('/')) {
    return;
  }

  const publicDirectory = resolveWebsitePublicDirectory(root);
  const imagePath = path.resolve(publicDirectory, `.${socialImage}`);
  const relativePath = path.relative(publicDirectory, imagePath);

  if (relativePath.startsWith('..') || path.isAbsolute(relativePath)) {
    issues.push(
      `${entry.metadata.slug}: socialImage escapes website public directory`
    );
    return;
  }

  if (!(await pathExists(imagePath))) {
    issues.push(
      `${entry.metadata.slug}: socialImage does not exist: ${socialImage}`
    );
  }
}

export async function checkBlogCorpus(root: string): Promise<BlogCheckResult> {
  const contentDirectory = resolveBlogContentDirectory(root);
  const registryPath = resolveBlogRegistryPath(root);
  const issues: string[] = [];
  let directorySlugs: string[];

  try {
    directorySlugs = await listArticleDirectorySlugs(contentDirectory);
  } catch (error) {
    return {
      articleCount: 0,
      issues: [error instanceof Error ? error.message : String(error)],
    };
  }

  const entries: BlogCorpusEntry[] = [];

  for (const directorySlug of directorySlugs) {
    try {
      entries.push(await readCorpusEntry(contentDirectory, directorySlug));
    } catch (error) {
      issues.push(error instanceof Error ? error.message : String(error));
    }
  }

  try {
    assertUniqueBlogSlugs(
      entries.map((entry) => entry.metadata),
      contentDirectory
    );
  } catch (error) {
    issues.push(error instanceof Error ? error.message : String(error));
  }

  for (const entry of entries) {
    if (entry.metadata.slug !== entry.directorySlug) {
      issues.push(
        `${entry.metadata.slug}: metadata slug must match directory ${entry.directorySlug}`
      );
    }
  }

  const articlesBySlug = new Map(
    entries.map((entry) => [entry.metadata.slug, entry.metadata] as const)
  );

  for (const entry of entries) {
    for (const targetSlug of collectInternalBlogLinks(entry.body)) {
      const target = articlesBySlug.get(targetSlug);

      if (target === undefined) {
        issues.push(
          `${entry.metadata.slug}: internal blog link target does not exist: ${targetSlug}`
        );
      } else if (!entry.metadata.draft && target.draft) {
        issues.push(
          `${entry.metadata.slug}: published article links to draft article: ${targetSlug}`
        );
      }
    }

    await validateSocialImage(root, entry, issues);
  }

  try {
    const actualRegistry = await readFile(registryPath, 'utf8');
    const expectedRegistry = buildBlogArticleRegistry(directorySlugs);
    const prettierConfig = (await resolveConfig(registryPath)) ?? {};
    const prettierOptions = { ...prettierConfig, filepath: registryPath };
    const [normalizedActualRegistry, normalizedExpectedRegistry] =
      await Promise.all([
        formatWithPrettier(actualRegistry, prettierOptions),
        formatWithPrettier(expectedRegistry, prettierOptions),
      ]);

    if (normalizedActualRegistry !== normalizedExpectedRegistry) {
      issues.push(
        `${registryPath}: registry is stale; run pnpm blog:new for new articles or regenerate it with Blog V1 tooling`
      );
    }
  } catch (error) {
    issues.push(error instanceof Error ? error.message : String(error));
  }

  return {
    articleCount: directorySlugs.length,
    issues: [...new Set(issues)].sort((left, right) =>
      left.localeCompare(right)
    ),
  };
}
