// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

'use client';

import { Switch as ReactSwitch } from '@vellira-ui/react';
import { Switch as NativeSwitch } from '@vellira-ui/react-native';

import { ComponentExamples } from '../../shared/ComponentExamples';
import type { ComponentPlatform } from '../../types';

type SwitchExamplesProps = {
  platform: ComponentPlatform;
};

export function SwitchExamples({ platform }: SwitchExamplesProps) {
  const reactExamples = [
    {
      title: 'Basic',
      description: 'Basic component usage.',
      preview: <ReactSwitch />,
      code: `import { Switch } from '@vellira-ui/react';

<Switch/>`,
    },
    {
      title: 'Controlled',
      description: 'State controlled by the parent application.',
      preview: <ReactSwitch checked />,
      code: `import { Switch } from '@vellira-ui/react';

<Switch
  checked
/>`,
    },
    {
      title: 'Uncontrolled',
      description: 'State initialized and then managed by the component.',
      preview: <ReactSwitch defaultChecked />,
      code: `import { Switch } from '@vellira-ui/react';

<Switch
  defaultChecked
/>`,
    },
    {
      title: 'Disabled',
      description: 'Disabled state with interaction unavailable.',
      preview: <ReactSwitch disabled />,
      code: `import { Switch } from '@vellira-ui/react';

<Switch
  disabled
/>`,
    },
    {
      title: 'Required',
      description: 'Required state for form participation.',
      preview: <ReactSwitch required />,
      code: `import { Switch } from '@vellira-ui/react';

<Switch
  required
/>`,
    },
    {
      title: 'Invalid',
      description: 'Invalid state with validation semantics.',
      preview: <ReactSwitch invalid />,
      code: `import { Switch } from '@vellira-ui/react';

<Switch
  invalid
/>`,
    },
  ] as const;

  const nativeExamples = [
    {
      title: 'Basic',
      description: 'Basic component usage.',
      preview: <NativeSwitch />,
      code: `import { Switch } from '@vellira-ui/react-native';

<Switch/>`,
    },
    {
      title: 'Controlled',
      description: 'State controlled by the parent application.',
      preview: <NativeSwitch checked />,
      code: `import { Switch } from '@vellira-ui/react-native';

<Switch
  checked
/>`,
    },
    {
      title: 'Uncontrolled',
      description: 'State initialized and then managed by the component.',
      preview: <NativeSwitch defaultChecked />,
      code: `import { Switch } from '@vellira-ui/react-native';

<Switch
  defaultChecked
/>`,
    },
    {
      title: 'Disabled',
      description: 'Disabled state with interaction unavailable.',
      preview: <NativeSwitch disabled />,
      code: `import { Switch } from '@vellira-ui/react-native';

<Switch
  disabled
/>`,
    },
    {
      title: 'Required',
      description: 'Required state for form participation.',
      preview: <NativeSwitch required />,
      code: `import { Switch } from '@vellira-ui/react-native';

<Switch
  required
/>`,
    },
    {
      title: 'Invalid',
      description: 'Invalid state with validation semantics.',
      preview: <NativeSwitch invalid />,
      code: `import { Switch } from '@vellira-ui/react-native';

<Switch
  invalid
/>`,
    },
  ] as const;

  return (
    <ComponentExamples
      items={platform === 'react' ? reactExamples : nativeExamples}
    />
  );
}
