// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

'use client';

import { Textarea } from '@vellira-ui/react-native';

import { TextareaPlayground } from './TextareaPlayground';

export function NativeTextareaDemo() {
  return (
    <TextareaPlayground
      platform='react-native'
      renderTextarea={(value, onChange) => (
        <Textarea
          value={value.value || undefined}
          onValueChange={(nextValue) => onChange('value', nextValue)}
          disabled={value.disabled}
          required={value.required}
          invalid={value.invalid}
        />
      )}
    />
  );
}
