// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

'use client';

import type { ComponentPlatform } from '../../types';

import { ComponentCodeBlock } from '../../shared/ComponentCodeBlock';
import { useComponentDemoState } from '../../shared/ComponentDemoStateProvider';

import {
  initialTextareaPlaygroundValue,
  type TextareaPlaygroundValue,
} from './TextareaPlayground';

import styles from '../../shared/ComponentUsage.module.css';

type TextareaUsageProps = {
  platform: ComponentPlatform;
};

function createTextareaCode(
  platform: ComponentPlatform,
  value: TextareaPlaygroundValue
) {
  const packageName =
    platform === 'react' ? '@vellira-ui/react' : '@vellira-ui/react-native';

  const props: string[] = platform === 'react' ? [] : [];

  const children = platform === 'react' ? `` : ``;

  if (value.label) {
    props.push(`label='${value.label}'`);
  }

  if (value.description) {
    props.push(`description='${value.description}'`);
  }

  if (value.error) {
    props.push(`error='${value.error}'`);
  }

  if (value.placeholder) {
    props.push(`placeholder='${value.placeholder}'`);
  }

  if (value.size !== 'sm') {
    props.push(`size='${value.size}'`);
  }

  if (value.value) {
    props.push(`value='${value.value}'`);
  }

  if (value.disabled) {
    props.push('disabled');
  }

  if (value.required) {
    props.push('required');
  }

  if (value.invalid) {
    props.push('invalid');
  }

  const propsText = props.length === 0 ? '' : `\n  ${props.join('\n  ')}\n`;

  if (!children) {
    return `import { Textarea } from '${packageName}';
${platform === 'react' ? `` : ``}

<Textarea${propsText}/>`;
  }

  return `import { Textarea } from '${packageName}';
${platform === 'react' ? `` : ``}

<Textarea${propsText}>
${children}
</Textarea>`;
}

export function TextareaUsage({ platform }: TextareaUsageProps) {
  const [value] = useComponentDemoState<TextareaPlaygroundValue>(
    initialTextareaPlaygroundValue
  );

  const code = createTextareaCode(platform, value);

  return (
    <section className={styles.root}>
      <div className={styles.header}>
        <h2 className={styles.title}>Usage</h2>

        <p className={styles.description}>
          Import the component and configure it with the same props used in the
          playground.
        </p>
      </div>

      <ComponentCodeBlock code={code} />
    </section>
  );
}
