// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

import type {
  ComponentApiProp,
  ComponentApiSection,
} from '../../shared/ComponentApi';

const reactTextareaApiSections: readonly ComponentApiSection[] = [
  {
    name: 'Textarea',
    props: [
      {
        name: 'value',
        type: 'string',
        description: 'Controlled value.',
      },
      {
        name: 'defaultValue',
        type: 'string',
        description: 'Initial value for uncontrolled usage.',
      },
      {
        name: 'disabled',
        type: 'boolean',
        description: 'Disables interaction.',
      },
      {
        name: 'required',
        type: 'boolean',
        description: 'Marks the control as required.',
      },
      {
        name: 'invalid',
        type: 'boolean',
        description: 'Marks the control as invalid.',
      },
      {
        name: 'onValueChange',
        type: '((value: string) => void)',
        description: 'Called when the value changes.',
      },
    ],
  },
];

const nativeTextareaApiSections: readonly ComponentApiSection[] = [
  {
    name: 'Textarea',
    props: [
      {
        name: 'value',
        type: 'string',
        description: 'Controlled value.',
      },
      {
        name: 'defaultValue',
        type: 'string',
        description: 'Initial value for uncontrolled usage.',
      },
      {
        name: 'disabled',
        type: 'boolean',
        description: 'Disables interaction.',
      },
      {
        name: 'required',
        type: 'boolean',
        description: 'Marks the control as required.',
      },
      {
        name: 'invalid',
        type: 'boolean',
        description: 'Marks the control as invalid.',
      },
      {
        name: 'onValueChange',
        type: '((value: string) => void)',
        description: 'Called when the value changes.',
      },
    ],
  },
];

const inheritedReactTextareaApi: readonly ComponentApiProp[] = [];

const inheritedNativeTextareaApi: readonly ComponentApiProp[] = [];

export const textareaApi = {
  react: {
    sections: reactTextareaApiSections,
    inheritedProps: inheritedReactTextareaApi,
  },
  'react-native': {
    sections: nativeTextareaApiSections,
    inheritedProps: inheritedNativeTextareaApi,
  },
} as const;
