// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

'use client';

import { TextareaDemo } from './TextareaDemo';

export function TextareaCatalogPreview() {
  return <TextareaDemo />;
}
