// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

'use client';

import type { ComponentPlatform } from '../../types';

import { ComponentAccessibility } from '../../shared/ComponentAccessibility';

type TextareaAccessibilityProps = {
  platform: ComponentPlatform;
};

export function TextareaAccessibility({
  platform,
}: TextareaAccessibilityProps) {
  const reactItems = [
    {
      title: 'Accessible naming',
      description:
        'Provide a visible label or another accessible name that clearly identifies the control.',
      props: ['label', 'children', 'aria-label', 'aria-labelledby'],
    },
    {
      title: 'Disabled state',
      description:
        'Disabled controls should remain identifiable while preventing interaction.',
      props: ['disabled'],
    },
    {
      title: 'Validation feedback',
      description:
        'Associate validation feedback with the control and expose its invalid state to assistive technologies.',
      props: ['error', 'invalid'],
    },
    {
      title: 'Required fields',
      description:
        'Required state should be communicated semantically and not rely only on visual styling.',
      props: ['required'],
    },
    {
      title: 'Keyboard and focus',
      description:
        'Preserve expected keyboard interaction and visible focus behavior.',
      props: ['onKeyDown', 'onFocus', 'onBlur', 'onClick'],
    },
  ] as const;

  const nativeItems = [
    {
      title: 'Accessible naming',
      description:
        'Provide a visible label or accessibilityLabel so screen readers can identify the control.',
      props: ['label', 'children', 'accessibilityLabel'],
    },
    {
      title: 'Disabled state',
      description:
        'Disabled controls should remain identifiable while preventing interaction.',
      props: ['disabled'],
    },
    {
      title: 'Validation feedback',
      description:
        'Announce validation feedback through accessible text or hints without relying only on visual styling.',
      props: ['error', 'invalid'],
    },
    {
      title: 'Required fields',
      description:
        'Required state should be communicated semantically and not rely only on visual styling.',
      props: ['required'],
    },
    {
      title: 'Keyboard and focus',
      description:
        'Verify focus and screen reader interaction on supported React Native platforms.',
      props: ['onFocus', 'onBlur', 'onPress'],
    },
  ] as const;

  return (
    <ComponentAccessibility
      items={platform === 'react' ? reactItems : nativeItems}
    />
  );
}
