// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

'use client';

import { Textarea } from '@vellira-ui/react';

import styles from '../../shared/ComponentsCatalog/ComponentsCatalog.module.css';

export function TextareaCatalogPreview() {
  return (
    <div className={styles.previewFormControl}>
      <Textarea
        label='Message'
        placeholder='Write a message...'
        size='sm'
        rows={3}
      />
    </div>
  );
}
