// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

'use client';

import { ComponentDemoStateProvider } from '../../shared/ComponentDemoStateProvider';

import { TextareaDemo } from './TextareaDemo';

export function TextareaCatalogPreview() {
  return (
    <ComponentDemoStateProvider resetKey='catalog:textarea'>
      <TextareaDemo />
    </ComponentDemoStateProvider>
  );
}
