// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

'use client';

import { Textarea as ReactTextarea } from '@vellira-ui/react';
import { Textarea as NativeTextarea } from '@vellira-ui/react-native';

import { ComponentExamples } from '../../shared/ComponentExamples';
import type { ComponentPlatform } from '../../types';

type TextareaExamplesProps = {
  platform: ComponentPlatform;
};

export function TextareaExamples({ platform }: TextareaExamplesProps) {
  const reactExamples = [
    {
      title: 'Basic',
      description: 'Basic component usage.',
      preview: <ReactTextarea />,
      code: `import { Textarea } from '@vellira-ui/react';

<Textarea/>`,
    },
    {
      title: 'Controlled',
      description: 'State controlled by the parent application.',
      preview: <ReactTextarea value='Example value' />,
      code: `import { Textarea } from '@vellira-ui/react';

<Textarea
  value='Example value'
/>`,
    },
    {
      title: 'Uncontrolled',
      description: 'State initialized and then managed by the component.',
      preview: <ReactTextarea defaultValue='Example value' />,
      code: `import { Textarea } from '@vellira-ui/react';

<Textarea
  defaultValue='Example value'
/>`,
    },
    {
      title: 'Disabled',
      description: 'Disabled state with interaction unavailable.',
      preview: <ReactTextarea disabled />,
      code: `import { Textarea } from '@vellira-ui/react';

<Textarea
  disabled
/>`,
    },
    {
      title: 'Required',
      description: 'Required state for form participation.',
      preview: <ReactTextarea required />,
      code: `import { Textarea } from '@vellira-ui/react';

<Textarea
  required
/>`,
    },
    {
      title: 'Invalid',
      description: 'Invalid state with validation semantics.',
      preview: <ReactTextarea invalid />,
      code: `import { Textarea } from '@vellira-ui/react';

<Textarea
  invalid
/>`,
    },
  ] as const;

  const nativeExamples = [
    {
      title: 'Basic',
      description: 'Basic component usage.',
      preview: <NativeTextarea />,
      code: `import { Textarea } from '@vellira-ui/react-native';

<Textarea/>`,
    },
    {
      title: 'Controlled',
      description: 'State controlled by the parent application.',
      preview: <NativeTextarea value='Example value' />,
      code: `import { Textarea } from '@vellira-ui/react-native';

<Textarea
  value='Example value'
/>`,
    },
    {
      title: 'Uncontrolled',
      description: 'State initialized and then managed by the component.',
      preview: <NativeTextarea defaultValue='Example value' />,
      code: `import { Textarea } from '@vellira-ui/react-native';

<Textarea
  defaultValue='Example value'
/>`,
    },
    {
      title: 'Disabled',
      description: 'Disabled state with interaction unavailable.',
      preview: <NativeTextarea disabled />,
      code: `import { Textarea } from '@vellira-ui/react-native';

<Textarea
  disabled
/>`,
    },
    {
      title: 'Required',
      description: 'Required state for form participation.',
      preview: <NativeTextarea required />,
      code: `import { Textarea } from '@vellira-ui/react-native';

<Textarea
  required
/>`,
    },
    {
      title: 'Invalid',
      description: 'Invalid state with validation semantics.',
      preview: <NativeTextarea invalid />,
      code: `import { Textarea } from '@vellira-ui/react-native';

<Textarea
  invalid
/>`,
    },
  ] as const;

  return (
    <ComponentExamples
      items={platform === 'react' ? reactExamples : nativeExamples}
    />
  );
}
