// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

'use client';

import type { ReactNode } from 'react';

import { ComponentPlayground } from '../../shared/ComponentPlayground';
import { useComponentDemoState } from '../../shared/ComponentDemoStateProvider';
import { PlaygroundControlsFromSchema } from '../../shared/PlaygroundControls';

import { textareaPlaygroundControls } from './textareaPlaygroundSchema';

export type TextareaPlaygroundValue = {
  label: string;
  description: string;
  error: string;
  placeholder: string;
  size: 'sm' | 'md' | 'lg';
  value: string;
  disabled: boolean;
  required: boolean;
  invalid: boolean;
};

type TextareaPlaygroundProps = {
  platform: 'react' | 'react-native';
  renderTextarea: (
    value: TextareaPlaygroundValue,
    onChange: <K extends keyof TextareaPlaygroundValue>(
      key: K,
      nextValue: TextareaPlaygroundValue[K]
    ) => void
  ) => ReactNode;
};

export const initialTextareaPlaygroundValue: TextareaPlaygroundValue = {
  label: '',
  description: '',
  error: '',
  placeholder: '',
  size: 'sm',
  value: '',
  disabled: false,
  required: false,
  invalid: false,
};

export function TextareaPlayground({
  platform,
  renderTextarea,
}: TextareaPlaygroundProps) {
  const [value, setValue] = useComponentDemoState<TextareaPlaygroundValue>(
    initialTextareaPlaygroundValue
  );

  const update = (
    key: keyof TextareaPlaygroundValue,
    nextValue: TextareaPlaygroundValue[keyof TextareaPlaygroundValue]
  ) => {
    setValue({
      ...value,
      [key]: nextValue,
    });
  };

  return (
    <ComponentPlayground
      previewWidth='field'
      controls={
        <PlaygroundControlsFromSchema
          platform={platform}
          value={value}
          controls={textareaPlaygroundControls}
          onChange={update}
        />
      }
    >
      {renderTextarea(value, update)}
    </ComponentPlayground>
  );
}
