// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

'use client';

import type { ComponentPlatform } from '../../types';

import { ComponentAccessibility } from '../../shared/ComponentAccessibility';

type TextareaAccessibilityProps = {
  platform: ComponentPlatform;
};

export function TextareaAccessibility({
  platform,
}: TextareaAccessibilityProps) {
  const reactItems = [
    {
      title: 'Disabled state',
      description:
        'Disabled controls should remain identifiable while preventing interaction.',
      props: ['disabled'],
    },
    {
      title: 'Required fields',
      description:
        'Required state should be communicated semantically and not rely only on visual styling.',
      props: ['required'],
    },
    {
      title: 'Keyboard and focus',
      description:
        'Preserve expected keyboard interaction and visible focus behavior.',
    },
  ] as const;

  const nativeItems = [
    {
      title: 'Disabled state',
      description:
        'Disabled controls should remain identifiable while preventing interaction.',
      props: ['disabled'],
    },
    {
      title: 'Required fields',
      description:
        'Required state should be communicated semantically and not rely only on visual styling.',
      props: ['required'],
    },
    {
      title: 'Keyboard and focus',
      description:
        'Verify focus and screen reader interaction on supported React Native platforms.',
    },
  ] as const;

  return (
    <ComponentAccessibility
      items={platform === 'react' ? reactItems : nativeItems}
    />
  );
}
