// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

import type { PlaygroundControl } from '../../shared/PlaygroundControls';

import type { TextareaPlaygroundValue } from './TextareaPlayground';

export const textareaPlaygroundControls = [
  {
    type: 'text',
    key: 'label',
    label: 'Label',
  },
  {
    type: 'text',
    key: 'description',
    label: 'Description',
  },
  {
    type: 'text',
    key: 'error',
    label: 'Error',
  },
  {
    type: 'text',
    key: 'placeholder',
    label: 'Placeholder',
  },
  {
    type: 'select',
    key: 'size',
    label: 'Size',
    options: ['sm', 'md', 'lg'],
  },
  {
    type: 'text',
    key: 'value',
    label: 'Value',
  },
  {
    type: 'toggle',
    key: 'disabled',
    label: 'Disabled',
    group: 'Options',
  },
  {
    type: 'toggle',
    key: 'required',
    label: 'Required',
    group: 'Options',
  },
  {
    type: 'toggle',
    key: 'invalid',
    label: 'Invalid',
    group: 'Options',
  },
] as const satisfies readonly PlaygroundControl<TextareaPlaygroundValue>[];
