// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

'use client';

import { Textarea } from '@vellira-ui/react';

import { TextareaPlayground } from './TextareaPlayground';

export function TextareaDemo() {
  return (
    <TextareaPlayground
      platform='react'
      renderTextarea={(value, onChange) => (
        <Textarea
          value={value.value || undefined}
          onValueChange={(nextValue) => onChange('value', nextValue)}
          disabled={value.disabled}
          required={value.required}
          invalid={value.invalid}
        />
      )}
    />
  );
}
