import type { ComponentType } from 'react';

import accessibleAccordionReactNativeMetadata from '../../content/blog/accessible-accordion-react-native/metadata.json';
import componentMetadataSourceOfTruthMetadata from '../../content/blog/component-metadata-source-of-truth/metadata.json';
import controlledUncontrolledReactNativeMetadata from '../../content/blog/controlled-uncontrolled-react-native/metadata.json';
import crossPlatformFormVelliraMetadata from '../../content/blog/cross-platform-form-vellira/metadata.json';
import designSystemComponentGeneratorMetadata from '../../content/blog/design-system-component-generator/metadata.json';
import productionReadyCrossPlatformComponentMetadata from '../../content/blog/production-ready-cross-platform-component/metadata.json';
import qualityGatesBeforeComponentGrowthMetadata from '../../content/blog/quality-gates-before-component-growth/metadata.json';
import twoRuntimesMetadata from '../../content/blog/two-runtimes/metadata.json';

export interface BlogMDXModule {
  default: ComponentType;
}

export type BlogMDXModuleLoader = () => Promise<BlogMDXModule>;

export interface BlogArticleMetadataRegistryEntry {
  slug: string;
  metadata: unknown;
}

/**
 * Generated by Blog V1 authoring tooling.
 *
 * Keep MDX and metadata imports statically analyzable for Next.js/Turbopack
 * and Cloudflare Workers. Runtime rendering must not depend on repository fs.
 */
const blogArticleMetadataRegistryEntries = [
  {
    slug: 'accessible-accordion-react-native',
    metadata: accessibleAccordionReactNativeMetadata,
  },
  {
    slug: 'component-metadata-source-of-truth',
    metadata: componentMetadataSourceOfTruthMetadata,
  },
  {
    slug: 'controlled-uncontrolled-react-native',
    metadata: controlledUncontrolledReactNativeMetadata,
  },
  {
    slug: 'cross-platform-form-vellira',
    metadata: crossPlatformFormVelliraMetadata,
  },
  {
    slug: 'design-system-component-generator',
    metadata: designSystemComponentGeneratorMetadata,
  },
  {
    slug: 'production-ready-cross-platform-component',
    metadata: productionReadyCrossPlatformComponentMetadata,
  },
  {
    slug: 'quality-gates-before-component-growth',
    metadata: qualityGatesBeforeComponentGrowthMetadata,
  },
  { slug: 'two-runtimes', metadata: twoRuntimesMetadata },
] as const satisfies readonly BlogArticleMetadataRegistryEntry[];

const blogArticleModuleLoaders: Readonly<Record<string, BlogMDXModuleLoader>> =
  {
    'accessible-accordion-react-native': () =>
      import('../../content/blog/accessible-accordion-react-native/article.mdx'),
    'component-metadata-source-of-truth': () =>
      import('../../content/blog/component-metadata-source-of-truth/article.mdx'),
    'controlled-uncontrolled-react-native': () =>
      import('../../content/blog/controlled-uncontrolled-react-native/article.mdx'),
    'cross-platform-form-vellira': () =>
      import('../../content/blog/cross-platform-form-vellira/article.mdx'),
    'design-system-component-generator': () =>
      import('../../content/blog/design-system-component-generator/article.mdx'),
    'production-ready-cross-platform-component': () =>
      import('../../content/blog/production-ready-cross-platform-component/article.mdx'),
    'quality-gates-before-component-growth': () =>
      import('../../content/blog/quality-gates-before-component-growth/article.mdx'),
    'two-runtimes': () => import('../../content/blog/two-runtimes/article.mdx'),
  };

export function getBlogArticleMetadataRegistryEntries(): readonly BlogArticleMetadataRegistryEntry[] {
  return blogArticleMetadataRegistryEntries;
}

export function getBlogArticleModuleLoader(
  slug: string
): BlogMDXModuleLoader | null {
  return blogArticleModuleLoaders[slug] ?? null;
}
