import type { ComponentPlatform } from '@vellira-ui/metadata';

import type { PlatformDocsContract } from '../../../apps/docs/src/component-docs/types';
import { MIN_PUBLIC_META_DESCRIPTION_LENGTH } from '../../../apps/website/src/component-catalog/registry/componentSeo';

import {
  defaultAuthoredRegionPlaceholder,
  authoredRegionEndMarker,
  authoredRegionStartMarker,
} from './authored-region';

import type { ComponentApiSection } from './api';

const packageNameByPlatform = {
  react: '@vellira-ui/react',
  'react-native': '@vellira-ui/react-native',
} as const satisfies Record<ComponentPlatform, string>;

const docsDirectoryByPlatform = {
  react: 'react',
  'react-native': 'react-native',
} as const satisfies Record<ComponentPlatform, string>;

export const generatedComponentDocsHeader =
  '<!-- Generated by scripts/generators/component-docs/generate-component-docs.ts. Do not edit outside the authored region. -->';

export function renderComponentDocPage(params: {
  componentName: string;
  platform: ComponentPlatform;
  docs: PlatformDocsContract;
  apiSections: readonly ComponentApiSection[];
  authoredContent: string;
}) {
  const { componentName, platform, docs, apiSections, authoredContent } =
    params;
  const sections = [
    renderFrontmatter(docs),
    generatedComponentDocsHeader,
    `# ${componentName}`,
    docs.summary,
    renderImportSection(componentName, platform),
    renderStorybookSection(docs),
    renderApiSection(apiSections),
    renderListSection('When To Use', docs.whenToUse),
    renderListSection('Accessibility', docs.accessibility),
    renderRelatedComponentsSection(platform, docs),
    renderListSection('Notes', docs.notes),
    renderAuthoredRegion(authoredContent),
  ].filter(Boolean);

  return `${sections.join('\n\n')}\n`;
}

function renderFrontmatter(docs: PlatformDocsContract) {
  const description = publicMetaDescription(docs.description);
  return [
    '---',
    `title: ${JSON.stringify(docs.title)}`,
    `description: ${JSON.stringify(description)}`,
    '---',
  ].join('\n');
}

function publicMetaDescription(value: string) {
  const description = value.trim();
  if (description.length >= MIN_PUBLIC_META_DESCRIPTION_LENGTH) {
    return description;
  }
  return `${description} Includes Vellira usage, API, and accessibility guidance for production interfaces.`;
}

function renderImportSection(
  componentName: string,
  platform: ComponentPlatform
) {
  return [
    '## Import',
    '```tsx',
    `import { ${componentName} } from '${packageNameByPlatform[platform]}';`,
    '```',
  ].join('\n');
}

function renderStorybookSection(docs: PlatformDocsContract) {
  if (!docs.storybook) {
    return '';
  }

  return [
    '## Storybook',
    '<StorybookFrame',
    `  id="${storybookIdFromReference(docs.storybook.title, docs.storybook.story)}"`,
    `  title="${escapeHtmlAttribute(docs.storybook.title)} - ${escapeHtmlAttribute(
      docs.storybook.story
    )}"`,
    `  :height="${docs.storybook.height ?? 360}"`,
    '/>',
  ].join('\n');
}

function renderApiSection(apiSections: readonly ComponentApiSection[]) {
  const apiSourcePath = apiSections[0]?.relativeApiPath;

  if (!apiSourcePath) {
    return '';
  }

  return [
    '## API',
    `API details are generated from \`${apiSourcePath}\`.`,
    apiSections.length === 1
      ? apiSections[0].block
      : apiSections
          .map((section) =>
            [`### ${section.title}`, section.block].join('\n\n')
          )
          .join('\n\n'),
  ].join('\n\n');
}

function renderListSection(title: string, items?: readonly string[]) {
  if (!items || items.length === 0) {
    return '';
  }

  return [`## ${title}`, items.map((item) => `- ${item}`).join('\n')].join(
    '\n\n'
  );
}

function renderRelatedComponentsSection(
  platform: ComponentPlatform,
  docs: PlatformDocsContract
) {
  if (!docs.seeAlso || docs.seeAlso.length === 0) {
    return '';
  }

  const docsDirectory = docsDirectoryByPlatform[platform];
  const items = docs.seeAlso.map((item) => {
    const link = `/${docsDirectory}/${slugifyComponentName(item.component)}`;

    return item.label
      ? `- [${item.component}](${link}) - ${item.label}`
      : `- [${item.component}](${link})`;
  });

  return ['## See Also', items.join('\n')].join('\n\n');
}

function renderAuthoredRegion(authoredContent: string) {
  return [
    authoredRegionStartMarker,
    authoredContent.trim().length > 0
      ? authoredContent.trimEnd()
      : defaultAuthoredRegionPlaceholder,
    authoredRegionEndMarker,
  ].join('\n');
}

function storybookIdFromReference(title: string, story: string) {
  return `${slugifyStorybookSegment(title)}--${slugifyStorybookSegment(story)}`;
}

function slugifyStorybookSegment(value: string) {
  return value
    .trim()
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/[^a-zA-Z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .toLowerCase();
}

function slugifyComponentName(componentName: string) {
  return componentName
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/[^a-zA-Z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .toLowerCase();
}

function escapeHtmlAttribute(value: string) {
  return value
    .replace(/&/g, '&amp;')
    .replace(/"/g, '&quot;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}
