import fs from 'node:fs';
import path from 'node:path';

import { formatGeneratedContent } from '../../format-generated-files';

import { objectPropertyKey, slugify } from '../helpers/format';
import type { GeneratedPageModel } from '../model/types';

const generatedPreviewFileName = 'generatedCatalogPreviews.ts';

function getCatalogEntrySource(source: string, slug: string) {
  const slugMarker = `slug: '${slug}'`;

  if (!source.includes(slugMarker)) {
    return null;
  }

  const slugIndex = source.indexOf(slugMarker);
  const entryStart = source.lastIndexOf('\n  {', slugIndex);

  if (entryStart < 0) {
    throw new Error(
      `Could not determine component catalog entry start for ${slug}`
    );
  }

  let depth = 0;

  for (let index = entryStart + 1; index < source.length; index += 1) {
    if (source[index] === '{') depth += 1;

    if (source[index] === '}') {
      depth -= 1;

      if (depth === 0) {
        let entryEnd = index + 1;

        if (source[entryEnd] === ',') entryEnd += 1;
        if (source[entryEnd] === '\n') entryEnd += 1;

        return source.slice(entryStart + 1, entryEnd);
      }
    }
  }

  throw new Error(
    `Could not determine component catalog entry end for ${slug}`
  );
}

export function requiresGeneratedCatalogPreview(params: {
  componentsRegistryFile: string;
  model: GeneratedPageModel;
}) {
  const source = fs.readFileSync(params.componentsRegistryFile, 'utf8');
  const existingEntry = getCatalogEntrySource(source, params.model.slug);

  if (!existingEntry) {
    return true;
  }

  return (
    existingEntry.includes(
      `description: '${params.model.componentName} component for Vellira applications.'`
    ) &&
    existingEntry.includes("status: 'beta'") &&
    existingEntry.includes('order: 999')
  );
}

export function renderGeneratedCatalogPreview(params: {
  model: GeneratedPageModel;
  generatedFileHeader: string;
}) {
  const { model, generatedFileHeader } = params;
  const demoName = model.platforms.includes('react')
    ? `${model.componentName}Demo`
    : `Native${model.componentName}Demo`;

  return `${generatedFileHeader}'use client';

import { ${demoName} } from './${demoName}';

export function ${model.componentName}CatalogPreview() {
  return <${demoName} />;
}
`;
}

export async function synchronizeGeneratedCatalogPreview(params: {
  root: string;
  check: boolean;
  checkFailures: string[];
  componentCatalogDir: string;
  componentsRegistryFile: string;
  model: GeneratedPageModel;
  generatedFileHeader: string;
}) {
  if (
    !requiresGeneratedCatalogPreview({
      componentsRegistryFile: params.componentsRegistryFile,
      model: params.model,
    })
  ) {
    return;
  }

  const previewFile = path.join(
    params.componentCatalogDir,
    `${params.model.componentName}CatalogPreview.tsx`
  );
  const currentSource = fs.existsSync(previewFile)
    ? fs.readFileSync(previewFile, 'utf8')
    : null;

  if (
    currentSource !== null &&
    !currentSource.startsWith(params.generatedFileHeader)
  ) {
    return;
  }

  const expectedSource = await formatGeneratedContent(
    previewFile,
    renderGeneratedCatalogPreview({
      model: params.model,
      generatedFileHeader: params.generatedFileHeader,
    })
  );

  if (currentSource === expectedSource) {
    return;
  }

  if (params.check) {
    params.checkFailures.push(path.relative(params.root, previewFile));
    return;
  }

  fs.mkdirSync(path.dirname(previewFile), { recursive: true });
  fs.writeFileSync(previewFile, expectedSource);
  console.log(
    `${currentSource === null ? '✅ Created' : '♻️ Updated'}: ${path.relative(
      params.root,
      previewFile
    )}`
  );
}

export function renderGeneratedCatalogPreviewRegistry(params: {
  componentsRoot: string;
}) {
  const previews = fs
    .readdirSync(params.componentsRoot, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => {
      const componentName = entry.name;
      const previewFile = path.join(
        params.componentsRoot,
        componentName,
        `${componentName}CatalogPreview.tsx`
      );

      return fs.existsSync(previewFile)
        ? {
            componentName,
            slug: slugify(componentName),
          }
        : null;
    })
    .filter(
      (
        preview
      ): preview is {
        componentName: string;
        slug: string;
      } => Boolean(preview)
    )
    .sort((left, right) => left.slug.localeCompare(right.slug));

  const imports = previews
    .map(
      ({ componentName }) =>
        `import { ${componentName}CatalogPreview } from '../components/${componentName}/${componentName}CatalogPreview';`
    )
    .join('\n');
  const entries = previews
    .map(
      ({ componentName, slug }) =>
        `  ${objectPropertyKey(slug)}: ${componentName}CatalogPreview,`
    )
    .join('\n');

  return `// Generated by scripts/generators/component-page/renderers/catalog-preview-registry.ts.
// Do not edit manually.

import type { ComponentType } from 'react';

${imports}

export const generatedCatalogPreviews = {
${entries}
} as const satisfies Record<string, ComponentType>;
`;
}

export async function synchronizeGeneratedCatalogPreviewRegistry(params: {
  root: string;
  check: boolean;
  checkFailures: string[];
  componentCatalogDir: string;
  componentsRegistryFile: string;
}) {
  const registryFile = path.join(
    path.dirname(params.componentsRegistryFile),
    generatedPreviewFileName
  );
  const componentsRoot = path.dirname(params.componentCatalogDir);
  const expectedSource = await formatGeneratedContent(
    registryFile,
    renderGeneratedCatalogPreviewRegistry({ componentsRoot })
  );
  const currentSource = fs.existsSync(registryFile)
    ? fs.readFileSync(registryFile, 'utf8')
    : null;

  if (currentSource === expectedSource) {
    return;
  }

  if (params.check) {
    params.checkFailures.push(path.relative(params.root, registryFile));
    return;
  }

  fs.writeFileSync(registryFile, expectedSource);
  console.log(
    `♻️ Updated catalog preview registry: ${path.relative(params.root, registryFile)}`
  );
}
