packages:
  - 'packages/*'
  - 'apps/*'
allowBuilds:
  '@parcel/watcher': true
  deasync: true
  esbuild: true
  sharp: true
  unrs-resolver: true
  workerd: true
minimumReleaseAgeExclude:
  - '@storybook/addon-ondevice-actions@10.4.5'
  - '@storybook/addon-ondevice-controls@10.4.5'
  - '@storybook/react-native-theming@10.4.5'
  - '@storybook/react-native-ui-common@10.4.5'
  - '@storybook/react-native-ui-lite@10.4.5'
  - '@storybook/react-native-ui@10.4.5'
  - '@storybook/react-native@10.4.5'
nodeLinker: hoisted

overrides:
  '@puppeteer/browsers': 3.0.6
  'brace-expansion@<2.0.0': 1.1.18
  colord: 2.9.4
  'minimatch@10>brace-expansion': 5.0.9

  'esbuild@<=0.24.2': 0.28.1
  fast-uri: 3.1.6

  '@xmldom/xmldom@0.8.14': 0.8.15
  '@xmldom/xmldom@0.9.11': 0.9.12

  'js-yaml@<4': 3.15.2
  'js-yaml@>=4 <5': 4.3.2

  metro: 0.84.5
  metro-babel-transformer: 0.84.5
  metro-cache: 0.84.5
  metro-cache-key: 0.84.5
  metro-config: 0.84.5
  metro-core: 0.84.5
  metro-file-map: 0.84.5
  metro-minify-terser: 0.84.5
  metro-resolver: 0.84.5
  metro-runtime: 0.84.5
  metro-source-map: 0.84.5
  metro-symbolicate: 0.84.5
  metro-transform-plugins: 0.84.5
  metro-transform-worker: 0.84.5

  'nanoid@<3.3.18': 3.3.18
  postcss: 8.5.23
  qs: 6.16.0

  sharp: 0.35.4

  'undici@<7': 6.28.0
  'undici@>=7 <8': 7.29.0

  'uuid@<11.1.1': 11.1.1
  'valibot@<=1.4.1': 1.4.2
  'vite@<=6.4.2': 6.4.3
  tmp: 0.2.7

patchedDependencies:
  next@16.3.3: patches/next@16.3.3.patch
allowUnusedPatches: false
