packages:
  - 'packages/*'
  - 'apps/*'
allowBuilds:
  '@parcel/watcher': true
  deasync: true
  esbuild: true
  sharp: true
  unrs-resolver: true
  workerd: true
minimumReleaseAgeExclude:
  - '@storybook/addon-ondevice-actions@10.4.5'
  - '@storybook/addon-ondevice-controls@10.4.5'
  - '@storybook/react-native-theming@10.4.5'
  - '@storybook/react-native-ui-common@10.4.5'
  - '@storybook/react-native-ui-lite@10.4.5'
  - '@storybook/react-native-ui@10.4.5'
  - '@storybook/react-native@10.4.5'
nodeLinker: hoisted

overrides:
  'brace-expansion@<2.0.0': 1.1.18
  'minimatch@10>brace-expansion': 5.0.9

  'esbuild@<=0.24.2': 0.28.1
  fast-uri: 3.1.6

  '@xmldom/xmldom@0.8.14': 0.8.15
  '@xmldom/xmldom@0.9.11': 0.9.12

  'js-yaml@<4': 3.15.1
  'js-yaml@>=4 <5': 4.3.1

  'nanoid@<3.3.18': 3.3.18
  postcss: 8.5.23
  qs: 6.16.0

  sharp: 0.35.3

  'undici@<7': 6.28.0
  'undici@>=7 <8': 7.29.0

  'uuid@<11.1.1': 11.1.1
  'valibot@<=1.4.1': 1.4.2
  'vite@<=6.4.2': 6.4.3
  tmp: 0.2.7