// Generated by scripts/generators/component-page/renderers/catalog-preview-registry.ts.
// Do not edit manually.

import type { ComponentType } from 'react';

import { AccordionCatalogPreview } from '../components/Accordion/AccordionCatalogPreview';
import { SwitchCatalogPreview } from '../components/Switch/SwitchCatalogPreview';

export const generatedCatalogPreviews = {
  accordion: AccordionCatalogPreview,
  switch: SwitchCatalogPreview,
} as const satisfies Record<string, ComponentType>;
