import type { ComponentExpansionTarget } from './expansion';

export const componentExpansionCatalog = [
  {
    name: 'Textarea',
    layer: 'primitives',
    category: 'form',
    platforms: ['react', 'react-native'],
    profile: 'form-control',
    componentTokens: 'standard',
    role: 'form-control',
    intent: {
      schemaVersion: '1',
      job: 'Enter and edit multiline text.',
      requiredCapabilities: [
        'controlled',
        'uncontrolled',
        'disabled',
        'required',
        'invalid',
        'multiline',
        'accessible-name',
      ],
    },
  },
  {
    name: 'Accordion',
    layer: 'components',
    category: 'navigation',
    platforms: ['react', 'react-native'],
    profile: 'compound',
    componentTokens: 'disclosure',
    role: 'catalog',
    intent: {
      schemaVersion: '1',
      job: 'Expand and collapse grouped disclosure content.',
      requiredCapabilities: [
        'compound-api',
        'multiple',
        'controlled',
        'uncontrolled',
        'collapsible',
        'disabled',
      ],
      platformRequirements: {
        react: ['keyboard'],
      },
    },
  },
  {
    name: 'Avatar',
    layer: 'primitives',
    category: 'data-display',
    platforms: ['react', 'react-native'],
    profile: 'base',
    componentTokens: 'standard',
    role: 'foundational',
    intent: {
      schemaVersion: '1',
      job: 'Represent a person or entity with an image and deterministic fallback.',
      requiredCapabilities: [
        'image-source',
        'fallback',
        'size-variants',
        'accessible-name',
      ],
    },
  },
  {
    name: 'Badge',
    layer: 'primitives',
    category: 'data-display',
    platforms: ['react', 'react-native'],
    profile: 'base',
    componentTokens: 'standard',
    role: 'foundational',
    intent: {
      schemaVersion: '1',
      job: 'Present compact status, category, or count-like labels.',
      requiredCapabilities: ['size-variants'],
    },
  },
  {
    name: 'Progress',
    layer: 'primitives',
    category: 'feedback',
    platforms: ['react', 'react-native'],
    profile: 'base',
    componentTokens: 'standard',
    role: 'foundational',
    intent: {
      schemaVersion: '1',
      job: 'Communicate bounded task or process progress.',
      requiredCapabilities: ['value-range', 'accessible-value'],
    },
  },
  {
    name: 'Skeleton',
    layer: 'primitives',
    category: 'feedback',
    platforms: ['react', 'react-native'],
    profile: 'base',
    componentTokens: 'standard',
    role: 'foundational',
    intent: {
      schemaVersion: '1',
      job: 'Represent content structure while data is loading.',
      requiredCapabilities: ['loading', 'reduced-motion'],
    },
  },
  {
    name: 'Toast',
    layer: 'components',
    category: 'feedback',
    platforms: ['react', 'react-native'],
    profile: 'overlay',
    componentTokens: 'standard',
    role: 'catalog',
    intent: {
      schemaVersion: '1',
      job: 'Present transient non-blocking feedback with a deterministic lifecycle.',
      requiredCapabilities: [
        'dismissible',
        'auto-dismiss',
        'stacking',
        'announcement',
        'reduced-motion',
      ],
    },
  },
] as const satisfies readonly ComponentExpansionTarget[];
