// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

'use client';

import type { ComponentPlatform } from '../../types';

import { ComponentCodeBlock } from '../../shared/ComponentCodeBlock';
import { useComponentDemoState } from '../../shared/ComponentDemoStateProvider';

import {
  initialAccordionPlaygroundValue,
  type AccordionPlaygroundValue,
} from './AccordionPlayground';

import styles from '../../shared/ComponentUsage.module.css';

type AccordionUsageProps = {
  platform: ComponentPlatform;
};

function createAccordionCode(
  platform: ComponentPlatform,
  value: AccordionPlaygroundValue
) {
  const packageName =
    platform === 'react' ? '@vellira-ui/react' : '@vellira-ui/react-native';

  const props: string[] = platform === 'react' ? [] : [];

  const children =
    platform === 'react'
      ? `  <Accordion.Item value='profile'>
    <Accordion.Trigger>Profile settings</Accordion.Trigger>
    <Accordion.Content>Update your public profile and account details.</Accordion.Content>
  </Accordion.Item>
  <Accordion.Item value='notifications'>
    <Accordion.Trigger>Notifications</Accordion.Trigger>
    <Accordion.Content>Choose when you want to receive updates.</Accordion.Content>
  </Accordion.Item>`
      : `  <Accordion.Item value='profile'>
    <Accordion.Trigger>Profile settings</Accordion.Trigger>
    <Accordion.Content>
      <NativeText
        style={{
        color: nativeTheme.components.accordion.content.fg,
        fontFamily: 'VelliraSans-Regular',
        fontSize: 16,
        lineHeight: 22,
      }}
      >
        Update your public profile and account details.
      </NativeText>
    </Accordion.Content>
  </Accordion.Item>
  <Accordion.Item value='notifications'>
    <Accordion.Trigger>Notifications</Accordion.Trigger>
    <Accordion.Content>
      <NativeText
        style={{
        color: nativeTheme.components.accordion.content.fg,
        fontFamily: 'VelliraSans-Regular',
        fontSize: 16,
        lineHeight: 22,
      }}
      >
        Choose when you want to receive updates.
      </NativeText>
    </Accordion.Content>
  </Accordion.Item>`;

  if (value.collapsible) {
    props.push('collapsible');
  }

  if (value.disabled) {
    props.push('disabled');
  }

  const propsText = props.length === 0 ? '' : `\n  ${props.join('\n  ')}\n`;

  const imports = `import { Accordion } from '${packageName}';${
    platform === 'react'
      ? ``
      : `
import { Text as NativeText } from 'react-native';
import { useTheme } from '@vellira-ui/react-native';`
  }`;

  const setup =
    platform === 'react' ? `` : `  const { theme: nativeTheme } = useTheme();`;

  const root = !children
    ? `<Accordion${propsText}/>`
    : `<Accordion${propsText}>
${children}
</Accordion>`;

  if (setup) {
    const indentedRoot = root
      .split('\n')
      .map((line) => `    ${line}`)
      .join('\n');

    return `${imports}

function Example() {
${setup}

  return (
${indentedRoot}
  );
}`;
  }

  return `${imports}

${root}`;
}

export function AccordionUsage({ platform }: AccordionUsageProps) {
  const [value] = useComponentDemoState<AccordionPlaygroundValue>(
    initialAccordionPlaygroundValue
  );

  const code = createAccordionCode(platform, value);

  return (
    <section className={styles.root}>
      <div className={styles.header}>
        <h2 className={styles.title}>Usage</h2>

        <p className={styles.description}>
          Import the component and configure it with the same props used in the
          playground.
        </p>
      </div>

      <ComponentCodeBlock code={code} />
    </section>
  );
}
