// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

'use client';

import type { ReactNode } from 'react';

import { ComponentPlayground } from '../../shared/ComponentPlayground';
import { useComponentDemoState } from '../../shared/ComponentDemoStateProvider';
import { PlaygroundControlsFromSchema } from '../../shared/PlaygroundControls';

import { accordionPlaygroundControls } from './accordionPlaygroundSchema';

export type AccordionPlaygroundValue = {
  collapsible: boolean;
  disabled: boolean;
};

type AccordionPlaygroundProps = {
  platform: 'react' | 'react-native';
  renderAccordion: (
    value: AccordionPlaygroundValue,
    onChange: <K extends keyof AccordionPlaygroundValue>(
      key: K,
      nextValue: AccordionPlaygroundValue[K]
    ) => void
  ) => ReactNode;
};

export const initialAccordionPlaygroundValue: AccordionPlaygroundValue = {
  collapsible: false,
  disabled: false,
};

export function AccordionPlayground({
  platform,
  renderAccordion,
}: AccordionPlaygroundProps) {
  const [value, setValue] = useComponentDemoState<AccordionPlaygroundValue>(
    initialAccordionPlaygroundValue
  );

  const update = (
    key: keyof AccordionPlaygroundValue,
    nextValue: AccordionPlaygroundValue[keyof AccordionPlaygroundValue]
  ) => {
    setValue({
      ...value,
      [key]: nextValue,
    });
  };

  return (
    <ComponentPlayground
      previewWidth='field'
      controls={
        <PlaygroundControlsFromSchema
          platform={platform}
          value={value}
          controls={accordionPlaygroundControls}
          onChange={update}
        />
      }
    >
      {renderAccordion(value, update)}
    </ComponentPlayground>
  );
}
