// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

import type {
  ComponentApiProp,
  ComponentApiSection,
} from '../../shared/ComponentApi';

const reactAccordionApiSections: readonly ComponentApiSection[] = [
  {
    name: 'Accordion',
    props: [
      {
        name: 'type',
        type: "'single' | 'multiple'",
        defaultValue: "'single'",
        description:
          'Determines whether one item or multiple items can be expanded.',
      },
      {
        name: 'value',
        type: 'string | string[]',
        description: 'Controlled expanded value or values.',
      },
      {
        name: 'defaultValue',
        type: 'string | string[]',
        description: 'Initial expanded value or values for uncontrolled usage.',
      },
      {
        name: 'onValueChange',
        type: '((value: string) => void) | ((value: string[]) => void)',
        description:
          'Called with the next expanded value or values after interaction.',
      },
      {
        name: 'collapsible',
        type: 'boolean',
        defaultValue: 'false',
        description:
          'Allows an expanded single item to collapse back to no selection.',
      },
      {
        name: 'disabled',
        type: 'boolean',
        defaultValue: 'false',
        description: 'Disables interaction for the root, item, or trigger.',
      },
      {
        name: 'children',
        type: 'ReactNode',
        description:
          'Compound Accordion.Item, Accordion.Trigger, and Accordion.Content nodes.',
      },
    ],
  },
  {
    name: 'Accordion.Item',
    props: [
      {
        name: 'value',
        type: 'string',
        description: 'Controlled expanded value or values.',
        required: true,
      },
      {
        name: 'disabled',
        type: 'boolean',
        defaultValue: 'false',
        description: 'Disables interaction for the root, item, or trigger.',
      },
      {
        name: 'children',
        type: 'ReactNode',
        description:
          'Compound Accordion.Item, Accordion.Trigger, and Accordion.Content nodes.',
      },
    ],
  },
  {
    name: 'Accordion.Trigger',
    props: [
      {
        name: 'disabled',
        type: 'boolean',
        defaultValue: 'false',
        description: 'Disables interaction for the root, item, or trigger.',
      },
      {
        name: 'children',
        type: 'ReactNode',
        description:
          'Compound Accordion.Item, Accordion.Trigger, and Accordion.Content nodes.',
      },
    ],
  },
  {
    name: 'Accordion.Content',
    props: [
      {
        name: 'forceMount',
        type: 'boolean',
        description: 'Keeps content mounted even when the item is collapsed.',
      },
      {
        name: 'children',
        type: 'ReactNode',
        description:
          'Compound Accordion.Item, Accordion.Trigger, and Accordion.Content nodes.',
      },
    ],
  },
];

const nativeAccordionApiSections: readonly ComponentApiSection[] = [
  {
    name: 'Accordion',
    props: [
      {
        name: 'type',
        type: "'single' | 'multiple'",
        defaultValue: "'single'",
        description:
          'Determines whether one item or multiple items can be expanded.',
      },
      {
        name: 'value',
        type: 'string | string[]',
        description: 'Controlled expanded value or values.',
      },
      {
        name: 'defaultValue',
        type: 'string | string[]',
        description: 'Initial expanded value or values for uncontrolled usage.',
      },
      {
        name: 'onValueChange',
        type: '((value: string) => void) | ((value: string[]) => void)',
        description:
          'Called with the next expanded value or values after interaction.',
      },
      {
        name: 'collapsible',
        type: 'boolean',
        defaultValue: 'false',
        description:
          'Allows an expanded single item to collapse back to no selection.',
      },
      {
        name: 'disabled',
        type: 'boolean',
        defaultValue: 'false',
        description: 'Disables interaction for the root, item, or trigger.',
      },
      {
        name: 'children',
        type: 'ReactNode',
        description:
          'Compound Accordion.Item, Accordion.Trigger, and Accordion.Content nodes.',
      },
    ],
  },
  {
    name: 'Accordion.Item',
    props: [
      {
        name: 'value',
        type: 'string',
        description: 'Controlled expanded value or values.',
        required: true,
      },
      {
        name: 'disabled',
        type: 'boolean',
        defaultValue: 'false',
        description: 'Disables interaction for the root, item, or trigger.',
      },
      {
        name: 'children',
        type: 'ReactNode',
        description:
          'Compound Accordion.Item, Accordion.Trigger, and Accordion.Content nodes.',
      },
    ],
  },
  {
    name: 'Accordion.Trigger',
    props: [
      {
        name: 'disabled',
        type: 'boolean',
        defaultValue: 'false',
        description: 'Disables interaction for the root, item, or trigger.',
      },
      {
        name: 'children',
        type: 'ReactNode',
        description:
          'Compound Accordion.Item, Accordion.Trigger, and Accordion.Content nodes.',
      },
    ],
  },
  {
    name: 'Accordion.Content',
    props: [
      {
        name: 'forceMount',
        type: 'boolean',
        description: 'Keeps content mounted even when the item is collapsed.',
      },
      {
        name: 'children',
        type: 'ReactNode',
        description:
          'Compound Accordion.Item, Accordion.Trigger, and Accordion.Content nodes.',
      },
    ],
  },
];

const inheritedReactAccordionApi: readonly ComponentApiProp[] = [];

const inheritedNativeAccordionApi: readonly ComponentApiProp[] = [];

export const accordionApi = {
  react: {
    sections: reactAccordionApiSections,
    inheritedProps: inheritedReactAccordionApi,
  },
  'react-native': {
    sections: nativeAccordionApiSections,
    inheritedProps: inheritedNativeAccordionApi,
  },
} as const;
