// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

import type { PlaygroundControl } from '../../shared/PlaygroundControls';

import type { AccordionPlaygroundValue } from './AccordionPlayground';

export const accordionPlaygroundControls = [
  {
    type: 'toggle',
    key: 'collapsible',
    label: 'Collapsible',
    group: 'Options',
  },
  {
    type: 'toggle',
    key: 'disabled',
    label: 'Disabled',
    group: 'Options',
  },
] as const satisfies readonly PlaygroundControl<AccordionPlaygroundValue>[];
