// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

'use client';

import { Accordion } from '@vellira-ui/react-native';
import { Text as NativeText } from 'react-native';
import { useTheme } from '@vellira-ui/react-native';

import { AccordionPlayground } from './AccordionPlayground';

export function NativeAccordionDemo() {
  const { theme: nativeTheme } = useTheme();

  return (
    <AccordionPlayground
      platform='react-native'
      renderAccordion={(value) => (
        <Accordion collapsible={value.collapsible} disabled={value.disabled}>
          <Accordion.Item value='profile'>
            <Accordion.Trigger>Profile settings</Accordion.Trigger>
            <Accordion.Content>
              <NativeText
                style={{
                  color: nativeTheme.components.accordion.content.fg,
                  fontFamily: 'VelliraSans-Regular',
                  fontSize: 16,
                  lineHeight: 22,
                }}
              >
                Update your public profile and account details.
              </NativeText>
            </Accordion.Content>
          </Accordion.Item>
          <Accordion.Item value='notifications'>
            <Accordion.Trigger>Notifications</Accordion.Trigger>
            <Accordion.Content>
              <NativeText
                style={{
                  color: nativeTheme.components.accordion.content.fg,
                  fontFamily: 'VelliraSans-Regular',
                  fontSize: 16,
                  lineHeight: 22,
                }}
              >
                Choose when you want to receive updates.
              </NativeText>
            </Accordion.Content>
          </Accordion.Item>
        </Accordion>
      )}
    />
  );
}
