// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

'use client';

import { Toast } from '@vellira-ui/react-native';

import { ToastPlayground } from './ToastPlayground';

export function NativeToastDemo() {
  return (
    <ToastPlayground
      platform='react-native'
      renderToast={(value, onChange) => (
        <Toast
          title='Changes saved'
          description='Your preferences are up to date.'
          duration={0}
          open={value.open}
          onOpenChange={(nextValue) => onChange('open', nextValue)}
        />
      )}
    />
  );
}
