// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

import type {
  ComponentApiProp,
  ComponentApiSection,
} from '../../shared/ComponentApi';

const reactToastApiSections: readonly ComponentApiSection[] = [
  {
    name: 'Toast',
    props: [
      {
        name: 'open',
        type: 'boolean',
        description: 'Controlled visibility state.',
      },
      {
        name: 'defaultOpen',
        type: 'boolean',
        description: 'Initial visibility for uncontrolled usage.',
      },
      {
        name: 'onOpenChange',
        type: '((open: boolean, details?: ToastOpenChangeDetails) => void)',
        description:
          'Called with the next visibility and the deterministic close reason.',
      },
      {
        name: 'id',
        type: 'string',
        description: 'Stable identifier for the rendered toast.',
      },
      {
        name: 'title',
        type: 'ReactNode',
        description: 'Short message heading.',
      },
      {
        name: 'description',
        type: 'ReactNode',
        description: 'Optional supporting detail.',
      },
      {
        name: 'icon',
        type: 'ReactNode',
        description:
          'Optional custom icon; semantic tones provide canonical defaults.',
      },
      {
        name: 'children',
        type: 'ReactNode',
        description: 'Optional custom message content.',
      },
      {
        name: 'tone',
        type: "'neutral' | 'info' | 'success' | 'warning' | 'error' | 'danger'",
        description: 'Semantic tone used for color and announcement priority.',
      },
      {
        name: 'duration',
        type: 'number',
        description:
          'Auto-dismiss duration in milliseconds. Set to 0 to persist.',
      },
      {
        name: 'dismissible',
        type: 'boolean',
        description: 'Whether to render an explicit dismiss control.',
      },
      {
        name: 'dismissLabel',
        type: 'string',
        description: 'Accessible name for the dismiss control.',
      },
      {
        name: 'action',
        type: 'ToastAction',
        description:
          'Optional labelled action with deterministic close behavior.',
      },
      {
        name: 'pauseOnHover',
        type: 'boolean',
        description:
          'Whether pointer hover pauses the remaining web auto-dismiss timeout.',
      },
      {
        name: 'pauseOnFocus',
        type: 'boolean',
        description:
          'Whether focus within the toast pauses the remaining web timeout.',
      },
      {
        name: 'closeOnEscape',
        type: 'boolean',
        description:
          'Whether Escape dismisses a web toast while one of its controls has focus.',
      },
      {
        name: 'ariaLive',
        type: "'assertive' | 'off' | 'polite'",
        description: 'Overrides the tone-derived web live-region priority.',
      },
      {
        name: 'className',
        type: 'string',
        description: 'Additional class name for the web toast or viewport.',
      },
      {
        name: 'style',
        type: 'CSSProperties',
        description: 'Platform style override for the toast or viewport.',
      },
    ],
  },
  {
    name: 'Toast.Provider',
    props: [
      {
        name: 'children',
        type: 'ReactNode',
        description: 'Optional custom message content.',
      },
      {
        name: 'store',
        type: 'ToastStore',
        description:
          'Externally owned store for integration or independent testing.',
      },
      {
        name: 'duration',
        type: 'number',
        description:
          'Auto-dismiss duration in milliseconds. Set to 0 to persist.',
      },
      {
        name: 'maxVisible',
        type: 'number',
        description:
          'Maximum number of visible messages before oldest-first overflow.',
      },
    ],
  },
  {
    name: 'Toast.Viewport',
    props: [
      {
        name: 'children',
        type: 'ReactNode',
        description: 'Optional custom message content.',
      },
      {
        name: 'portal',
        type: 'boolean',
        description:
          'Whether the web viewport renders through the canonical Portal.',
      },
      {
        name: 'container',
        type: 'Element | DocumentFragment | null',
        description: 'Optional web portal destination.',
      },
      {
        name: 'position',
        type: "'top-start' | 'top-center' | 'top-end' | 'bottom-start' | 'bottom-center' | 'bottom-end'",
        description: 'Viewport edge and alignment.',
      },
      {
        name: 'label',
        type: 'string',
        description: 'Accessible name for the web notification region.',
      },
      {
        name: 'className',
        type: 'string',
        description: 'Additional class name for the web toast or viewport.',
      },
      {
        name: 'style',
        type: 'CSSProperties',
        description: 'Platform style override for the toast or viewport.',
      },
    ],
  },
];

const nativeToastApiSections: readonly ComponentApiSection[] = [
  {
    name: 'Toast',
    props: [
      {
        name: 'open',
        type: 'boolean',
        description: 'Controlled visibility state.',
      },
      {
        name: 'defaultOpen',
        type: 'boolean',
        description: 'Initial visibility for uncontrolled usage.',
      },
      {
        name: 'onOpenChange',
        type: '((open: boolean, details?: ToastOpenChangeDetails) => void)',
        description:
          'Called with the next visibility and the deterministic close reason.',
      },
      {
        name: 'id',
        type: 'string',
        description: 'Stable identifier for the rendered toast.',
      },
      {
        name: 'title',
        type: 'ReactNode',
        description: 'Short message heading.',
      },
      {
        name: 'description',
        type: 'ReactNode',
        description: 'Optional supporting detail.',
      },
      {
        name: 'icon',
        type: 'ReactNode',
        description:
          'Optional custom icon; semantic tones provide canonical defaults.',
      },
      {
        name: 'children',
        type: 'ReactNode',
        description: 'Optional custom message content.',
      },
      {
        name: 'announcement',
        type: 'string',
        description: 'Explicit text announced by native assistive technology.',
      },
      {
        name: 'tone',
        type: "'neutral' | 'info' | 'success' | 'warning' | 'error' | 'danger'",
        description: 'Semantic tone used for color and announcement priority.',
      },
      {
        name: 'duration',
        type: 'number',
        description:
          'Auto-dismiss duration in milliseconds. Set to 0 to persist.',
      },
      {
        name: 'dismissible',
        type: 'boolean',
        description: 'Whether to render an explicit dismiss control.',
      },
      {
        name: 'dismissLabel',
        type: 'string',
        description: 'Accessible name for the dismiss control.',
      },
      {
        name: 'action',
        type: 'ToastAction',
        description:
          'Optional labelled action with deterministic close behavior.',
      },
      {
        name: 'accessibilityLabel',
        type: 'string',
        description: 'Native accessible label.',
      },
      {
        name: 'style',
        type: 'StyleProp<ViewStyle>',
        description: 'Platform style override for the toast or viewport.',
      },
      {
        name: 'testID',
        type: 'string',
        description: 'Stable native test identifier.',
      },
    ],
  },
  {
    name: 'Toast.Provider',
    props: [
      {
        name: 'children',
        type: 'ReactNode',
        description: 'Optional custom message content.',
      },
      {
        name: 'store',
        type: 'ToastStore',
        description:
          'Externally owned store for integration or independent testing.',
      },
      {
        name: 'duration',
        type: 'number',
        description:
          'Auto-dismiss duration in milliseconds. Set to 0 to persist.',
      },
      {
        name: 'maxVisible',
        type: 'number',
        description:
          'Maximum number of visible messages before oldest-first overflow.',
      },
    ],
  },
  {
    name: 'Toast.Viewport',
    props: [
      {
        name: 'children',
        type: 'ReactNode',
        description: 'Optional custom message content.',
      },
      {
        name: 'portal',
        type: 'boolean',
        description:
          'Whether the web viewport renders through the canonical Portal.',
      },
      {
        name: 'position',
        type: "'top-start' | 'top-center' | 'top-end' | 'bottom-start' | 'bottom-center' | 'bottom-end'",
        description: 'Viewport edge and alignment.',
      },
      {
        name: 'accessibilityLabel',
        type: 'string',
        description: 'Native accessible label.',
      },
      {
        name: 'style',
        type: 'StyleProp<ViewStyle>',
        description: 'Platform style override for the toast or viewport.',
      },
      {
        name: 'testID',
        type: 'string',
        description: 'Stable native test identifier.',
      },
    ],
  },
];

const inheritedReactToastApi: readonly ComponentApiProp[] = [];

const inheritedNativeToastApi: readonly ComponentApiProp[] = [];

export const toastApi = {
  react: {
    sections: reactToastApiSections,
    inheritedProps: inheritedReactToastApi,
  },
  'react-native': {
    sections: nativeToastApiSections,
    inheritedProps: inheritedNativeToastApi,
  },
} as const;
