// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

'use client';

import type { ComponentPlatform } from '../../types';

import { ComponentAccessibility } from '../../shared/ComponentAccessibility';

type ToastAccessibilityProps = {
  platform: ComponentPlatform;
};

export function ToastAccessibility({ platform }: ToastAccessibilityProps) {
  const reactItems = [
    {
      title: 'Announcements',
      description:
        'Ordinary tones use a polite status region; error and danger use an assertive alert.',
      props: ['tone', 'ariaLive'],
    },
    {
      title: 'Focus and controls',
      description:
        'Toasts do not steal focus; action and dismiss controls remain keyboard accessible.',
      props: ['action', 'dismissible', 'dismissLabel'],
    },
    {
      title: 'Reduced motion',
      description:
        'Entrance animation is removed under prefers-reduced-motion.',
    },
  ] as const;

  const nativeItems = [
    {
      title: 'Native announcement',
      description:
        'Messages use AccessibilityInfo announcements and native live-region semantics.',
      props: ['announcement', 'tone', 'accessibilityLabel'],
    },
    {
      title: 'Touch and dismissal',
      description:
        'Action and dismiss controls provide labelled 44-point touch targets and accessibility escape dismissal.',
      props: ['action', 'dismissible', 'dismissLabel'],
    },
    {
      title: 'Reduced motion',
      description:
        'Native entrance transitions become immediate when reduced motion is enabled.',
    },
  ] as const;

  return (
    <ComponentAccessibility
      items={platform === 'react' ? reactItems : nativeItems}
    />
  );
}
