// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

'use client';

import { Toast as ReactToast } from '@vellira-ui/react';
import { Toast as NativeToast } from '@vellira-ui/react-native';

import { ComponentExamples } from '../../shared/ComponentExamples';
import type { ComponentPlatform } from '../../types';

type ToastExamplesProps = {
  platform: ComponentPlatform;
};

export function ToastExamples({ platform }: ToastExamplesProps) {
  const reactExamples = [
    {
      title: 'Success',
      description: 'A polite confirmation that dismisses automatically.',
      preview: (
        <ReactToast
          title='Changes saved'
          description='Your preferences are up to date.'
          tone='success'
        />
      ),
      code: `import { Toast } from '@vellira-ui/react';

<Toast
  title='Changes saved'
  description='Your preferences are up to date.'
  tone='success'
/>`,
    },
    {
      title: 'Error',
      description:
        'An assertive application-level error with manual dismissal.',
      preview: (
        <ReactToast
          title='Upload failed'
          description='Check your connection and try again.'
          tone='error'
          duration={0}
        />
      ),
      code: `import { Toast } from '@vellira-ui/react';

<Toast
  title='Upload failed'
  description='Check your connection and try again.'
  tone='error'
  duration={0}
/>`,
    },
    {
      title: 'Action',
      description: 'A concise reversible action.',
      preview: (
        <ReactToast
          title='Message archived'
          action={{ label: 'Undo', onAction: () => undefined }}
          duration={0}
        />
      ),
      code: `import { Toast } from '@vellira-ui/react';

<Toast
  title='Message archived'
  action={{ label: 'Undo', onAction: () => undefined }}
  duration={0}
/>`,
    },
  ] as const;

  const nativeExamples = [
    {
      title: 'Success',
      description: 'A polite confirmation that dismisses automatically.',
      preview: (
        <NativeToast
          title='Changes saved'
          description='Your preferences are up to date.'
          tone='success'
        />
      ),
      code: `import { Toast } from '@vellira-ui/react-native';

<Toast
  title='Changes saved'
  description='Your preferences are up to date.'
  tone='success'
/>`,
    },
    {
      title: 'Error',
      description:
        'An assertive application-level error with manual dismissal.',
      preview: (
        <NativeToast
          title='Upload failed'
          description='Check your connection and try again.'
          tone='error'
          duration={0}
        />
      ),
      code: `import { Toast } from '@vellira-ui/react-native';

<Toast
  title='Upload failed'
  description='Check your connection and try again.'
  tone='error'
  duration={0}
/>`,
    },
    {
      title: 'Action',
      description: 'A concise reversible action.',
      preview: (
        <NativeToast
          title='Message archived'
          action={{ label: 'Undo', onAction: () => undefined }}
          duration={0}
        />
      ),
      code: `import { Toast } from '@vellira-ui/react-native';

<Toast
  title='Message archived'
  action={{ label: 'Undo', onAction: () => undefined }}
  duration={0}
/>`,
    },
  ] as const;

  return (
    <ComponentExamples
      items={platform === 'react' ? reactExamples : nativeExamples}
    />
  );
}
