// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

'use client';

import type { ReactNode } from 'react';

import { ComponentPlayground } from '../../shared/ComponentPlayground';
import { useComponentDemoState } from '../../shared/ComponentDemoStateProvider';
import { PlaygroundControlsFromSchema } from '../../shared/PlaygroundControls';

import { toastPlaygroundControls } from './toastPlaygroundSchema';

export type ToastPlaygroundValue = {
  open: boolean;
};

type ToastPlaygroundProps = {
  platform: 'react' | 'react-native';
  renderToast: (
    value: ToastPlaygroundValue,
    onChange: <K extends keyof ToastPlaygroundValue>(
      key: K,
      nextValue: ToastPlaygroundValue[K]
    ) => void
  ) => ReactNode;
};

export const initialToastPlaygroundValue: ToastPlaygroundValue = {
  open: false,
};

export function ToastPlayground({
  platform,
  renderToast,
}: ToastPlaygroundProps) {
  const [value, setValue] = useComponentDemoState<ToastPlaygroundValue>(
    initialToastPlaygroundValue
  );

  const update = (
    key: keyof ToastPlaygroundValue,
    nextValue: ToastPlaygroundValue[keyof ToastPlaygroundValue]
  ) => {
    setValue({
      ...value,
      [key]: nextValue,
    });
  };

  return (
    <ComponentPlayground
      previewWidth='full'
      controls={
        <PlaygroundControlsFromSchema
          platform={platform}
          value={value}
          controls={toastPlaygroundControls}
          onChange={update}
        />
      }
    >
      {renderToast(value, update)}
    </ComponentPlayground>
  );
}
