// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

'use client';

import type { ComponentPlatform } from '../../types';

import { ComponentCodeBlock } from '../../shared/ComponentCodeBlock';
import { useComponentDemoState } from '../../shared/ComponentDemoStateProvider';

import {
  initialToastPlaygroundValue,
  type ToastPlaygroundValue,
} from './ToastPlayground';

import styles from '../../shared/ComponentUsage.module.css';

type ToastUsageProps = {
  platform: ComponentPlatform;
};

function createToastCode(
  platform: ComponentPlatform,
  value: ToastPlaygroundValue
) {
  const packageName =
    platform === 'react' ? '@vellira-ui/react' : '@vellira-ui/react-native';

  const props: string[] =
    platform === 'react'
      ? [
          `title='Changes saved' description='Your preferences are up to date.' duration={0}`,
        ]
      : [
          `title='Changes saved' description='Your preferences are up to date.' duration={0}`,
        ];

  const children = platform === 'react' ? `` : ``;

  if (value.open) {
    props.push('open');
  }

  const propsText = props.length === 0 ? '' : `\n  ${props.join('\n  ')}\n`;

  if (!children) {
    return `import { Toast } from '${packageName}';
${platform === 'react' ? `` : ``}

<Toast${propsText}/>`;
  }

  return `import { Toast } from '${packageName}';
${platform === 'react' ? `` : ``}

<Toast${propsText}>
${children}
</Toast>`;
}

export function ToastUsage({ platform }: ToastUsageProps) {
  const [value] = useComponentDemoState<ToastPlaygroundValue>(
    initialToastPlaygroundValue
  );

  const code = createToastCode(platform, value);

  return (
    <section className={styles.root}>
      <div className={styles.header}>
        <h2 className={styles.title}>Usage</h2>

        <p className={styles.description}>
          Import the component and configure it with the same props used in the
          playground.
        </p>
      </div>

      <ComponentCodeBlock code={code} />
    </section>
  );
}
