// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

'use client';

import { Toast } from '@vellira-ui/react';

import styles from '../../shared/ComponentsCatalog/ComponentsCatalog.module.css';

export function ToastCatalogPreview() {
  return (
    <div className={styles.previewStack}>
      <Toast
        title='Changes saved'
        tone='success'
        duration={0}
        dismissible={false}
      />
    </div>
  );
}
