// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

import type { PlaygroundControl } from '../../shared/PlaygroundControls';

import type { ToastPlaygroundValue } from './ToastPlayground';

export const toastPlaygroundControls = [
  {
    type: 'toggle',
    key: 'open',
    label: 'Open',
    group: 'Options',
  },
] as const satisfies readonly PlaygroundControl<ToastPlaygroundValue>[];
