import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

import { afterEach, describe, expect, it, vi } from 'vitest';

import { formatGeneratedContent } from '../format-generated-files';
import { getCatalogPaths } from '../component-page/helpers/paths';
import {
  getComponentDocsContractVariable,
  getComponentDocsTargets,
  renderComponentDocsContract,
  resolvePlanCapabilities,
} from './docs';
import { createComponentGenerationPlan } from './plan';
import { checkGeneratedPlanContract } from './plan-contract';
import { checkComponentDocumentationContract } from './documentation-contract';
import { renderMetadataTemplate } from './templates';
import { generateComponentWebsitePage } from './website';
import {
  checkComponentWebsiteContract,
  getPlannedComponentWebsiteArtifacts,
} from './website-contract';

import type { ComponentGeneratorOptions } from './cli';
import type { ComponentGenerationPlan } from './plan';

vi.mock('node:child_process', () => ({
  spawnSync: vi.fn(),
}));

vi.mock('./documentation-contract', () => ({
  checkComponentDocumentationContract: vi.fn(async () => []),
}));

const roots: string[] = [];

function tempRoot() {
  const root = fs.mkdtempSync(
    path.join(os.tmpdir(), 'vellira-production-contract-parity-')
  );
  roots.push(root);
  return root;
}

function plan(
  root: string,
  overrides: Partial<ComponentGeneratorOptions> = {}
): ComponentGenerationPlan {
  return createComponentGenerationPlan({
    root,
    options: {
      componentName: 'ContractProbe',
      platform: 'both',
      layer: 'components',
      category: 'utility',
      profile: 'base',
      capabilities: [],
      parts: [],
      force: false,
      ...overrides,
    },
  });
}

async function writeCanonicalPlanArtifacts(plan: ComponentGenerationPlan) {
  const platforms = plan.targets.map((target) => target.packageName);
  const metadata = await formatGeneratedContent(
    plan.metadataFile,
    renderMetadataTemplate({
      componentName: plan.componentName,
      layer: plan.layer,
      category: plan.category,
      platforms,
      profile: plan.profile,
      capabilities: resolvePlanCapabilities(plan),
      typeOwnership: plan.typeOwnership,
      dependencies: plan.dependencies,
      icons: plan.icons,
      tokens: plan.tokens,
      assets: plan.assets,
      componentTokens: plan.componentTokens,
    })
  );

  fs.mkdirSync(path.dirname(plan.metadataFile), { recursive: true });
  fs.writeFileSync(plan.metadataFile, metadata);

  const metadataName = `${plan.componentName[0].toLowerCase()}${plan.componentName.slice(1)}Metadata`;
  fs.writeFileSync(
    plan.metadataBarrelFile,
    `import { ${metadataName} } from './${plan.componentName}.metadata';\n\nexport const componentMetadata = [\n  ${metadataName},\n] as const;\n`
  );

  const docsContract = await formatGeneratedContent(
    plan.docsContractFile,
    renderComponentDocsContract(plan)
  );
  fs.mkdirSync(path.dirname(plan.docsContractFile), { recursive: true });
  fs.writeFileSync(plan.docsContractFile, docsContract);

  const docsVariable = getComponentDocsContractVariable(plan.componentName);
  fs.writeFileSync(
    plan.docsContractRegistryFile,
    `import { ${docsVariable} } from './${plan.componentName}.docs';\n\nexport const componentDocsContracts = [${docsVariable}] as const;\n`
  );

  for (const target of getComponentDocsTargets(plan)) {
    fs.mkdirSync(path.dirname(target.docsFile), { recursive: true });
    fs.writeFileSync(
      target.docsFile,
      '<!-- Generated by scripts/generators/component-docs/generate-component-docs.ts -->\n'
    );
  }
}

function snapshotFiles(directory: string): Map<string, Buffer> {
  if (!fs.existsSync(directory)) {
    return new Map();
  }

  const files = new Map<string, Buffer>();

  for (const entry of fs.readdirSync(directory, { withFileTypes: true })) {
    const entryPath = path.join(directory, entry.name);

    if (entry.isDirectory()) {
      for (const [filePath, contents] of snapshotFiles(entryPath)) {
        files.set(filePath, contents);
      }
    } else if (entry.isFile()) {
      files.set(entryPath, fs.readFileSync(entryPath));
    }
  }

  return files;
}

function changedFiles(
  before: Map<string, Buffer>,
  after: Map<string, Buffer>
): { createdFiles: string[]; updatedFiles: string[] } {
  return {
    createdFiles: [...after.keys()]
      .filter((filePath) => !before.has(filePath))
      .sort(),
    updatedFiles: [...after.keys()]
      .filter((filePath) => {
        const previous = before.get(filePath);
        const current = after.get(filePath);

        return (
          previous !== undefined &&
          current !== undefined &&
          !previous.equals(current)
        );
      })
      .sort(),
  };
}

afterEach(() => {
  vi.clearAllMocks();

  for (const root of roots.splice(0)) {
    fs.rmSync(root, { recursive: true, force: true });
  }
});

describe('component production contract regression matrix', () => {
  it('keeps full shared dependencies and design-resource intent in one plan', () => {
    const result = plan('/repo', {
      profile: 'compound',
      parts: ['Root', 'Trigger', 'Content'],
      dependencies: {
        packages: ['@vellira-ui/core'],
        components: ['Tooltip'],
        platforms: {
          react: {
            packages: ['@vellira-ui/icons'],
          },
          'react-native': {
            packages: ['@vellira-ui/assets'],
          },
        },
      },
      icons: [{ name: 'ChevronDown', purpose: 'disclosure indicator' }],
      tokens: ['semantic.text.primary'],
      assets: [{ path: 'styles/probe.css', purpose: 'probe surface' }],
      componentTokens: 'disclosure',
    });

    expect(result.typeOwnership).toBe('shared');
    expect(result.dependencies.packages).toEqual([
      '@vellira-ui/core',
      '@vellira-ui/types',
    ]);
    expect(result.dependencies.components).toEqual(['Tooltip']);
    expect(result.dependencies.platforms).toEqual({
      react: {
        packages: ['@vellira-ui/icons'],
      },
      'react-native': {
        packages: ['@vellira-ui/assets'],
      },
    });
    expect(result.icons).toEqual([
      { name: 'ChevronDown', purpose: 'disclosure indicator' },
    ]);
    expect(result.tokens).toEqual(['semantic.text.primary']);
    expect(result.assets).toEqual([
      { path: 'styles/probe.css', purpose: 'probe surface' },
    ]);
    expect(result.componentTokens).toBe('disclosure');
  });

  it('does not invent core, shared types, or assets for a minimal base component', () => {
    const result = plan('/repo');

    expect(result.typeOwnership).toBe('platform');
    expect(result.dependencies).toEqual({});
    expect(result.assets).toEqual([]);
    expect(result.targets.map((target) => target.packageName)).toEqual([
      'react',
      'react-native',
    ]);
  });

  it.each([
    ['web', ['react']],
    ['native', ['react-native']],
  ] as const)(
    'preserves the selected %s-only renderer boundary',
    (platform, expectedTargets) => {
      const result = plan('/repo', { platform });

      expect(result.targets.map((target) => target.packageName)).toEqual(
        expectedTargets
      );
    }
  );

  it('keeps overlay platform dependencies intentionally divergent', () => {
    const result = plan('/repo', {
      profile: 'overlay',
      parts: ['Root', 'Trigger', 'Content'],
      dependencies: {
        platforms: {
          react: {
            packages: ['@vellira-ui/icons'],
          },
          'react-native': {
            components: ['PortalHost'],
          },
        },
      },
    });

    expect(result.typeOwnership).toBe('shared');
    expect(result.dependencies.packages).toEqual(['@vellira-ui/types']);
    expect(result.dependencies.platforms).toEqual({
      react: {
        packages: ['@vellira-ui/icons'],
      },
      'react-native': {
        components: ['PortalHost'],
      },
    });
  });

  it('plans website artifacts for each selected platform without false parity', () => {
    const both = getPlannedComponentWebsiteArtifacts(plan('/repo'));
    const web = getPlannedComponentWebsiteArtifacts(
      plan('/repo', { platform: 'web' })
    );
    const native = getPlannedComponentWebsiteArtifacts(
      plan('/repo', { platform: 'native' })
    );

    expect(both.createdFiles).toEqual(
      expect.arrayContaining([
        '/repo/apps/website/src/component-catalog/components/ContractProbe/ContractProbeDemo.tsx',
        '/repo/apps/website/src/component-catalog/components/ContractProbe/NativeContractProbeDemo.tsx',
        '/repo/apps/website/src/component-catalog/components/ContractProbe/ContractProbeCatalogPreview.tsx',
      ])
    );
    expect(web.createdFiles).toContain(
      '/repo/apps/website/src/component-catalog/components/ContractProbe/ContractProbeDemo.tsx'
    );
    expect(web.createdFiles).not.toContain(
      '/repo/apps/website/src/component-catalog/components/ContractProbe/NativeContractProbeDemo.tsx'
    );
    expect(native.createdFiles).toContain(
      '/repo/apps/website/src/component-catalog/components/ContractProbe/NativeContractProbeDemo.tsx'
    );
    expect(native.createdFiles).not.toContain(
      '/repo/apps/website/src/component-catalog/components/ContractProbe/ContractProbeDemo.tsx'
    );

    expect(both.updatedFiles).toEqual([
      '/repo/apps/website/src/component-catalog/registry/componentPages.ts',
      '/repo/apps/website/src/component-catalog/registry/componentPresentation.ts',
      '/repo/apps/website/src/component-catalog/registry/generatedCatalogPreviews.ts',
    ]);

    expect(both.updatedFiles).not.toContain(
      '/repo/apps/website/src/component-catalog/registry/relatedComponents.ts'
    );
  });

  it('keeps fresh cross-platform website artifacts in planned, runtime, and filesystem parity', async () => {
    const root = tempRoot();
    const generationPlan = plan(root);
    const catalogPaths = getCatalogPaths({
      root,
      componentName: generationPlan.componentName,
    });

    await writeCanonicalPlanArtifacts(generationPlan);
    fs.mkdirSync(path.dirname(catalogPaths.catalogRegistryFile), {
      recursive: true,
    });

    for (const registryFile of [
      catalogPaths.catalogRegistryFile,
      catalogPaths.componentPresentationRegistryFile,
      catalogPaths.generatedCatalogPreviewsFile,
    ]) {
      fs.writeFileSync(registryFile, `before ${path.basename(registryFile)}\n`);
    }

    const planned = getPlannedComponentWebsiteArtifacts(generationPlan);
    const websiteRoot = path.join(root, 'apps', 'website');
    const before = snapshotFiles(websiteRoot);

    vi.mocked(spawnSync).mockImplementation(() => {
      for (const filePath of [
        ...planned.createdFiles,
        ...planned.updatedFiles,
      ]) {
        fs.mkdirSync(path.dirname(filePath), { recursive: true });
        fs.writeFileSync(filePath, `after ${path.basename(filePath)}\n`);
      }

      return {
        pid: 1,
        output: [],
        stdout: '',
        stderr: '',
        status: 0,
        signal: null,
      };
    });

    const runtime = await generateComponentWebsitePage({
      root,
      componentName: generationPlan.componentName,
      profile: generationPlan.profile,
      category: generationPlan.category,
    });
    const actual = changedFiles(before, snapshotFiles(websiteRoot));

    expect({
      createdFiles: runtime.createdFiles,
      updatedFiles: runtime.updatedFiles,
    }).toEqual(planned);
    expect(actual).toEqual(planned);
    expect(runtime.createdFiles).toContain(
      path.join(
        catalogPaths.componentCatalogDir,
        `${generationPlan.componentName}CatalogPreview.tsx`
      )
    );
    expect(runtime.updatedFiles).toContain(
      catalogPaths.generatedCatalogPreviewsFile
    );
  });

  it('detects metadata drift for every production intent family', async () => {
    const root = tempRoot();
    const result = plan(root, {
      profile: 'compound',
      parts: ['Root', 'Trigger', 'Content'],
      dependencies: {
        packages: ['@vellira-ui/core'],
      },
      icons: [{ name: 'ChevronDown', purpose: 'disclosure indicator' }],
      tokens: ['semantic.text.primary'],
      assets: [{ path: 'styles/probe.css', purpose: 'probe surface' }],
      componentTokens: 'disclosure',
    });

    await writeCanonicalPlanArtifacts(result);
    expect(await checkGeneratedPlanContract(result)).toEqual([]);

    const canonical = fs.readFileSync(result.metadataFile, 'utf8');
    const drifts: Array<[string, string]> = [
      ["'@vellira-ui/core'", "'@vellira-ui/icons'"],
      ["name: 'ChevronDown'", "name: 'Close'"],
      ["'semantic.text.primary'", "'semantic.text.secondary'"],
      ["path: 'styles/probe.css'", "path: 'styles/drift.css'"],
      ["componentTokens: 'disclosure'", "componentTokens: 'standard'"],
    ];

    for (const [from, to] of drifts) {
      expect(canonical).toContain(from);
      fs.writeFileSync(result.metadataFile, canonical.replace(from, to));
      expect(await checkGeneratedPlanContract(result)).toContain(
        result.metadataFile
      );
    }
  });

  it('propagates canonical generated docs and API drift into generator check evidence', async () => {
    const root = tempRoot();
    const result = plan(root);

    await writeCanonicalPlanArtifacts(result);
    const apiFile = path.join(root, 'packages/react/API.md');
    vi.mocked(checkComponentDocumentationContract).mockResolvedValueOnce([
      apiFile,
    ]);

    expect(await checkGeneratedPlanContract(result)).toContain(apiFile);
  });

  it('detects docs-contract drift independently of authored docs regions', async () => {
    const root = tempRoot();
    const result = plan(root);

    await writeCanonicalPlanArtifacts(result);
    const canonical = fs.readFileSync(result.docsContractFile, 'utf8');
    const summary =
      'Use ContractProbe in React utility interfaces when you need the canonical Vellira behavior and styling for this component.';
    expect(canonical).toContain(summary);
    fs.writeFileSync(
      result.docsContractFile,
      canonical.replace(summary, 'Drifted ContractProbe summary')
    );

    expect(await checkGeneratedPlanContract(result)).toContain(
      result.docsContractFile
    );
  });

  it('maps website JSON stale evidence back to repository artifacts', () => {
    const root = '/repo';
    const result = plan(root);

    vi.mocked(spawnSync).mockReturnValue({
      status: 1,
      signal: null,
      output: [],
      pid: 1,
      stdout: JSON.stringify({
        schemaVersion: '1',
        componentName: 'ContractProbe',
        status: 'stale',
        staleFiles: [
          'apps/website/src/component-catalog/components/ContractProbe/contract-probeApi.ts',
        ],
      }),
      stderr: '',
    } as unknown as ReturnType<typeof spawnSync>);

    expect(checkComponentWebsiteContract(result)).toEqual([
      '/repo/apps/website/src/component-catalog/components/ContractProbe/contract-probeApi.ts',
    ]);
  });
});
