// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

import type {
  ComponentApiProp,
  ComponentApiSection,
} from '../../shared/ComponentApi';

const reactInputApiSections: readonly ComponentApiSection[] = [
  {
    name: 'Input',
    props: [
      {
        name: 'type',
        type: 'import("react").HTMLInputTypeAttribute',
        defaultValue: "'text'",
        description:
          'Native input type. Search automatically adds a start search icon.',
      },
      {
        name: 'value',
        type: 'string | number | readonly string[]',
        description: 'Controlled value.',
      },
      {
        name: 'defaultValue',
        type: 'string | number | readonly string[]',
        description: 'Initial uncontrolled value.',
      },
      {
        name: 'onValueChange',
        type: '((value: string) => void)',
        description: 'Called with the next string value.',
      },
      {
        name: 'variant',
        type: "'outline' | 'filled' | 'soft' | 'bare'",
        defaultValue: "'outline'",
        description:
          'Visual variant. `bare` preserves Input behavior while composition owns field chrome.',
      },
      {
        name: 'id',
        type: 'string',
        description:
          'Control id. Inherits the generated FormField id when omitted.',
      },
      {
        name: 'name',
        type: 'string',
        description: 'Native input name.',
      },
      {
        name: 'startIcon',
        type: 'ReactNode',
        description: 'Icon rendered at the start of the control.',
      },
      {
        name: 'endIcon',
        type: 'ReactNode',
        description:
          'Icon rendered in the right slot when no higher-priority action is active.',
      },
      {
        name: 'startAddon',
        type: 'ReactNode',
        description: 'Segmented addon rendered before the input.',
      },
      {
        name: 'endAddon',
        type: 'ReactNode',
        description: 'Segmented addon rendered after the input.',
      },
      {
        name: 'prefix',
        type: 'ReactNode',
        description: 'Inline prefix rendered inside the input chrome.',
      },
      {
        name: 'suffix',
        type: 'ReactNode',
        description: 'Inline suffix rendered inside the input chrome.',
      },
      {
        name: 'clearIcon',
        type: 'ReactNode',
        description:
          'Custom clear action content. Defaults to the canonical Vellira Close icon.',
      },
      {
        name: 'mask',
        type: 'InputMask',
        description: 'Input mask. String masks use # as a digit placeholder.',
      },
      {
        name: 'format',
        type: 'InputFormatter',
        description:
          'Formats the displayed value without changing the controlled value.',
      },
      {
        name: 'parse',
        type: 'InputParser',
        description:
          'Parses a formatted display value before mask/onValueChange.',
      },
      {
        name: 'startIconTone',
        type: "'default' | 'primary' | 'secondary' | 'success' | 'danger' | 'muted' | 'inverse'",
        defaultValue: "'default'",
        description: 'Tone for startIcon.',
      },
      {
        name: 'endIconTone',
        type: "'default' | 'primary' | 'secondary' | 'success' | 'danger' | 'muted' | 'inverse'",
        defaultValue: "'default'",
        description: 'Tone for endIcon.',
      },
      {
        name: 'clearIconTone',
        type: "'default' | 'primary' | 'secondary' | 'success' | 'danger' | 'muted' | 'inverse'",
        defaultValue: "'danger'",
        description: 'Tone for clearIcon.',
      },
      {
        name: 'wrapperClassName',
        type: 'string',
        description:
          'Class name applied to the outer FormField wrapper in shorthand mode.',
      },
      {
        name: 'className',
        type: 'string',
        description: 'Class name applied to the native input element.',
      },
      {
        name: 'autoComplete',
        type: 'string',
        description:
          'Native autocomplete value. When omitted, sensible values are derived from type.',
      },
      {
        name: 'label',
        type: 'string',
        description: 'Visible field label.',
      },
      {
        name: 'description',
        type: 'string',
        description:
          'Supporting text rendered with the field and linked to the control.',
      },
      {
        name: 'placeholder',
        type: 'string',
        description: 'Placeholder shown when the value is empty.',
      },
      {
        name: 'size',
        type: "'sm' | 'md' | 'lg'",
        defaultValue: "'md'",
        description:
          'Field size. Inherits from FormField when omitted by compatible controls.',
      },
      {
        name: 'color',
        type: "'primary' | 'success' | 'danger' | 'neutral' | 'warning'",
        defaultValue: "'primary'",
        description: 'Semantic color palette for the control.',
      },
      {
        name: 'disabled',
        type: 'boolean',
        defaultValue: 'false',
        description:
          'Disables interaction. Also inherited from FormField by compatible controls.',
      },
      {
        name: 'readOnly',
        type: 'boolean',
        defaultValue: 'false',
        description:
          'Makes the control non-editable while preserving focus and value semantics.',
      },
      {
        name: 'required',
        type: 'boolean',
        defaultValue: 'false',
        description:
          'Marks the field as required. Also inherited from FormField.',
      },
      {
        name: 'invalid',
        type: 'boolean',
        defaultValue: 'false',
        description:
          'Shows invalid styling without requiring error text. Also inherited from FormField.',
      },
      {
        name: 'loading',
        type: 'boolean',
        defaultValue: 'false',
        description:
          'Shows a spinner in the right slot and makes the field read-only.',
      },
      {
        name: 'clearable',
        type: 'boolean',
        defaultValue: 'false',
        description: 'Shows a clear action when the field has a value.',
      },
      {
        name: 'onClear',
        type: '(() => void)',
        description: 'Called when the clear action is activated.',
      },
      {
        name: 'revealPassword',
        type: 'boolean',
        defaultValue: 'false',
        description: 'Shows a password visibility toggle for password inputs.',
      },
      {
        name: 'showCounter',
        type: 'boolean',
        defaultValue: 'false',
        description:
          'Shows the current character count when maxLength is provided.',
      },
      {
        name: 'error',
        type: 'string',
        description: 'Error message. Also implies invalid state.',
      },
    ],
  },
];

const nativeInputApiSections: readonly ComponentApiSection[] = [
  {
    name: 'Input',
    props: [
      {
        name: 'value',
        type: 'string',
        description: 'Controlled value.',
      },
      {
        name: 'defaultValue',
        type: 'string',
        description: 'Initial uncontrolled value.',
      },
      {
        name: 'onValueChange',
        type: '((value: string) => void)',
        description: 'Called with the next string value.',
      },
      {
        name: 'type',
        type: "'number' | 'text' | 'email' | 'password' | 'tel' | 'url' | 'search'",
        defaultValue: "'text'",
        description:
          'Semantic input type used to derive keyboard and secure entry behavior.',
      },
      {
        name: 'startIcon',
        type: 'InputIconElement',
        description: 'Icon rendered at the start of the control.',
      },
      {
        name: 'endIcon',
        type: 'InputIconElement',
        description:
          'Icon rendered at the end of the control when no action is active.',
      },
      {
        name: 'clearIcon',
        type: 'InputIconElement',
        description:
          'Custom clear action icon. Defaults to the canonical Vellira Close icon.',
      },
      {
        name: 'startIconTone',
        type: "'default' | 'primary' | 'secondary' | 'success' | 'danger' | 'muted' | 'inverse'",
        defaultValue: "'default'",
        description: 'Tone for startIcon.',
      },
      {
        name: 'endIconTone',
        type: "'default' | 'primary' | 'secondary' | 'success' | 'danger' | 'muted' | 'inverse'",
        defaultValue: "'default'",
        description: 'Tone for endIcon.',
      },
      {
        name: 'clearIconTone',
        type: "'default' | 'primary' | 'secondary' | 'success' | 'danger' | 'muted' | 'inverse'",
        defaultValue: "'danger'",
        description: 'Tone for clearIcon.',
      },
      {
        name: 'iconSize',
        type: 'number',
        description: 'Icon size in pixels.',
      },
      {
        name: 'containerStyle',
        type: 'StyleProp<ViewStyle>',
        description: 'Style for the outer container.',
      },
      {
        name: 'inputStyle',
        type: 'StyleProp<TextStyle>',
        description: 'Style for the TextInput.',
      },
      {
        name: 'testID',
        type: 'string',
        description: 'Test identifier.',
      },
      {
        name: 'keyboardType',
        type: "'url' | 'default' | 'number-pad' | 'decimal-pad' | 'numeric' | 'email-address' | 'phone-pad' | 'visible-password' | 'ascii-capable' | 'numbers-and-punctuation' | 'name-phone-pad' | 'twitter' | 'web-search'",
        description: 'Native keyboard type override.',
      },
      {
        name: 'secureTextEntry',
        type: 'boolean',
        description: 'Native secure text entry override.',
      },
      {
        name: 'label',
        type: 'string',
        description: 'Visible field label.',
      },
      {
        name: 'description',
        type: 'string',
        description:
          'Supporting text rendered with the field and linked to the control.',
      },
      {
        name: 'placeholder',
        type: 'string',
        description: 'Placeholder shown when the value is empty.',
      },
      {
        name: 'size',
        type: "'sm' | 'md' | 'lg'",
        defaultValue: "'md'",
        description:
          'Field size. Inherits from FormField when omitted by compatible controls.',
      },
      {
        name: 'color',
        type: "'primary' | 'success' | 'danger' | 'neutral' | 'warning'",
        defaultValue: "'primary'",
        description: 'Semantic color palette for the control.',
      },
      {
        name: 'variant',
        type: "'outline' | 'filled' | 'soft'",
        defaultValue: "'outline'",
        description: 'Visual variant for the control chrome.',
      },
      {
        name: 'disabled',
        type: 'boolean',
        defaultValue: 'false',
        description:
          'Disables interaction. Also inherited from FormField by compatible controls.',
      },
      {
        name: 'readOnly',
        type: 'boolean',
        defaultValue: 'false',
        description:
          'Makes the control non-editable while preserving focus and value semantics.',
      },
      {
        name: 'required',
        type: 'boolean',
        defaultValue: 'false',
        description:
          'Marks the field as required. Also inherited from FormField.',
      },
      {
        name: 'invalid',
        type: 'boolean',
        defaultValue: 'false',
        description:
          'Shows invalid styling without requiring error text. Also inherited from FormField.',
      },
      {
        name: 'loading',
        type: 'boolean',
        defaultValue: 'false',
        description:
          'Shows a spinner in the right slot and makes the field read-only.',
      },
      {
        name: 'clearable',
        type: 'boolean',
        defaultValue: 'false',
        description: 'Shows a clear action when the field has a value.',
      },
      {
        name: 'onClear',
        type: '(() => void)',
        description: 'Called when the clear action is activated.',
      },
      {
        name: 'revealPassword',
        type: 'boolean',
        defaultValue: 'false',
        description: 'Shows a password visibility toggle for password inputs.',
      },
      {
        name: 'showCounter',
        type: 'boolean',
        defaultValue: 'false',
        description:
          'Shows the current character count when maxLength is provided.',
      },
      {
        name: 'mask',
        type: 'InputMask',
        description: 'Input mask. String masks use # as a digit placeholder.',
      },
      {
        name: 'format',
        type: 'InputFormatter',
        description:
          'Formats the displayed value without changing the controlled value.',
      },
      {
        name: 'parse',
        type: 'InputParser',
        description:
          'Parses a formatted display value before mask/onValueChange.',
      },
      {
        name: 'error',
        type: 'string',
        description: 'Error message. Also implies invalid state.',
      },
    ],
  },
];

const inheritedReactInputApi: readonly ComponentApiProp[] = [
  {
    name: 'form',
    type: 'string',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'slot',
    type: 'string',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'style',
    type: 'CSSProperties',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'title',
    type: 'string',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'pattern',
    type: 'string',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'key',
    type: 'Key | null',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'accept',
    type: 'string',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'alt',
    type: 'string',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'capture',
    type: 'boolean | "user" | "environment"',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'checked',
    type: 'boolean',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'formAction',
    type: 'string | ((formData: FormData) => void | Promise<void>)',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'formEncType',
    type: 'string',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'formMethod',
    type: 'string',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'formNoValidate',
    type: 'boolean',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'formTarget',
    type: 'string',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'height',
    type: 'string | number',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'list',
    type: 'string',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'max',
    type: 'string | number',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'maxLength',
    type: 'number',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'min',
    type: 'string | number',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'minLength',
    type: 'number',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'multiple',
    type: 'boolean',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'src',
    type: 'string',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'step',
    type: 'string | number',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'width',
    type: 'string | number',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'defaultChecked',
    type: 'boolean',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'suppressContentEditableWarning',
    type: 'boolean',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'suppressHydrationWarning',
    type: 'boolean',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'accessKey',
    type: 'string',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'autoCapitalize',
    type: '(string & {}) | "off" | "none" | "on" | "sentences" | "words" | "characters"',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'autoFocus',
    type: 'boolean',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'contentEditable',
    type: 'Booleanish | "inherit" | "plaintext-only"',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'contextMenu',
    type: 'string',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'dir',
    type: 'string',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'draggable',
    type: 'Booleanish',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'enterKeyHint',
    type: "'search' | 'enter' | 'done' | 'go' | 'next' | 'previous' | 'send'",
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'hidden',
    type: 'boolean',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'lang',
    type: 'string',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'nonce',
    type: 'string',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'spellCheck',
    type: 'Booleanish',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'tabIndex',
    type: 'number',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'translate',
    type: "'yes' | 'no'",
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'radioGroup',
    type: 'string',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'role',
    type: 'AriaRole',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'about',
    type: 'string',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'content',
    type: 'string',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'datatype',
    type: 'string',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'inlist',
    type: 'any',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'property',
    type: 'string',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'rel',
    type: 'string',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'resource',
    type: 'string',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'rev',
    type: 'string',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'typeof',
    type: 'string',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'vocab',
    type: 'string',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'autoCorrect',
    type: 'string',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'autoSave',
    type: 'string',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'itemProp',
    type: 'string',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'itemScope',
    type: 'boolean',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'itemType',
    type: 'string',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'itemID',
    type: 'string',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'itemRef',
    type: 'string',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'results',
    type: 'number',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'security',
    type: 'string',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'unselectable',
    type: "'off' | 'on'",
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'popover',
    type: "'' | 'auto' | 'manual' | 'hint'",
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'popoverTargetAction',
    type: "'toggle' | 'show' | 'hide'",
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'popoverTarget',
    type: 'string',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'inert',
    type: 'boolean',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'inputMode',
    type: "'search' | 'text' | 'email' | 'tel' | 'url' | 'none' | 'numeric' | 'decimal'",
    description:
      'Hints at the type of data that might be entered by the user while editing the element or its contents',
  },
  {
    name: 'is',
    type: 'string',
    description:
      'Specify that a standard HTML element should behave like a defined custom built-in element',
  },
  {
    name: 'exportparts',
    type: 'string',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'part',
    type: 'string',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'aria-activedescendant',
    type: 'string',
    description:
      'Identifies the currently active element when DOM focus is on a composite widget, textbox, group, or application.',
  },
  {
    name: 'aria-atomic',
    type: 'Booleanish',
    description:
      'Indicates whether assistive technologies will present all, or only parts of, the changed region based on the change notifications defined by the aria-relevant attribute.',
  },
  {
    name: 'aria-autocomplete',
    type: "'list' | 'none' | 'inline' | 'both'",
    description:
      "Indicates whether inputting text could trigger display of one or more predictions of the user's intended value for an input and specifies how predictions would be\npresented if they are made.",
  },
  {
    name: 'aria-braillelabel',
    type: 'string',
    description:
      'Defines a string value that labels the current element, which is intended to be converted into Braille.',
  },
  {
    name: 'aria-brailleroledescription',
    type: 'string',
    description:
      'Defines a human-readable, author-localized abbreviated description for the role of an element, which is intended to be converted into Braille.',
  },
  {
    name: 'aria-busy',
    type: 'Booleanish',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'aria-checked',
    type: 'boolean | "true" | "false" | "mixed"',
    description:
      'Indicates the current "checked" state of checkboxes, radio buttons, and other widgets.',
  },
  {
    name: 'aria-colcount',
    type: 'number',
    description:
      'Defines the total number of columns in a table, grid, or treegrid.',
  },
  {
    name: 'aria-colindex',
    type: 'number',
    description:
      "Defines an element's column index or position with respect to the total number of columns within a table, grid, or treegrid.",
  },
  {
    name: 'aria-colindextext',
    type: 'string',
    description: 'Defines a human readable text alternative of aria-colindex.',
  },
  {
    name: 'aria-colspan',
    type: 'number',
    description:
      'Defines the number of columns spanned by a cell or gridcell within a table, grid, or treegrid.',
  },
  {
    name: 'aria-controls',
    type: 'string',
    description:
      'Identifies the element (or elements) whose contents or presence are controlled by the current element.',
  },
  {
    name: 'aria-current',
    type: 'boolean | "time" | "step" | "date" | "true" | "false" | "page" | "location"',
    description:
      'Indicates the element that represents the current item within a container or set of related elements.',
  },
  {
    name: 'aria-describedby',
    type: 'string',
    description:
      'Identifies the element (or elements) that describes the object.',
  },
  {
    name: 'aria-description',
    type: 'string',
    description:
      'Defines a string value that describes or annotates the current element.',
  },
  {
    name: 'aria-details',
    type: 'string',
    description:
      'Identifies the element that provides a detailed, extended description for the object.',
  },
  {
    name: 'aria-disabled',
    type: 'Booleanish',
    description:
      'Indicates that the element is perceivable but disabled, so it is not editable or otherwise operable.',
  },
  {
    name: 'aria-dropeffect',
    type: "'link' | 'none' | 'copy' | 'execute' | 'move' | 'popup'",
    description:
      'Indicates what functions can be performed when a dragged object is released on the drop target.',
  },
  {
    name: 'aria-errormessage',
    type: 'string',
    description:
      'Identifies the element that provides an error message for the object.',
  },
  {
    name: 'aria-expanded',
    type: 'Booleanish',
    description:
      'Indicates whether the element, or another grouping element it controls, is currently expanded or collapsed.',
  },
  {
    name: 'aria-flowto',
    type: 'string',
    description:
      "Identifies the next element (or elements) in an alternate reading order of content which, at the user's discretion,\nallows assistive technology to override the general default of reading in document source order.",
  },
  {
    name: 'aria-grabbed',
    type: 'Booleanish',
    description:
      'Indicates an element\'s "grabbed" state in a drag-and-drop operation.',
  },
  {
    name: 'aria-haspopup',
    type: 'boolean | "dialog" | "menu" | "true" | "false" | "grid" | "listbox" | "tree"',
    description:
      'Indicates the availability and type of interactive popup element, such as menu or dialog, that can be triggered by an element.',
  },
  {
    name: 'aria-hidden',
    type: 'Booleanish',
    description:
      'Indicates whether the element is exposed to an accessibility API.',
  },
  {
    name: 'aria-invalid',
    type: 'boolean | "true" | "false" | "grammar" | "spelling"',
    description:
      'Indicates the entered value does not conform to the format expected by the application.',
  },
  {
    name: 'aria-keyshortcuts',
    type: 'string',
    description:
      'Indicates keyboard shortcuts that an author has implemented to activate or give focus to an element.',
  },
  {
    name: 'aria-label',
    type: 'string',
    description: 'Defines a string value that labels the current element.',
  },
  {
    name: 'aria-labelledby',
    type: 'string',
    description:
      'Identifies the element (or elements) that labels the current element.',
  },
  {
    name: 'aria-level',
    type: 'number',
    description:
      'Defines the hierarchical level of an element within a structure.',
  },
  {
    name: 'aria-live',
    type: "'off' | 'assertive' | 'polite'",
    description:
      'Indicates that an element will be updated, and describes the types of updates the user agents, assistive technologies, and user can expect from the live region.',
  },
  {
    name: 'aria-modal',
    type: 'Booleanish',
    description: 'Indicates whether an element is modal when displayed.',
  },
  {
    name: 'aria-multiline',
    type: 'Booleanish',
    description:
      'Indicates whether a text box accepts multiple lines of input or only a single line.',
  },
  {
    name: 'aria-multiselectable',
    type: 'Booleanish',
    description:
      'Indicates that the user may select more than one item from the current selectable descendants.',
  },
  {
    name: 'aria-orientation',
    type: "'horizontal' | 'vertical'",
    description:
      "Indicates whether the element's orientation is horizontal, vertical, or unknown/ambiguous.",
  },
  {
    name: 'aria-owns',
    type: 'string',
    description:
      'Identifies an element (or elements) in order to define a visual, functional, or contextual parent/child relationship\nbetween DOM elements where the DOM hierarchy cannot be used to represent the relationship.',
  },
  {
    name: 'aria-placeholder',
    type: 'string',
    description:
      'Defines a short hint (a word or short phrase) intended to aid the user with data entry when the control has no value.\nA hint could be a sample value or a brief description of the expected format.',
  },
  {
    name: 'aria-posinset',
    type: 'number',
    description:
      "Defines an element's number or position in the current set of listitems or treeitems. Not required if all elements in the set are present in the DOM.",
  },
  {
    name: 'aria-pressed',
    type: 'boolean | "true" | "false" | "mixed"',
    description: 'Indicates the current "pressed" state of toggle buttons.',
  },
  {
    name: 'aria-readonly',
    type: 'Booleanish',
    description:
      'Indicates that the element is not editable, but is otherwise operable.',
  },
  {
    name: 'aria-relevant',
    type: "'text' | 'additions' | 'additions removals' | 'additions text' | 'all' | 'removals' | 'removals additions' | 'removals text' | 'text additions' | 'text removals'",
    description:
      'Indicates what notifications the user agent will trigger when the accessibility tree within a live region is modified.',
  },
  {
    name: 'aria-required',
    type: 'Booleanish',
    description:
      'Indicates that user input is required on the element before a form may be submitted.',
  },
  {
    name: 'aria-roledescription',
    type: 'string',
    description:
      'Defines a human-readable, author-localized description for the role of an element.',
  },
  {
    name: 'aria-rowcount',
    type: 'number',
    description:
      'Defines the total number of rows in a table, grid, or treegrid.',
  },
  {
    name: 'aria-rowindex',
    type: 'number',
    description:
      "Defines an element's row index or position with respect to the total number of rows within a table, grid, or treegrid.",
  },
  {
    name: 'aria-rowindextext',
    type: 'string',
    description: 'Defines a human readable text alternative of aria-rowindex.',
  },
  {
    name: 'aria-rowspan',
    type: 'number',
    description:
      'Defines the number of rows spanned by a cell or gridcell within a table, grid, or treegrid.',
  },
  {
    name: 'aria-selected',
    type: 'Booleanish',
    description: 'Indicates the current "selected" state of various widgets.',
  },
  {
    name: 'aria-setsize',
    type: 'number',
    description:
      'Defines the number of items in the current set of listitems or treeitems. Not required if all elements in the set are present in the DOM.',
  },
  {
    name: 'aria-sort',
    type: "'none' | 'ascending' | 'descending' | 'other'",
    description:
      'Indicates if items in a table or grid are sorted in ascending or descending order.',
  },
  {
    name: 'aria-valuemax',
    type: 'number',
    description: 'Defines the maximum allowed value for a range widget.',
  },
  {
    name: 'aria-valuemin',
    type: 'number',
    description: 'Defines the minimum allowed value for a range widget.',
  },
  {
    name: 'aria-valuenow',
    type: 'number',
    description: 'Defines the current value for a range widget.',
  },
  {
    name: 'aria-valuetext',
    type: 'string',
    description:
      'Defines the human readable text alternative of aria-valuenow for a range widget.',
  },
  {
    name: 'children',
    type: 'ReactNode',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'dangerouslySetInnerHTML',
    type: '{ __html: string | TrustedHTML; }',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onCopy',
    type: 'ClipboardEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onCopyCapture',
    type: 'ClipboardEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onCut',
    type: 'ClipboardEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onCutCapture',
    type: 'ClipboardEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onPaste',
    type: 'ClipboardEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onPasteCapture',
    type: 'ClipboardEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onCompositionEnd',
    type: 'CompositionEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onCompositionEndCapture',
    type: 'CompositionEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onCompositionStart',
    type: 'CompositionEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onCompositionStartCapture',
    type: 'CompositionEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onCompositionUpdate',
    type: 'CompositionEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onCompositionUpdateCapture',
    type: 'CompositionEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onFocus',
    type: 'FocusEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onFocusCapture',
    type: 'FocusEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onBlur',
    type: 'FocusEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onBlurCapture',
    type: 'FocusEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onChangeCapture',
    type: 'ChangeEventHandler<HTMLInputElement, Element>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onBeforeInput',
    type: 'InputEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onBeforeInputCapture',
    type: 'InputEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onInput',
    type: 'InputEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onInputCapture',
    type: 'InputEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onReset',
    type: 'ReactEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onResetCapture',
    type: 'ReactEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onSubmit',
    type: 'SubmitEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onSubmitCapture',
    type: 'SubmitEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onInvalid',
    type: 'ReactEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onInvalidCapture',
    type: 'ReactEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onLoad',
    type: 'ReactEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onLoadCapture',
    type: 'ReactEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onError',
    type: 'ReactEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onErrorCapture',
    type: 'ReactEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onKeyDown',
    type: 'KeyboardEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onKeyDownCapture',
    type: 'KeyboardEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onKeyPress',
    type: 'KeyboardEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onKeyPressCapture',
    type: 'KeyboardEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onKeyUp',
    type: 'KeyboardEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onKeyUpCapture',
    type: 'KeyboardEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onAbort',
    type: 'ReactEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onAbortCapture',
    type: 'ReactEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onCanPlay',
    type: 'ReactEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onCanPlayCapture',
    type: 'ReactEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onCanPlayThrough',
    type: 'ReactEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onCanPlayThroughCapture',
    type: 'ReactEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onDurationChange',
    type: 'ReactEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onDurationChangeCapture',
    type: 'ReactEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onEmptied',
    type: 'ReactEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onEmptiedCapture',
    type: 'ReactEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onEncrypted',
    type: 'ReactEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onEncryptedCapture',
    type: 'ReactEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onEnded',
    type: 'ReactEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onEndedCapture',
    type: 'ReactEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onLoadedData',
    type: 'ReactEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onLoadedDataCapture',
    type: 'ReactEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onLoadedMetadata',
    type: 'ReactEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onLoadedMetadataCapture',
    type: 'ReactEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onLoadStart',
    type: 'ReactEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onLoadStartCapture',
    type: 'ReactEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onPause',
    type: 'ReactEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onPauseCapture',
    type: 'ReactEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onPlay',
    type: 'ReactEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onPlayCapture',
    type: 'ReactEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onPlaying',
    type: 'ReactEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onPlayingCapture',
    type: 'ReactEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onProgress',
    type: 'ReactEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onProgressCapture',
    type: 'ReactEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onRateChange',
    type: 'ReactEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onRateChangeCapture',
    type: 'ReactEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onSeeked',
    type: 'ReactEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onSeekedCapture',
    type: 'ReactEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onSeeking',
    type: 'ReactEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onSeekingCapture',
    type: 'ReactEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onStalled',
    type: 'ReactEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onStalledCapture',
    type: 'ReactEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onSuspend',
    type: 'ReactEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onSuspendCapture',
    type: 'ReactEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onTimeUpdate',
    type: 'ReactEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onTimeUpdateCapture',
    type: 'ReactEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onVolumeChange',
    type: 'ReactEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onVolumeChangeCapture',
    type: 'ReactEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onWaiting',
    type: 'ReactEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onWaitingCapture',
    type: 'ReactEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onAuxClick',
    type: 'MouseEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onAuxClickCapture',
    type: 'MouseEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onClick',
    type: 'MouseEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onClickCapture',
    type: 'MouseEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onContextMenu',
    type: 'MouseEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onContextMenuCapture',
    type: 'MouseEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onDoubleClick',
    type: 'MouseEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onDoubleClickCapture',
    type: 'MouseEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onDrag',
    type: 'DragEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onDragCapture',
    type: 'DragEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onDragEnd',
    type: 'DragEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onDragEndCapture',
    type: 'DragEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onDragEnter',
    type: 'DragEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onDragEnterCapture',
    type: 'DragEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onDragExit',
    type: 'DragEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onDragExitCapture',
    type: 'DragEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onDragLeave',
    type: 'DragEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onDragLeaveCapture',
    type: 'DragEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onDragOver',
    type: 'DragEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onDragOverCapture',
    type: 'DragEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onDragStart',
    type: 'DragEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onDragStartCapture',
    type: 'DragEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onDrop',
    type: 'DragEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onDropCapture',
    type: 'DragEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onMouseDown',
    type: 'MouseEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onMouseDownCapture',
    type: 'MouseEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onMouseEnter',
    type: 'MouseEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onMouseLeave',
    type: 'MouseEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onMouseMove',
    type: 'MouseEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onMouseMoveCapture',
    type: 'MouseEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onMouseOut',
    type: 'MouseEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onMouseOutCapture',
    type: 'MouseEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onMouseOver',
    type: 'MouseEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onMouseOverCapture',
    type: 'MouseEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onMouseUp',
    type: 'MouseEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onMouseUpCapture',
    type: 'MouseEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onSelect',
    type: 'ReactEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onSelectCapture',
    type: 'ReactEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onTouchCancel',
    type: 'TouchEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onTouchCancelCapture',
    type: 'TouchEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onTouchEnd',
    type: 'TouchEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onTouchEndCapture',
    type: 'TouchEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onTouchMove',
    type: 'TouchEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onTouchMoveCapture',
    type: 'TouchEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onTouchStart',
    type: 'TouchEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onTouchStartCapture',
    type: 'TouchEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onPointerDown',
    type: 'PointerEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onPointerDownCapture',
    type: 'PointerEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onPointerMove',
    type: 'PointerEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onPointerMoveCapture',
    type: 'PointerEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onPointerUp',
    type: 'PointerEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onPointerUpCapture',
    type: 'PointerEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onPointerCancel',
    type: 'PointerEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onPointerCancelCapture',
    type: 'PointerEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onPointerEnter',
    type: 'PointerEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onPointerLeave',
    type: 'PointerEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onPointerOver',
    type: 'PointerEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onPointerOverCapture',
    type: 'PointerEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onPointerOut',
    type: 'PointerEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onPointerOutCapture',
    type: 'PointerEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onGotPointerCapture',
    type: 'PointerEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onGotPointerCaptureCapture',
    type: 'PointerEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onLostPointerCapture',
    type: 'PointerEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onLostPointerCaptureCapture',
    type: 'PointerEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onScroll',
    type: 'UIEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onScrollCapture',
    type: 'UIEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onScrollEnd',
    type: 'UIEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onScrollEndCapture',
    type: 'UIEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onWheel',
    type: 'WheelEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onWheelCapture',
    type: 'WheelEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onAnimationStart',
    type: 'AnimationEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onAnimationStartCapture',
    type: 'AnimationEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onAnimationEnd',
    type: 'AnimationEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onAnimationEndCapture',
    type: 'AnimationEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onAnimationIteration',
    type: 'AnimationEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onAnimationIterationCapture',
    type: 'AnimationEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onToggle',
    type: 'ToggleEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onBeforeToggle',
    type: 'ToggleEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onTransitionCancel',
    type: 'TransitionEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onTransitionCancelCapture',
    type: 'TransitionEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onTransitionEnd',
    type: 'TransitionEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onTransitionEndCapture',
    type: 'TransitionEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onTransitionRun',
    type: 'TransitionEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onTransitionRunCapture',
    type: 'TransitionEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onTransitionStart',
    type: 'TransitionEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onTransitionStartCapture',
    type: 'TransitionEventHandler<HTMLInputElement>',
    description: 'Forwarded React DOM prop.',
  },
];

const inheritedNativeInputApi: readonly ComponentApiProp[] = [
  {
    name: 'allowFontScaling',
    type: 'boolean',
    description:
      'Specifies whether fonts should scale to respect Text Size accessibility settings.\nThe default is `true`.',
  },
  {
    name: 'autoCapitalize',
    type: "'none' | 'sentences' | 'words' | 'characters'",
    description:
      "Can tell TextInput to automatically capitalize certain characters.\n     characters: all characters,\n     words: first letter of each word\n     sentences: first letter of each sentence (default)\n     none: don't auto capitalize anything\n\nhttps://reactnative.dev/docs/textinput#autocapitalize",
  },
  {
    name: 'autoComplete',
    type: "'email' | 'password' | 'tel' | 'url' | '2fa-app-otp' | 'additional-name' | 'address-line1' | 'address-line2' | 'birthdate-day' | 'birthdate-full' | 'birthdate-month' | 'birthdate-year' | 'cc-csc' | 'cc-exp' | 'cc-exp-day' | 'cc-exp-month' | 'cc-exp-year' | 'cc-number' | 'cc-name' | 'cc-given-name' | 'cc-middle-name' | 'cc-family-name' | 'cc-type' | 'country' | 'current-password' | 'email-otp' | 'flight-confirmation-code' | 'flight-number' | 'family-name' | 'gender' | 'gift-card-number' | 'gift-card-pin' | 'given-name' | 'honorific-prefix' | 'honorific-suffix' | 'loyalty-account-number' | 'name' | 'name-family' | 'name-given' | 'name-middle' | 'name-middle-initial' | 'name-prefix' | 'name-suffix' | 'new-password' | 'nickname' | 'one-time-code' | 'organization' | 'organization-title' | 'password-new' | 'postal-address' | 'postal-address-country' | 'postal-address-dependent-locality' | 'postal-address-extended' | 'postal-address-extended-postal-code' | 'postal-address-locality' | 'postal-address-region' | 'postal-address-unit' | 'postal-code' | 'promo-code' | 'street-address' | 'sms-otp' | 'tel-country-code' | 'tel-national' | 'tel-device' | 'upi-vpa' | 'wifi-password' | 'username' | 'username-new' | 'off'",
    description:
      'Specifies autocomplete hints for the system, so it can provide autofill.\nOn Android, the system will always attempt to offer autofill by using heuristics to identify the type of content.\nTo disable autocomplete, set autoComplete to off.\n\nThe following values work across platforms:\n\n- `additional-name`\n- `address-line1`\n- `address-line2`\n- `cc-number`\n- `country`\n- `current-password`\n- `email`\n- `family-name`\n- `given-name`\n- `honorific-prefix`\n- `honorific-suffix`\n- `name`\n- `new-password`\n- `off`\n- `one-time-code`\n- `postal-code`\n- `street-address`\n- `tel`\n- `username`\n\nThe following values work on iOS only:\n\n- `nickname`\n- `organization`\n- `organization-title`\n- `url`\n\nThe following values work on Android only:\n\n- `birthdate-day`\n- `birthdate-full`\n- `birthdate-month`\n- `birthdate-year`\n- `cc-csc`\n- `cc-exp`\n- `cc-exp-day`\n- `cc-exp-month`\n- `cc-exp-year`\n- `2fa-app-otp`\n- `email-otp`\n- `flight-confirmation-code`\n- `flight-number`\n- `gender`\n- `gift-card-number`\n- `gift-card-pin`\n- `loyalty-account-number`\n- `name-family`\n- `name-given`\n- `name-middle`\n- `name-middle-initial`\n- `name-prefix`\n- `name-suffix`\n- `password`\n- `password-new`\n- `postal-address`\n- `postal-address-country`\n- `postal-address-dependent-locality`\n- `postal-address-extended`\n- `postal-address-extended-postal-code`\n- `postal-address-locality`\n- `postal-address-region`\n- `postal-address-unit`\n- `promo-code`\n- `sms-otp`\n- `tel-country-code`\n- `tel-national`\n- `tel-device`\n- `upi-vpa`\n- `wifi-password`\n- `username-new`',
  },
  {
    name: 'autoCorrect',
    type: 'boolean',
    description: 'If false, disables auto-correct.\nThe default value is true.',
  },
  {
    name: 'autoFocus',
    type: 'boolean',
    description:
      'If true, focuses the input on componentDidMount.\nThe default value is false.',
  },
  {
    name: 'blurOnSubmit',
    type: 'boolean',
    description:
      'If `true`, the text field will blur when submitted.\nThe default value is true for single-line fields and false for\nmultiline fields. Note that for multiline fields, setting `blurOnSubmit`\nto `true` means that pressing return will blur the field and trigger the\n`onSubmitEditing` event instead of inserting a newline into the field.',
  },
  {
    name: 'submitBehavior',
    type: "'submit' | 'blurAndSubmit' | 'newline'",
    description:
      "When the return key is pressed,\n\nFor single line inputs:\n\n- `'newline`' defaults to `'blurAndSubmit'`\n- `undefined` defaults to `'blurAndSubmit'`\n\nFor multiline inputs:\n\n- `'newline'` adds a newline\n- `undefined` defaults to `'newline'`\n\nFor both single line and multiline inputs:\n\n- `'submit'` will only send a submit event and not blur the input\n- `'blurAndSubmit`' will both blur the input and send a submit event",
  },
  {
    name: 'caretHidden',
    type: 'boolean',
    description: 'If true, caret is hidden. The default value is false.',
  },
  {
    name: 'contextMenuHidden',
    type: 'boolean',
    description: 'If true, context menu is hidden. The default value is false.',
  },
  {
    name: 'inputMode',
    type: "'text' | 'email' | 'tel' | 'url' | 'search' | 'numeric' | 'none' | 'decimal'",
    description:
      'Works like the inputmode attribute in HTML, it determines which keyboard to open, e.g. numeric and has precedence over keyboardType.',
  },
  {
    name: 'maxLength',
    type: 'number',
    description:
      'Limits the maximum number of characters that can be entered.\nUse this instead of implementing the logic in JS to avoid flicker.',
  },
  {
    name: 'multiline',
    type: 'boolean',
    description:
      'If true, the text input can be multiple lines. The default value is false.',
  },
  {
    name: 'onBlur',
    type: '((e: BlurEvent) => void)',
    description:
      'Callback that is called when the text input is blurred\n\nNote: If you are trying to find the last value of TextInput, you can use the `onEndEditing`\nevent, which is fired upon completion of editing.',
  },
  {
    name: 'onContentSizeChange',
    type: '((e: TextInputContentSizeChangeEvent) => void)',
    description:
      "Callback that is called when the text input's content size changes.\nThis will be called with\n`{ nativeEvent: { contentSize: { width, height } } }`.\n\nOnly called for multiline text inputs.",
  },
  {
    name: 'onEndEditing',
    type: '((e: TextInputEndEditingEvent) => void)',
    description: 'Callback that is called when text input ends.',
  },
  {
    name: 'onPress',
    type: '((e: NativeSyntheticEvent<NativeTouchEvent>) => void)',
    description: 'Called when a single tap gesture is detected.',
  },
  {
    name: 'onPressIn',
    type: '((e: NativeSyntheticEvent<NativeTouchEvent>) => void)',
    description: 'Callback that is called when a touch is engaged.',
  },
  {
    name: 'onPressOut',
    type: '((e: NativeSyntheticEvent<NativeTouchEvent>) => void)',
    description: 'Callback that is called when a touch is released.',
  },
  {
    name: 'onFocus',
    type: '((e: FocusEvent) => void)',
    description: 'Callback that is called when the text input is focused',
  },
  {
    name: 'onSelectionChange',
    type: '((e: TextInputSelectionChangeEvent) => void)',
    description:
      'Callback that is called when the text input selection is changed.',
  },
  {
    name: 'onSubmitEditing',
    type: '((e: TextInputSubmitEditingEvent) => void)',
    description:
      "Callback that is called when the text input's submit button is pressed.",
  },
  {
    name: 'onScroll',
    type: '((e: TextInputScrollEvent) => void)',
    description:
      'Invoked on content scroll with\n `{ nativeEvent: { contentOffset: { x, y } } }`.\n\nMay also contain other properties from ScrollEvent but on Android contentSize is not provided for performance reasons.',
  },
  {
    name: 'onKeyPress',
    type: '((e: TextInputKeyPressEvent) => void)',
    description:
      "Callback that is called when a key is pressed.\nThis will be called with\n `{ nativeEvent: { key: keyValue } }`\nwhere keyValue is 'Enter' or 'Backspace' for respective keys and the typed-in character otherwise including ' ' for space.\n\nFires before onChange callbacks.\nNote: on Android only the inputs from soft keyboard are handled, not the hardware keyboard inputs.",
  },
  {
    name: 'placeholderTextColor',
    type: 'ColorValue',
    description: 'The text color of the placeholder string',
  },
  {
    name: 'returnKeyType',
    type: "'search' | 'default' | 'none' | 'done' | 'go' | 'next' | 'send' | 'previous' | 'google' | 'join' | 'route' | 'yahoo' | 'emergency-call'",
    description:
      "enum('default', 'go', 'google', 'join', 'next', 'route', 'search', 'send', 'yahoo', 'done', 'emergency-call')\nDetermines how the return key should look.",
  },
  {
    name: 'enterKeyHint',
    type: "'search' | 'done' | 'go' | 'next' | 'send' | 'previous' | 'enter'",
    description:
      'Determines what text should be shown to the return key on virtual keyboards.\nHas precedence over the returnKeyType prop.',
  },
  {
    name: 'selectTextOnFocus',
    type: 'boolean',
    description: 'If true, all text will automatically be selected on focus',
  },
  {
    name: 'selection',
    type: '{ start: number; end?: number; }',
    description:
      "The start and end of the text input's selection. Set start and end to\nthe same value to position the cursor.",
  },
  {
    name: 'selectionColor',
    type: 'ColorValue',
    description: 'The highlight (and cursor on ios) color of the text input',
  },
  {
    name: 'textAlign',
    type: "'left' | 'center' | 'right'",
    description:
      'Align the input text to the left, center, or right sides of the input field.',
  },
  {
    name: 'inputAccessoryViewID',
    type: 'string',
    description:
      'Used to connect to an InputAccessoryView. Not part of react-natives documentation, but present in examples and\ncode.\nSee https://reactnative.dev/docs/inputaccessoryview for more information.',
  },
  {
    name: 'inputAccessoryViewButtonLabel',
    type: 'string',
    description:
      'An optional label that overrides the default input accessory view button label.',
  },
  {
    name: 'maxFontSizeMultiplier',
    type: 'number | null',
    description:
      'Specifies largest possible scale a font can reach when allowFontScaling is enabled. Possible values:\n- null/undefined (default): inherit from the parent node or the global default (0)\n- 0: no max, ignore parent/global default\n- >= 1: sets the maxFontSizeMultiplier of this node to this value',
  },
  {
    name: 'children',
    type: 'React.ReactNode',
    description: 'Forwarded React Native prop.',
  },
  {
    name: 'hitSlop',
    type: 'number | Insets | null',
    description:
      'This defines how far a touch event can start away from the view.\nTypical interface guidelines recommend touch targets that are at least\n30 - 40 points/density-independent pixels. If a Touchable view has\na height of 20 the touchable height can be extended to 40 with\nhitSlop={{top: 10, bottom: 10, left: 0, right: 0}}\nNOTE The touch area never extends past the parent view bounds and\nthe Z-index of sibling views always takes precedence if a touch\nhits two overlapping views.',
  },
  {
    name: 'id',
    type: 'string',
    description: 'Used to reference react managed views from native code.',
  },
  {
    name: 'needsOffscreenAlphaCompositing',
    type: 'boolean',
    description:
      "Whether this view needs to rendered offscreen and composited with an alpha in order to preserve 100% correct colors and blending behavior.\nThe default (false) falls back to drawing the component and its children\nwith an alpha applied to the paint used to draw each element instead of rendering the full component offscreen and compositing it back with an alpha value.\nThis default may be noticeable and undesired in the case where the View you are setting an opacity on\nhas multiple overlapping elements (e.g. multiple overlapping Views, or text and a background).\n\nRendering offscreen to preserve correct alpha behavior is extremely expensive\nand hard to debug for non-native developers, which is why it is not turned on by default.\nIf you do need to enable this property for an animation,\nconsider combining it with renderToHardwareTextureAndroid if the view contents are static (i.e. it doesn't need to be redrawn each frame).\nIf that property is enabled, this View will be rendered off-screen once,\nsaved in a hardware texture, and then composited onto the screen with an alpha each frame without having to switch rendering targets on the GPU.",
  },
  {
    name: 'onLayout',
    type: '((event: LayoutChangeEvent) => void)',
    description:
      'Invoked on mount and layout changes with\n\n{nativeEvent: { layout: {x, y, width, height}}}.',
  },
  {
    name: 'pointerEvents',
    type: "'none' | 'box-none' | 'box-only' | 'auto'",
    description:
      "\nIn the absence of auto property, none is much like CSS's none value. box-none is as if you had applied the CSS class:\n\n.box-none {\n  pointer-events: none;\n}\n.box-none * {\n  pointer-events: all;\n}\n\nbox-only is the equivalent of\n\n.box-only {\n  pointer-events: all;\n}\n.box-only * {\n  pointer-events: none;\n}\n\nBut since pointerEvents does not affect layout/appearance, and we are already deviating from the spec by adding additional modes,\nwe opt to not include pointerEvents on style. On some platforms, we would need to implement it as a className anyways. Using style or not is an implementation detail of the platform.",
  },
  {
    name: 'removeClippedSubviews',
    type: 'boolean',
    description:
      '\nThis is a special performance property exposed by RCTView and is useful for scrolling content when there are many subviews,\nmost of which are offscreen. For this property to be effective, it must be applied to a view that contains many subviews that extend outside its bound.\nThe subviews must also have overflow: hidden, as should the containing view (or one of its superviews).',
  },
  {
    name: 'nativeID',
    type: 'string',
    description: 'Used to reference react managed views from native code.',
  },
  {
    name: 'collapsable',
    type: 'boolean',
    description:
      "Views that are only used to layout their children or otherwise don't draw anything\nmay be automatically removed from the native hierarchy as an optimization.\nSet this property to false to disable this optimization and ensure that this View exists in the native view hierarchy.",
  },
  {
    name: 'collapsableChildren',
    type: 'boolean',
    description:
      'Setting to false prevents direct children of the view from being removed\nfrom the native view hierarchy, similar to the effect of setting\n`collapsable={false}` on each child.',
  },
  {
    name: 'renderToHardwareTextureAndroid',
    type: 'boolean',
    description:
      "Whether this view should render itself (and all of its children) into a single hardware texture on the GPU.\n\nOn Android, this is useful for animations and interactions that only modify opacity, rotation, translation, and/or scale:\nin those cases, the view doesn't have to be redrawn and display lists don't need to be re-executed. The texture can just be\nre-used and re-composited with different parameters. The downside is that this can use up limited video memory, so this prop should be set back to false at the end of the interaction/animation.",
  },
  {
    name: 'focusable',
    type: 'boolean',
    description:
      'Whether this `View` should be focusable with a non-touch input device, eg. receive focus with a hardware keyboard.',
  },
  {
    name: 'tabIndex',
    type: '0 | -1',
    description:
      'Indicates whether this `View` should be focusable with a non-touch input device, eg. receive focus with a hardware keyboard.\nSee https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex\nfor more details.\n\nSupports the following values:\n-  0 (View is focusable)\n- -1 (View is not focusable)',
  },
  {
    name: 'shouldRasterizeIOS',
    type: 'boolean',
    description:
      "Whether this view should be rendered as a bitmap before compositing.\n\nOn iOS, this is useful for animations and interactions that do not modify this component's dimensions nor its children;\nfor example, when translating the position of a static view, rasterization allows the renderer to reuse a cached bitmap of a static view\nand quickly composite it during each frame.\n\nRasterization incurs an off-screen drawing pass and the bitmap consumes memory.\nTest and measure when using this property.",
  },
  {
    name: 'isTVSelectable',
    type: 'boolean',
    description:
      '*(Apple TV only)* When set to true, this view will be focusable\nand navigable using the Apple TV remote.',
  },
  {
    name: 'hasTVPreferredFocus',
    type: 'boolean',
    description:
      '*(Apple TV only)* May be set to true to force the Apple TV focus engine to move focus to this view.',
  },
  {
    name: 'tvParallaxShiftDistanceX',
    type: 'number',
    description:
      '*(Apple TV only)* May be used to change the appearance of the Apple TV parallax effect when this view goes in or out of focus.  Defaults to 2.0.',
  },
  {
    name: 'tvParallaxShiftDistanceY',
    type: 'number',
    description:
      '*(Apple TV only)* May be used to change the appearance of the Apple TV parallax effect when this view goes in or out of focus.  Defaults to 2.0.',
  },
  {
    name: 'tvParallaxTiltAngle',
    type: 'number',
    description:
      '*(Apple TV only)* May be used to change the appearance of the Apple TV parallax effect when this view goes in or out of focus.  Defaults to 0.05.',
  },
  {
    name: 'tvParallaxMagnification',
    type: 'number',
    description:
      '*(Apple TV only)* May be used to change the appearance of the Apple TV parallax effect when this view goes in or out of focus.  Defaults to 1.0.',
  },
  {
    name: 'onStartShouldSetResponder',
    type: '((event: GestureResponderEvent) => boolean)',
    description:
      'Does this view want to become responder on the start of a touch?',
  },
  {
    name: 'onMoveShouldSetResponder',
    type: '((event: GestureResponderEvent) => boolean)',
    description:
      'Called for every touch move on the View when it is not the responder: does this view want to "claim" touch responsiveness?',
  },
  {
    name: 'onResponderEnd',
    type: '((event: GestureResponderEvent) => void)',
    description:
      'If the View returns true and attempts to become the responder, one of the following will happen:',
  },
  {
    name: 'onResponderGrant',
    type: '((event: GestureResponderEvent) => void)',
    description:
      'The View is now responding for touch events.\nThis is the time to highlight and show the user what is happening',
  },
  {
    name: 'onResponderReject',
    type: '((event: GestureResponderEvent) => void)',
    description:
      'Something else is the responder right now and will not release it',
  },
  {
    name: 'onResponderMove',
    type: '((event: GestureResponderEvent) => void)',
    description: 'The user is moving their finger',
  },
  {
    name: 'onResponderRelease',
    type: '((event: GestureResponderEvent) => void)',
    description: 'Fired at the end of the touch, ie "touchUp"',
  },
  {
    name: 'onResponderStart',
    type: '((event: GestureResponderEvent) => void)',
    description: 'Forwarded React Native prop.',
  },
  {
    name: 'onResponderTerminationRequest',
    type: '((event: GestureResponderEvent) => boolean)',
    description:
      'Something else wants to become responder.\nShould this view release the responder? Returning true allows release',
  },
  {
    name: 'onResponderTerminate',
    type: '((event: GestureResponderEvent) => void)',
    description:
      'The responder has been taken from the View.\nMight be taken by other views after a call to onResponderTerminationRequest,\nor might be taken by the OS without asking (happens with control center/ notification center on iOS)',
  },
  {
    name: 'onStartShouldSetResponderCapture',
    type: '((event: GestureResponderEvent) => boolean)',
    description:
      'onStartShouldSetResponder and onMoveShouldSetResponder are called with a bubbling pattern,\nwhere the deepest node is called first.\nThat means that the deepest component will become responder when multiple Views return true for *ShouldSetResponder handlers.\nThis is desirable in most cases, because it makes sure all controls and buttons are usable.\n\nHowever, sometimes a parent will want to make sure that it becomes responder.\nThis can be handled by using the capture phase.\nBefore the responder system bubbles up from the deepest component,\nit will do a capture phase, firing on*ShouldSetResponderCapture.\nSo if a parent View wants to prevent the child from becoming responder on a touch start,\nit should have a onStartShouldSetResponderCapture handler which returns true.',
  },
  {
    name: 'onMoveShouldSetResponderCapture',
    type: '((event: GestureResponderEvent) => boolean)',
    description:
      'onStartShouldSetResponder and onMoveShouldSetResponder are called with a bubbling pattern,\nwhere the deepest node is called first.\nThat means that the deepest component will become responder when multiple Views return true for *ShouldSetResponder handlers.\nThis is desirable in most cases, because it makes sure all controls and buttons are usable.\n\nHowever, sometimes a parent will want to make sure that it becomes responder.\nThis can be handled by using the capture phase.\nBefore the responder system bubbles up from the deepest component,\nit will do a capture phase, firing on*ShouldSetResponderCapture.\nSo if a parent View wants to prevent the child from becoming responder on a touch start,\nit should have a onStartShouldSetResponderCapture handler which returns true.',
  },
  {
    name: 'onTouchStart',
    type: '((event: GestureResponderEvent) => void)',
    description: 'Forwarded React Native prop.',
  },
  {
    name: 'onTouchMove',
    type: '((event: GestureResponderEvent) => void)',
    description: 'Forwarded React Native prop.',
  },
  {
    name: 'onTouchEnd',
    type: '((event: GestureResponderEvent) => void)',
    description: 'Forwarded React Native prop.',
  },
  {
    name: 'onTouchCancel',
    type: '((event: GestureResponderEvent) => void)',
    description: 'Forwarded React Native prop.',
  },
  {
    name: 'onTouchEndCapture',
    type: '((event: GestureResponderEvent) => void)',
    description: 'Forwarded React Native prop.',
  },
  {
    name: 'onPointerEnter',
    type: '((event: PointerEvent) => void)',
    description: 'Forwarded React Native prop.',
  },
  {
    name: 'onPointerEnterCapture',
    type: '((event: PointerEvent) => void)',
    description: 'Forwarded React Native prop.',
  },
  {
    name: 'onPointerLeave',
    type: '((event: PointerEvent) => void)',
    description: 'Forwarded React Native prop.',
  },
  {
    name: 'onPointerLeaveCapture',
    type: '((event: PointerEvent) => void)',
    description: 'Forwarded React Native prop.',
  },
  {
    name: 'onPointerMove',
    type: '((event: PointerEvent) => void)',
    description: 'Forwarded React Native prop.',
  },
  {
    name: 'onPointerMoveCapture',
    type: '((event: PointerEvent) => void)',
    description: 'Forwarded React Native prop.',
  },
  {
    name: 'onPointerCancel',
    type: '((event: PointerEvent) => void)',
    description: 'Forwarded React Native prop.',
  },
  {
    name: 'onPointerCancelCapture',
    type: '((event: PointerEvent) => void)',
    description: 'Forwarded React Native prop.',
  },
  {
    name: 'onPointerDown',
    type: '((event: PointerEvent) => void)',
    description: 'Forwarded React Native prop.',
  },
  {
    name: 'onPointerDownCapture',
    type: '((event: PointerEvent) => void)',
    description: 'Forwarded React Native prop.',
  },
  {
    name: 'onPointerUp',
    type: '((event: PointerEvent) => void)',
    description: 'Forwarded React Native prop.',
  },
  {
    name: 'onPointerUpCapture',
    type: '((event: PointerEvent) => void)',
    description: 'Forwarded React Native prop.',
  },
  {
    name: 'accessible',
    type: 'boolean',
    description:
      'When true, indicates that the view is an accessibility element.\nBy default, all the touchable elements are accessible.',
  },
  {
    name: 'accessibilityActions',
    type: 'readonly Readonly<{ name: AccessibilityActionName | string; label?: string; }>[]',
    description:
      'Provides an array of custom actions available for accessibility.',
  },
  {
    name: 'accessibilityLabel',
    type: 'string',
    description:
      "Overrides the text that's read by the screen reader when the user interacts with the element. By default, the\nlabel is constructed by traversing all the children and accumulating all the Text nodes separated by space.",
  },
  {
    name: 'aria-label',
    type: 'string',
    description:
      'Alias for accessibilityLabel  https://reactnative.dev/docs/view#accessibilitylabel\nhttps://github.com/facebook/react-native/issues/34424',
  },
  {
    name: 'accessibilityRole',
    type: "'text' | 'search' | 'none' | 'button' | 'togglebutton' | 'link' | 'image' | 'keyboardkey' | 'adjustable' | 'imagebutton' | 'header' | 'summary' | 'alert' | 'checkbox' | 'combobox' | 'menu' | 'menubar' | 'menuitem' | 'progressbar' | 'radio' | 'radiogroup' | 'scrollbar' | 'spinbutton' | 'switch' | 'tab' | 'tabbar' | 'tablist' | 'timer' | 'list' | 'toolbar'",
    description:
      'Accessibility Role tells a person using either VoiceOver on iOS or TalkBack on Android the type of element that is focused on.',
  },
  {
    name: 'accessibilityState',
    type: 'AccessibilityState',
    description:
      'Accessibility State tells a person using either VoiceOver on iOS or TalkBack on Android the state of the element currently focused on.',
  },
  {
    name: 'aria-busy',
    type: 'boolean',
    description:
      'alias for accessibilityState\n\nsee https://reactnative.dev/docs/accessibility#accessibilitystate',
  },
  {
    name: 'aria-checked',
    type: 'boolean | "mixed"',
    description: 'Forwarded React Native prop.',
  },
  {
    name: 'aria-disabled',
    type: 'boolean',
    description: 'Forwarded React Native prop.',
  },
  {
    name: 'aria-expanded',
    type: 'boolean',
    description: 'Forwarded React Native prop.',
  },
  {
    name: 'aria-selected',
    type: 'boolean',
    description: 'Forwarded React Native prop.',
  },
  {
    name: 'accessibilityHint',
    type: 'string',
    description:
      'An accessibility hint helps users understand what will happen when they perform an action on the accessibility element when that result is not obvious from the accessibility label.',
  },
  {
    name: 'accessibilityValue',
    type: 'AccessibilityValue',
    description:
      "Represents the current value of a component. It can be a textual description of a component's value, or for range-based components, such as sliders and progress bars,\nit contains range information (minimum, current, and maximum).",
  },
  {
    name: 'aria-valuemax',
    type: 'number',
    description: 'Forwarded React Native prop.',
  },
  {
    name: 'aria-valuemin',
    type: 'number',
    description: 'Forwarded React Native prop.',
  },
  {
    name: 'aria-valuenow',
    type: 'number',
    description: 'Forwarded React Native prop.',
  },
  {
    name: 'aria-valuetext',
    type: 'string',
    description: 'Forwarded React Native prop.',
  },
  {
    name: 'onAccessibilityAction',
    type: '((event: AccessibilityActionEvent) => void)',
    description:
      'When `accessible` is true, the system will try to invoke this function when the user performs an accessibility custom action.',
  },
  {
    name: 'importantForAccessibility',
    type: "'auto' | 'yes' | 'no' | 'no-hide-descendants'",
    description:
      '[Android] Controlling if a view fires accessibility events and if it is reported to accessibility services.',
  },
  {
    name: 'aria-hidden',
    type: 'boolean',
    description:
      'A value indicating whether the accessibility elements contained within\nthis accessibility element are hidden.',
  },
  {
    name: 'aria-modal',
    type: 'boolean',
    description: 'Forwarded React Native prop.',
  },
  {
    name: 'role',
    type: "'none' | 'button' | 'link' | 'summary' | 'alert' | 'checkbox' | 'combobox' | 'menu' | 'menubar' | 'menuitem' | 'progressbar' | 'radio' | 'radiogroup' | 'scrollbar' | 'spinbutton' | 'switch' | 'tab' | 'tablist' | 'timer' | 'list' | 'toolbar' | 'alertdialog' | 'application' | 'article' | 'banner' | 'cell' | 'columnheader' | 'complementary' | 'contentinfo' | 'definition' | 'dialog' | 'directory' | 'document' | 'feed' | 'figure' | 'form' | 'grid' | 'group' | 'heading' | 'img' | 'listitem' | 'log' | 'main' | 'marquee' | 'math' | 'meter' | 'navigation' | 'note' | 'option' | 'presentation' | 'region' | 'row' | 'rowgroup' | 'rowheader' | 'searchbox' | 'separator' | 'slider' | 'status' | 'table' | 'tabpanel' | 'term' | 'tooltip' | 'tree' | 'treegrid' | 'treeitem'",
    description:
      'Indicates to accessibility services to treat UI component like a specific role.',
  },
  {
    name: 'accessibilityLabelledBy',
    type: 'string | string[]',
    description:
      'Identifies the element that labels the element it is applied to. When the assistive technology focuses on the component with this props,\nthe text is read aloud. The value should should match the nativeID of the related element.',
  },
  {
    name: 'aria-labelledby',
    type: 'string',
    description:
      'Identifies the element that labels the element it is applied to. When the assistive technology focuses on the component with this props,\nthe text is read aloud. The value should should match the nativeID of the related element.',
  },
  {
    name: 'accessibilityLiveRegion',
    type: "'none' | 'polite' | 'assertive'",
    description:
      'Indicates to accessibility services whether the user should be notified\nwhen this view changes. Works for Android API >= 19 only.',
  },
  {
    name: 'aria-live',
    type: "'off' | 'polite' | 'assertive'",
    description:
      'Indicates to accessibility services whether the user should be notified\nwhen this view changes. Works for Android API >= 19 only.',
  },
  {
    name: 'screenReaderFocusable',
    type: 'boolean',
    description:
      'Enables the view to be screen reader focusable, not keyboard focusable.',
  },
  {
    name: 'accessibilityElementsHidden',
    type: 'boolean',
    description:
      'A Boolean value indicating whether the accessibility elements contained within this accessibility element\nare hidden to the screen reader.',
  },
  {
    name: 'accessibilityViewIsModal',
    type: 'boolean',
    description:
      'A Boolean value indicating whether VoiceOver should ignore the elements within views that are siblings of the receiver.',
  },
  {
    name: 'onAccessibilityEscape',
    type: '(() => void)',
    description:
      'When accessible is true, the system will invoke this function when the user performs the escape gesture (scrub with two fingers).',
  },
  {
    name: 'onAccessibilityTap',
    type: '(() => void)',
    description:
      'When `accessible` is true, the system will try to invoke this function when the user performs accessibility tap gesture.',
  },
  {
    name: 'onMagicTap',
    type: '(() => void)',
    description:
      'When accessible is true, the system will invoke this function when the user performs the magic tap gesture.',
  },
  {
    name: 'accessibilityIgnoresInvertColors',
    type: 'boolean',
    description:
      'https://reactnative.dev/docs/accessibility#accessibilityignoresinvertcolorsios',
  },
  {
    name: 'accessibilityLanguage',
    type: 'string',
    description:
      "By using the accessibilityLanguage property, the screen reader will understand which language to use while reading the element's label, value and hint. The provided string value must follow the BCP 47 specification (https://www.rfc-editor.org/info/bcp47).\nhttps://reactnative.dev/docs/accessibility#accessibilitylanguage-ios",
  },
  {
    name: 'accessibilityShowsLargeContentViewer',
    type: 'boolean',
    description:
      'A Boolean value that indicates whether or not to show the item in the large content viewer.\nAvailable on iOS 13.0+\nhttps://reactnative.dev/docs/accessibility#accessibilityshowslargecontentviewer',
  },
  {
    name: 'accessibilityLargeContentTitle',
    type: 'string',
    description:
      'When `accessibilityShowsLargeContentViewer` is set, this string will be used as title for the large content viewer.\nhttps://reactnative.dev/docs/accessibility#accessibilitylargecontenttitle',
  },
  {
    name: 'accessibilityRespondsToUserInteraction',
    type: 'boolean',
    description:
      'Blocks the user from interacting with the component through keyboard while still allowing\nscreen reader to interact with it if this View is still accessible.',
  },
  {
    name: 'disableKeyboardShortcuts',
    type: 'boolean',
    description:
      'If true, the keyboard shortcuts (undo/redo and copy buttons) are disabled. The default value is false.',
  },
  {
    name: 'clearButtonMode',
    type: "'never' | 'while-editing' | 'unless-editing' | 'always'",
    description:
      "enum('never', 'while-editing', 'unless-editing', 'always')\nWhen the clear button should appear on the right side of the text view",
  },
  {
    name: 'clearTextOnFocus',
    type: 'boolean',
    description:
      'If true, clears the text field automatically when editing begins',
  },
  {
    name: 'dataDetectorTypes',
    type: 'DataDetectorTypes | DataDetectorTypes[]',
    description:
      "Determines the types of data converted to clickable URLs in the text input.\nOnly valid if `multiline={true}` and `editable={false}`.\nBy default no data types are detected.\n\nYou can provide one type or an array of many types.\n\nPossible values for `dataDetectorTypes` are:\n\n- `'phoneNumber'`\n- `'link'`\n- `'address'`\n- `'calendarEvent'`\n- `'none'`\n- `'all'`",
  },
  {
    name: 'enablesReturnKeyAutomatically',
    type: 'boolean',
    description:
      'If true, the keyboard disables the return key when there is no text and automatically enables it when there is text.\nThe default value is false.',
  },
  {
    name: 'keyboardAppearance',
    type: "'default' | 'light' | 'dark'",
    description: 'Determines the color of the keyboard.',
  },
  {
    name: 'passwordRules',
    type: 'string | null',
    description:
      'Provide rules for your password.\nFor example, say you want to require a password with at least eight characters consisting of a mix of uppercase and lowercase letters, at least one number, and at most two consecutive characters.\n"required: upper; required: lower; required: digit; max-consecutive: 2; minlength: 8;"',
  },
  {
    name: 'rejectResponderTermination',
    type: 'boolean | null',
    description:
      'If `true`, allows TextInput to pass touch events to the parent component.\nThis allows components to be swipeable from the TextInput on iOS,\nas is the case on Android by default.\nIf `false`, TextInput always asks to handle the input (except when disabled).',
  },
  {
    name: 'selectionState',
    type: 'DocumentSelectionState',
    description:
      'See DocumentSelectionState.js, some state that is responsible for maintaining selection information for a document',
  },
  {
    name: 'spellCheck',
    type: 'boolean',
    description:
      'If false, disables spell-check style (i.e. red underlines). The default value is inherited from autoCorrect',
  },
  {
    name: 'textContentType',
    type: "'password' | 'none' | 'name' | 'nickname' | 'username' | 'flightNumber' | 'URL' | 'addressCity' | 'addressCityAndState' | 'addressState' | 'countryName' | 'creditCardNumber' | 'creditCardExpiration' | 'creditCardExpirationMonth' | 'creditCardExpirationYear' | 'creditCardSecurityCode' | 'creditCardType' | 'creditCardName' | 'creditCardGivenName' | 'creditCardMiddleName' | 'creditCardFamilyName' | 'emailAddress' | 'familyName' | 'fullStreetAddress' | 'givenName' | 'jobTitle' | 'location' | 'middleName' | 'namePrefix' | 'nameSuffix' | 'organizationName' | 'postalCode' | 'streetAddressLine1' | 'streetAddressLine2' | 'sublocality' | 'telephoneNumber' | 'newPassword' | 'oneTimeCode' | 'birthdate' | 'birthdateDay' | 'birthdateMonth' | 'birthdateYear' | 'cellularEID' | 'cellularIMEI' | 'dateTime' | 'shipmentTrackingNumber'",
    description:
      "Give the keyboard and the system information about the expected\nsemantic meaning for the content that users enter.\n\nTo disable autofill, set textContentType to `none`.\n\nPossible values for `textContentType` are:\n\n - `'none'`\n - `'URL'`\n - `'addressCity'`\n - `'addressCityAndState'`\n - `'addressState'`\n - `'countryName'`\n - `'creditCardNumber'`\n - `'creditCardExpiration'` (iOS 17+)\n - `'creditCardExpirationMonth'` (iOS 17+)\n - `'creditCardExpirationYear'` (iOS 17+)\n - `'creditCardSecurityCode'` (iOS 17+)\n - `'creditCardType'` (iOS 17+)\n - `'creditCardName'` (iOS 17+)\n - `'creditCardGivenName'` (iOS 17+)\n - `'creditCardMiddleName'` (iOS 17+)\n - `'creditCardFamilyName'` (iOS 17+)\n - `'emailAddress'`\n - `'familyName'`\n - `'fullStreetAddress'`\n - `'givenName'`\n - `'jobTitle'`\n - `'location'`\n - `'middleName'`\n - `'name'`\n - `'namePrefix'`\n - `'nameSuffix'`\n - `'nickname'`\n - `'organizationName'`\n - `'postalCode'`\n - `'streetAddressLine1'`\n - `'streetAddressLine2'`\n - `'sublocality'`\n - `'telephoneNumber'`\n - `'username'`\n - `'password'`\n - `'newPassword'`\n - `'oneTimeCode'`\n - `'birthdate'` (iOS 17+)\n - `'birthdateDay'` (iOS 17+)\n - `'birthdateMonth'` (iOS 17+)\n - `'birthdateYear'` (iOS 17+)\n - `'cellularEID'` (iOS 17.4+)\n - `'cellularIMEI'` (iOS 17.4+)\n - `'dateTime'` (iOS 15+)\n - `'flightNumber'` (iOS 15+)\n - `'shipmentTrackingNumber'` (iOS 15+)",
  },
  {
    name: 'scrollEnabled',
    type: 'boolean',
    description:
      'If false, scrolling of the text view will be disabled. The default value is true. Only works with multiline={true}',
  },
  {
    name: 'lineBreakStrategyIOS',
    type: "'none' | 'standard' | 'hangul-word' | 'push-out'",
    description: 'Set line break strategy on iOS.',
  },
  {
    name: 'lineBreakModeIOS',
    type: "'wordWrapping' | 'char' | 'clip' | 'head' | 'middle' | 'tail'",
    description: 'Set line break mode on iOS.',
  },
  {
    name: 'smartInsertDelete',
    type: 'boolean',
    description:
      'If `false`, the iOS system will not insert an extra space after a paste operation\nneither delete one or two spaces after a cut or delete operation.\n\nThe default value is `true`.',
  },
  {
    name: 'cursorColor',
    type: 'ColorValue | null',
    description:
      'When provided it will set the color of the cursor (or "caret") in the component.\nUnlike the behavior of `selectionColor` the cursor color will be set independently\nfrom the color of the text selection box.',
  },
  {
    name: 'selectionHandleColor',
    type: 'ColorValue | null',
    description:
      'When provided it will set the color of the selection handles when highlighting text.\nUnlike the behavior of `selectionColor` the handle color will be set independently\nfrom the color of the text selection box.',
  },
  {
    name: 'importantForAutofill',
    type: "'auto' | 'yes' | 'no' | 'noExcludeDescendants' | 'yesExcludeDescendants'",
    description:
      "Determines whether the individual fields in your app should be included in a\nview structure for autofill purposes on Android API Level 26+. Defaults to auto.\nTo disable auto complete, use `off`.\n\n*Android Only*\n\nThe following values work on Android only:\n\n- `auto` - let Android decide\n- `no` - not important for autofill\n- `noExcludeDescendants` - this view and its children aren't important for autofill\n- `yes` - is important for autofill\n- `yesExcludeDescendants` - this view is important for autofill but its children aren't",
  },
  {
    name: 'disableFullscreenUI',
    type: 'boolean',
    description:
      'When false, if there is a small amount of space available around a text input (e.g. landscape orientation on a phone),\n  the OS may choose to have the user edit the text inside of a full screen text input mode.\nWhen true, this feature is disabled and users will always edit the text directly inside of the text input.\nDefaults to false.',
  },
  {
    name: 'inlineImageLeft',
    type: 'string',
    description:
      'If defined, the provided image resource will be rendered on the left.',
  },
  {
    name: 'inlineImagePadding',
    type: 'number',
    description:
      'Padding between the inline image, if any, and the text input itself.',
  },
  {
    name: 'numberOfLines',
    type: 'number',
    description:
      'Sets the number of lines for a TextInput.\nUse it with multiline set to true to be able to fill the lines.',
  },
  {
    name: 'returnKeyLabel',
    type: 'string',
    description:
      'Sets the return key to the label. Use it instead of `returnKeyType`.',
  },
  {
    name: 'textBreakStrategy',
    type: "'simple' | 'highQuality' | 'balanced'",
    description:
      'Set text break strategy on Android API Level 23+, possible values are simple, highQuality, balanced\nThe default value is simple.',
  },
  {
    name: 'underlineColorAndroid',
    type: 'ColorValue',
    description: 'The color of the textInput underline.',
  },
  {
    name: 'textAlignVertical',
    type: "'center' | 'auto' | 'top' | 'bottom'",
    description: 'Vertically align text when `multiline` is set to true',
  },
  {
    name: 'showSoftInputOnFocus',
    type: 'boolean',
    description:
      'When false, it will prevent the soft keyboard from showing when the field is focused. The default value is true',
  },
  {
    name: 'verticalAlign',
    type: "'auto' | 'middle' | 'top' | 'bottom'",
    description: 'Vertically align text when `multiline` is set to true',
  },
];

export const inputApi = {
  react: {
    sections: reactInputApiSections,
    inheritedProps: inheritedReactInputApi,
  },
  'react-native': {
    sections: nativeInputApiSections,
    inheritedProps: inheritedNativeInputApi,
  },
} as const;
