import { describe, expect, it } from 'vitest';

import * as api from './index';

export const publicApiSymbols = [
  'Accordion',
  'AccordionContentProps',
  'AccordionItemProps',
  'AccordionProps',
  'AccordionTriggerProps',
  'Button',
  'ButtonProps',
  'Checkbox',
  'CheckboxProps',
  'Dropdown',
  'DropdownCheckboxItemProps',
  'DropdownContentProps',
  'DropdownGroupProps',
  'DropdownItemProps',
  'DropdownLabelProps',
  'DropdownProps',
  'DropdownRadioGroupProps',
  'DropdownRadioItemProps',
  'DropdownSelectEvent',
  'DropdownSeparatorProps',
  'DropdownSubContentProps',
  'DropdownSubProps',
  'DropdownSubTriggerProps',
  'DropdownTriggerProps',
  'FormField',
  'FormFieldControlProps',
  'FormFieldDescriptionProps',
  'FormFieldLabelProps',
  'FormFieldMessageProps',
  'FormFieldProps',
  'Input',
  'InputProps',
  'Modal',
  'ModalAutoFocusEvent',
  'ModalBodyProps',
  'ModalCloseProps',
  'ModalContentPlacement',
  'ModalContentProps',
  'ModalContentSize',
  'ModalFooterProps',
  'ModalHeaderProps',
  'ModalOutsideEvent',
  'ModalOverlayProps',
  'ModalProps',
  'ModalScrollBehavior',
  'ModalTriggerProps',
  'Popover',
  'PopoverAnchorProps',
  'PopoverArrowAlign',
  'PopoverArrowProps',
  'PopoverCloseProps',
  'PopoverContentProps',
  'PopoverDescriptionProps',
  'PopoverProps',
  'PopoverTitleProps',
  'PopoverTriggerProps',
  'Portal',
  'PortalProps',
  'PortalProvider',
  'PortalProviderProps',
  'Radio',
  'RadioGroup',
  'RadioGroupItemProps',
  'RadioGroupProps',
  'RadioProps',
  'Select',
  'SelectContentSlotProps',
  'SelectEmptyProps',
  'SelectGroupProps',
  'SelectIconProps',
  'SelectItemBadgeProps',
  'SelectItemDescriptionProps',
  'SelectItemIconProps',
  'SelectItemProps',
  'SelectLabelProps',
  'SelectLoadingProps',
  'SelectOption',
  'SelectProps',
  'SelectRenderOptionContext',
  'SelectRenderValueContext',
  'SelectSearchProps',
  'SelectSeparatorProps',
  'SelectTriggerSlotProps',
  'SelectValueProps',
  'Switch',
  'SwitchProps',
  'Tabs',
  'TabsContentProps',
  'TabsIndicatorProps',
  'TabsListProps',
  'TabsProps',
  'TabsSlotProps',
  'TabsTriggerProps',
  'ThemeContextValue',
  'ThemeName',
  'ThemeProvider',
  'ThemeProviderProps',
  'Tooltip',
  'TooltipContentProps',
  'TooltipProps',
  'TooltipRootProps',
  'TooltipTriggerProps',
  'useTheme',
] as const;

describe('public API', () => {
  it('exports only documented runtime entries', () => {
    expect(Object.keys(api).sort()).toEqual([
      'Accordion',
      'Button',
      'Checkbox',
      'Dropdown',
      'FormField',
      'Input',
      'Modal',
      'Popover',
      'Portal',
      'PortalProvider',
      'Radio',
      'RadioGroup',
      'Select',
      'Switch',
      'Tabs',
      'ThemeProvider',
      'Tooltip',
      'useTheme',
    ]);
  });

  it('exports runtime components and hooks', () => {
    expect(api.ThemeProvider).toBeDefined();
    expect(api.Portal).toBeDefined();
    expect(api.PortalProvider).toBeDefined();
    expect(api.useTheme).toBeDefined();

    expect(typeof api.Portal).toBe('function');
    expect(typeof api.PortalProvider).toBe('function');
    expect(typeof api.useTheme).toBe('function');
    expect(typeof api.ThemeProvider).toBe('function');
  });
});
