// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

'use client';

import type { ReactNode } from 'react';

import { ComponentPlayground } from '../../shared/ComponentPlayground';
import { useComponentDemoState } from '../../shared/ComponentDemoStateProvider';
import { PlaygroundControlsFromSchema } from '../../shared/PlaygroundControls';

import { avatarPlaygroundControls } from './avatarPlaygroundSchema';

export type AvatarPlaygroundValue = {
  fallback: string;
  name: string;
  size: 'sm' | 'md' | 'lg';
  source: string;
};

type AvatarPlaygroundProps = {
  platform: 'react' | 'react-native';
  renderAvatar: (
    value: AvatarPlaygroundValue,
    onChange: <K extends keyof AvatarPlaygroundValue>(
      key: K,
      nextValue: AvatarPlaygroundValue[K]
    ) => void
  ) => ReactNode;
};

export const initialAvatarPlaygroundValue: AvatarPlaygroundValue = {
  fallback: 'example',
  name: 'example',
  size: 'sm',
  source: '',
};

export function AvatarPlayground({
  platform,
  renderAvatar,
}: AvatarPlaygroundProps) {
  const [value, setValue] = useComponentDemoState<AvatarPlaygroundValue>(
    initialAvatarPlaygroundValue
  );

  const update = (
    key: keyof AvatarPlaygroundValue,
    nextValue: AvatarPlaygroundValue[keyof AvatarPlaygroundValue]
  ) => {
    setValue({
      ...value,
      [key]: nextValue,
    });
  };

  return (
    <ComponentPlayground
      previewWidth='auto'
      controls={
        <PlaygroundControlsFromSchema
          platform={platform}
          value={value}
          controls={avatarPlaygroundControls}
          onChange={update}
        />
      }
    >
      {renderAvatar(value, update)}
    </ComponentPlayground>
  );
}
