// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

'use client';

import { Avatar } from '@vellira-ui/react';

export function AvatarCatalogPreview() {
  return <Avatar />;
}
