// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

'use client';

import { Avatar as ReactAvatar } from '@vellira-ui/react';
import { Avatar as NativeAvatar } from '@vellira-ui/react-native';

import { ComponentExamples } from '../../shared/ComponentExamples';
import type { ComponentPlatform } from '../../types';

type AvatarExamplesProps = {
  platform: ComponentPlatform;
};

export function AvatarExamples({ platform }: AvatarExamplesProps) {
  const reactExamples = [
    {
      title: 'Fallback avatar',
      description:
        'A named fallback remains visible when an image source is not supplied.',
      preview: <ReactAvatar />,
      code: `import { Avatar } from '@vellira-ui/react';

<Avatar/>`,
    },
    {
      title: 'Large avatar',
      description:
        'Use the large size where the identity marker needs more emphasis.',
      preview: <ReactAvatar size='lg' />,
      code: `import { Avatar } from '@vellira-ui/react';

<Avatar
  size='lg'
/>`,
    },
  ] as const;

  const nativeExamples = [
    {
      title: 'Fallback avatar',
      description:
        'A named fallback remains visible when an image source is not supplied.',
      preview: <NativeAvatar />,
      code: `import { Avatar } from '@vellira-ui/react-native';

<Avatar/>`,
    },
    {
      title: 'Large avatar',
      description:
        'Use the large size where the identity marker needs more emphasis.',
      preview: <NativeAvatar size='lg' />,
      code: `import { Avatar } from '@vellira-ui/react-native';

<Avatar
  size='lg'
/>`,
    },
  ] as const;

  return (
    <ComponentExamples
      items={platform === 'react' ? reactExamples : nativeExamples}
    />
  );
}
