// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

import type { PlaygroundControl } from '../../shared/PlaygroundControls';

import type { AvatarPlaygroundValue } from './AvatarPlayground';

export const avatarPlaygroundControls = [
  {
    type: 'text',
    key: 'fallback',
    label: 'Fallback',
  },
  {
    type: 'text',
    key: 'name',
    label: 'Name',
  },
  {
    type: 'select',
    key: 'size',
    label: 'Size',
    options: ['sm', 'md', 'lg'],
  },
  {
    type: 'text',
    key: 'source',
    label: 'Source',
  },
] as const satisfies readonly PlaygroundControl<AvatarPlaygroundValue>[];
