// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

'use client';

import type { ComponentPlatform } from '../../types';

import { ComponentAccessibility } from '../../shared/ComponentAccessibility';

type AvatarAccessibilityProps = {
  platform: ComponentPlatform;
};

export function AvatarAccessibility({ platform }: AvatarAccessibilityProps) {
  const reactItems = [
    {
      title: 'Accessible name',
      description:
        'The avatar exposes an image role with the name prop as its accessible name. Its visual fallback and nested image are not announced separately.',
      props: ['name'],
    },
  ] as const;

  const nativeItems = [
    {
      title: 'Accessible name',
      description:
        'The native avatar is announced as one image using the name prop. Nested fallback content and the loaded image remain decorative.',
      props: ['name'],
    },
  ] as const;

  return (
    <ComponentAccessibility
      items={platform === 'react' ? reactItems : nativeItems}
    />
  );
}
