// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

import type {
  ComponentApiProp,
  ComponentApiSection,
} from '../../shared/ComponentApi';

const reactAvatarApiSections: readonly ComponentApiSection[] = [
  {
    name: 'Avatar',
    props: [
      {
        name: 'fallback',
        type: 'string',
        defaultValue: "'JD'",
        description:
          'Text shown when no image is available and while the supplied image is loading or has failed.',
        required: true,
      },
      {
        name: 'name',
        type: 'string',
        defaultValue: "'Jordan Diaz'",
        description:
          'Human-readable name announced to assistive technologies for the avatar.',
        required: true,
      },
      {
        name: 'size',
        type: "'sm' | 'md' | 'lg'",
        defaultValue: "'md'",
        description:
          'Controls the avatar geometry using the small, medium, or large size variant.',
      },
      {
        name: 'source',
        type: 'string',
        description:
          'Optional image source. Changing it starts a new image lifecycle and restores the fallback until the new image loads.',
      },
    ],
  },
];

const nativeAvatarApiSections: readonly ComponentApiSection[] = [
  {
    name: 'Avatar',
    props: [
      {
        name: 'fallback',
        type: 'string',
        defaultValue: "'JD'",
        description:
          'Text shown when no image is available and while the supplied image is loading or has failed.',
        required: true,
      },
      {
        name: 'name',
        type: 'string',
        defaultValue: "'Jordan Diaz'",
        description:
          'Human-readable name announced to assistive technologies for the avatar.',
        required: true,
      },
      {
        name: 'size',
        type: "'sm' | 'md' | 'lg'",
        defaultValue: "'md'",
        description:
          'Controls the avatar geometry using the small, medium, or large size variant.',
      },
      {
        name: 'source',
        type: 'string | number',
        description:
          'Optional image source. Changing it starts a new image lifecycle and restores the fallback until the new image loads.',
      },
    ],
  },
];

const inheritedReactAvatarApi: readonly ComponentApiProp[] = [];

const inheritedNativeAvatarApi: readonly ComponentApiProp[] = [];

export const avatarApi = {
  react: {
    sections: reactAvatarApiSections,
    inheritedProps: inheritedReactAvatarApi,
  },
  'react-native': {
    sections: nativeAvatarApiSections,
    inheritedProps: inheritedNativeAvatarApi,
  },
} as const;
