// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

'use client';

import type { ComponentPlatform } from '../../types';

import { ComponentCodeBlock } from '../../shared/ComponentCodeBlock';
import { useComponentDemoState } from '../../shared/ComponentDemoStateProvider';

import {
  initialAvatarPlaygroundValue,
  type AvatarPlaygroundValue,
} from './AvatarPlayground';

import styles from '../../shared/ComponentUsage.module.css';

type AvatarUsageProps = {
  platform: ComponentPlatform;
};

function createAvatarCode(
  platform: ComponentPlatform,
  value: AvatarPlaygroundValue
) {
  const packageName =
    platform === 'react' ? '@vellira-ui/react' : '@vellira-ui/react-native';

  const props: string[] = platform === 'react' ? [] : [];

  const children = platform === 'react' ? `` : ``;

  if (value.fallback) {
    props.push(`fallback='${value.fallback}'`);
  }

  if (value.name) {
    props.push(`name='${value.name}'`);
  }

  if (value.size !== 'sm') {
    props.push(`size='${value.size}'`);
  }

  if (value.source) {
    props.push(`source='${value.source}'`);
  }

  const propsText = props.length === 0 ? '' : `\n  ${props.join('\n  ')}\n`;

  if (!children) {
    return `import { Avatar } from '${packageName}';
${platform === 'react' ? `` : ``}

<Avatar${propsText}/>`;
  }

  return `import { Avatar } from '${packageName}';
${platform === 'react' ? `` : ``}

<Avatar${propsText}>
${children}
</Avatar>`;
}

export function AvatarUsage({ platform }: AvatarUsageProps) {
  const [value] = useComponentDemoState<AvatarPlaygroundValue>(
    initialAvatarPlaygroundValue
  );

  const code = createAvatarCode(platform, value);

  return (
    <section className={styles.root}>
      <div className={styles.header}>
        <h2 className={styles.title}>Usage</h2>

        <p className={styles.description}>
          Import the component and configure it with the same props used in the
          playground.
        </p>
      </div>

      <ComponentCodeBlock code={code} />
    </section>
  );
}
