// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

'use client';

import { Avatar } from '@vellira-ui/react-native';

import { AvatarPlayground } from './AvatarPlayground';

export function NativeAvatarDemo() {
  return (
    <AvatarPlayground
      platform='react-native'
      renderAvatar={(value) => (
        <Avatar
          fallback={value.fallback}
          name={value.name}
          size={value.size}
          source={value.source || undefined}
        />
      )}
    />
  );
}
