import path from 'node:path';

import { slugify } from './format';

export const generatedFileHeader = `// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

`;

export function getCatalogPaths(params: {
  root: string;
  componentName: string;
}) {
  const { root, componentName } = params;
  const catalogRoot = path.join(
    root,
    'apps',
    'website',
    'src',
    'component-catalog'
  );
  const catalogComponentsRoot = path.join(catalogRoot, 'components');
  const catalogRegistryFile = path.join(
    catalogRoot,
    'registry',
    'componentPages.ts'
  );
  const componentsRegistryFile = path.join(
    catalogRoot,
    'registry',
    'components.ts'
  );
  const generatedCatalogPreviewsFile = path.join(
    catalogRoot,
    'registry',
    'generatedCatalogPreviews.ts'
  );
  const componentCatalogDir = path.join(catalogComponentsRoot, componentName);
  const slug = slugify(componentName);

  return {
    catalogRoot,
    catalogComponentsRoot,
    catalogRegistryFile,
    componentsRegistryFile,
    generatedCatalogPreviewsFile,
    componentCatalogDir,
    slug,
  };
}

export function getVelliraApiSourceRoots(root: string) {
  return [
    path.join(root, 'packages', 'types', 'src'),
    path.join(root, 'packages', 'types', 'dist'),
    path.join(root, 'packages', 'react', 'src'),
    path.join(root, 'packages', 'react', 'dist'),
    path.join(root, 'packages', 'react-native', 'src'),
    path.join(root, 'packages', 'react-native', 'dist'),
  ].map((sourceRoot) => path.normalize(sourceRoot));
}
