// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

'use client';

import { Dropdown as ReactDropdown } from '@vellira-ui/react';
import { Dropdown as NativeDropdown } from '@vellira-ui/react-native';
import { ChevronDown } from '@vellira-ui/icons';
import { Button as ReactButton } from '@vellira-ui/react';
import { Button as NativeButton } from '@vellira-ui/react-native';
import { Download, Settings } from '@vellira-ui/icons';

import { ComponentExamples } from '../../shared/ComponentExamples';
import type { ComponentPlatform } from '../../types';

type DropdownExamplesProps = {
  platform: ComponentPlatform;
};

export function DropdownExamples({ platform }: DropdownExamplesProps) {
  const reactExamples = [
    {
      title: 'Basic',
      description: 'Action menu with common items.',
      preview: (
        <ReactDropdown>
          <ReactDropdown.Trigger asChild>
            <ReactButton
              appearance='outline'
              color='neutral'
              iconEnd={<ChevronDown />}
            >
              Actions
            </ReactButton>
          </ReactDropdown.Trigger>
          <ReactDropdown.Content>
            <ReactDropdown.Item>Profile</ReactDropdown.Item>
            <ReactDropdown.Item>Settings</ReactDropdown.Item>
            <ReactDropdown.Separator />
            <ReactDropdown.Item color='danger'>Sign out</ReactDropdown.Item>
          </ReactDropdown.Content>
        </ReactDropdown>
      ),
      code: `import { Dropdown } from '@vellira-ui/react';
import { ChevronDown } from '@vellira-ui/icons';
import { Button as ReactButton } from '@vellira-ui/react';

<Dropdown>
  <Dropdown.Trigger asChild>
    <ReactButton appearance='outline' color='neutral' iconEnd={<ChevronDown />}>Actions</ReactButton>
  </Dropdown.Trigger>
  <Dropdown.Content>
    <Dropdown.Item>Profile</Dropdown.Item>
    <Dropdown.Item>Settings</Dropdown.Item>
    <Dropdown.Separator />
    <Dropdown.Item color='danger'>Sign out</Dropdown.Item>
  </Dropdown.Content>
</Dropdown>`,
    },
    {
      title: 'Groups and separators',
      description: 'Organizes related actions with labels and dividers.',
      preview: (
        <ReactDropdown>
          <ReactDropdown.Trigger asChild>
            <ReactButton
              appearance='outline'
              color='neutral'
              iconEnd={<ChevronDown />}
            >
              Actions
            </ReactButton>
          </ReactDropdown.Trigger>
          <ReactDropdown.Content>
            <ReactDropdown.Group>
              <ReactDropdown.Label>Account</ReactDropdown.Label>
              <ReactDropdown.Item>Profile</ReactDropdown.Item>
              <ReactDropdown.Item>Settings</ReactDropdown.Item>
            </ReactDropdown.Group>
            <ReactDropdown.Separator />
            <ReactDropdown.Item color='danger'>Sign out</ReactDropdown.Item>
          </ReactDropdown.Content>
        </ReactDropdown>
      ),
      code: `import { Dropdown } from '@vellira-ui/react';
import { ChevronDown } from '@vellira-ui/icons';
import { Button as ReactButton } from '@vellira-ui/react';

<Dropdown>
  <Dropdown.Trigger asChild>
    <ReactButton appearance='outline' color='neutral' iconEnd={<ChevronDown />}>Actions</ReactButton>
  </Dropdown.Trigger>
  <Dropdown.Content>
    <Dropdown.Group>
      <Dropdown.Label>Account</Dropdown.Label>
      <Dropdown.Item>Profile</Dropdown.Item>
      <Dropdown.Item>Settings</Dropdown.Item>
    </Dropdown.Group>
    <Dropdown.Separator />
    <Dropdown.Item color='danger'>Sign out</Dropdown.Item>
  </Dropdown.Content>
</Dropdown>`,
    },
    {
      title: 'Item adornments',
      description: 'Adds icons, badges, and shortcuts to clarify actions.',
      preview: (
        <ReactDropdown>
          <ReactDropdown.Trigger asChild>
            <ReactButton
              appearance='outline'
              color='neutral'
              iconEnd={<ChevronDown />}
            >
              Actions
            </ReactButton>
          </ReactDropdown.Trigger>
          <ReactDropdown.Content>
            <ReactDropdown.Item icon={<Settings />} shortcut='Cmd+,'>
              Settings
            </ReactDropdown.Item>
            <ReactDropdown.Item
              icon={<Download />}
              badge='New'
              shortcut='Cmd+D'
            >
              Download
            </ReactDropdown.Item>
            <ReactDropdown.Item disabled>Unavailable</ReactDropdown.Item>
          </ReactDropdown.Content>
        </ReactDropdown>
      ),
      code: `import { Dropdown } from '@vellira-ui/react';
import { ChevronDown } from '@vellira-ui/icons';
import { Button as ReactButton } from '@vellira-ui/react';
import { Download, Settings } from '@vellira-ui/icons';

<Dropdown>
  <Dropdown.Trigger asChild>
    <ReactButton appearance='outline' color='neutral' iconEnd={<ChevronDown />}>Actions</ReactButton>
  </Dropdown.Trigger>
  <Dropdown.Content>
    <Dropdown.Item icon={<Settings />} shortcut='Cmd+,'>Settings</Dropdown.Item>
    <Dropdown.Item icon={<Download />} badge='New' shortcut='Cmd+D'>Download</Dropdown.Item>
    <Dropdown.Item disabled>Unavailable</Dropdown.Item>
  </Dropdown.Content>
</Dropdown>`,
    },
    {
      title: 'Searchable',
      description: 'Filter menu items.',
      preview: (
        <ReactDropdown searchable>
          <ReactDropdown.Trigger asChild>
            <ReactButton
              appearance='outline'
              color='neutral'
              iconEnd={<ChevronDown />}
            >
              Actions
            </ReactButton>
          </ReactDropdown.Trigger>
          <ReactDropdown.Content>
            <ReactDropdown.Item>Profile</ReactDropdown.Item>
            <ReactDropdown.Item>Settings</ReactDropdown.Item>
            <ReactDropdown.Separator />
            <ReactDropdown.Item color='danger'>Sign out</ReactDropdown.Item>
          </ReactDropdown.Content>
        </ReactDropdown>
      ),
      code: `import { Dropdown } from '@vellira-ui/react';
import { ChevronDown } from '@vellira-ui/icons';
import { Button as ReactButton } from '@vellira-ui/react';

<Dropdown
  searchable
>
  <Dropdown.Trigger asChild>
    <ReactButton appearance='outline' color='neutral' iconEnd={<ChevronDown />}>Actions</ReactButton>
  </Dropdown.Trigger>
  <Dropdown.Content>
    <Dropdown.Item>Profile</Dropdown.Item>
    <Dropdown.Item>Settings</Dropdown.Item>
    <Dropdown.Separator />
    <Dropdown.Item color='danger'>Sign out</Dropdown.Item>
  </Dropdown.Content>
</Dropdown>`,
    },
    {
      title: 'Selectable items',
      description:
        'Uses checkbox and radio menu items for temporary preferences.',
      preview: (
        <ReactDropdown>
          <ReactDropdown.Trigger asChild>
            <ReactButton
              appearance='outline'
              color='neutral'
              iconEnd={<ChevronDown />}
            >
              View options
            </ReactButton>
          </ReactDropdown.Trigger>
          <ReactDropdown.Content>
            <ReactDropdown.CheckboxItem checked>
              Show archived
            </ReactDropdown.CheckboxItem>
            <ReactDropdown.Separator />
            <ReactDropdown.RadioGroup defaultValue='comfortable'>
              <ReactDropdown.RadioItem value='comfortable'>
                Comfortable
              </ReactDropdown.RadioItem>
              <ReactDropdown.RadioItem value='compact'>
                Compact
              </ReactDropdown.RadioItem>
            </ReactDropdown.RadioGroup>
          </ReactDropdown.Content>
        </ReactDropdown>
      ),
      code: `import { Dropdown } from '@vellira-ui/react';
import { ChevronDown } from '@vellira-ui/icons';
import { Button as ReactButton } from '@vellira-ui/react';

<Dropdown>
  <Dropdown.Trigger asChild>
    <ReactButton appearance='outline' color='neutral' iconEnd={<ChevronDown />}>View options</ReactButton>
  </Dropdown.Trigger>
  <Dropdown.Content>
    <Dropdown.CheckboxItem checked>Show archived</Dropdown.CheckboxItem>
    <Dropdown.Separator />
    <Dropdown.RadioGroup defaultValue='comfortable'>
      <Dropdown.RadioItem value='comfortable'>Comfortable</Dropdown.RadioItem>
      <Dropdown.RadioItem value='compact'>Compact</Dropdown.RadioItem>
    </Dropdown.RadioGroup>
  </Dropdown.Content>
</Dropdown>`,
    },
    {
      title: 'Nested React dropdown submenu',
      description:
        'Groups secondary actions under a nested React dropdown submenu.',
      preview: (
        <ReactDropdown>
          <ReactDropdown.Trigger asChild>
            <ReactButton
              appearance='outline'
              color='neutral'
              iconEnd={<ChevronDown />}
            >
              Export
            </ReactButton>
          </ReactDropdown.Trigger>
          <ReactDropdown.Content>
            <ReactDropdown.Item>Copy link</ReactDropdown.Item>
            <ReactDropdown.Sub>
              <ReactDropdown.SubTrigger>Download</ReactDropdown.SubTrigger>
              <ReactDropdown.SubContent>
                <ReactDropdown.Item>PDF</ReactDropdown.Item>
                <ReactDropdown.Item>CSV</ReactDropdown.Item>
              </ReactDropdown.SubContent>
            </ReactDropdown.Sub>
          </ReactDropdown.Content>
        </ReactDropdown>
      ),
      code: `import { Dropdown } from '@vellira-ui/react';
import { ChevronDown } from '@vellira-ui/icons';
import { Button as ReactButton } from '@vellira-ui/react';

<Dropdown>
  <Dropdown.Trigger asChild>
    <ReactButton appearance='outline' color='neutral' iconEnd={<ChevronDown />}>Export</ReactButton>
  </Dropdown.Trigger>
  <Dropdown.Content>
    <Dropdown.Item>Copy link</Dropdown.Item>
    <Dropdown.Sub>
      <Dropdown.SubTrigger>Download</Dropdown.SubTrigger>
      <Dropdown.SubContent>
        <Dropdown.Item>PDF</Dropdown.Item>
        <Dropdown.Item>CSV</Dropdown.Item>
      </Dropdown.SubContent>
    </Dropdown.Sub>
  </Dropdown.Content>
</Dropdown>`,
    },
    {
      title: 'Loading',
      description: 'Loading menu state.',
      preview: (
        <ReactDropdown loading>
          <ReactDropdown.Trigger asChild>
            <ReactButton
              appearance='outline'
              color='neutral'
              iconEnd={<ChevronDown />}
            >
              Actions
            </ReactButton>
          </ReactDropdown.Trigger>
          <ReactDropdown.Content>
            <ReactDropdown.Item>Profile</ReactDropdown.Item>
            <ReactDropdown.Item>Settings</ReactDropdown.Item>
            <ReactDropdown.Separator />
            <ReactDropdown.Item color='danger'>Sign out</ReactDropdown.Item>
          </ReactDropdown.Content>
        </ReactDropdown>
      ),
      code: `import { Dropdown } from '@vellira-ui/react';
import { ChevronDown } from '@vellira-ui/icons';
import { Button as ReactButton } from '@vellira-ui/react';

<Dropdown
  loading
>
  <Dropdown.Trigger asChild>
    <ReactButton appearance='outline' color='neutral' iconEnd={<ChevronDown />}>Actions</ReactButton>
  </Dropdown.Trigger>
  <Dropdown.Content>
    <Dropdown.Item>Profile</Dropdown.Item>
    <Dropdown.Item>Settings</Dropdown.Item>
    <Dropdown.Separator />
    <Dropdown.Item color='danger'>Sign out</Dropdown.Item>
  </Dropdown.Content>
</Dropdown>`,
    },
    {
      title: 'Disabled',
      description: 'Disabled trigger state.',
      preview: (
        <ReactDropdown disabled>
          <ReactDropdown.Trigger asChild>
            <ReactButton
              appearance='outline'
              color='neutral'
              iconEnd={<ChevronDown />}
            >
              Actions
            </ReactButton>
          </ReactDropdown.Trigger>
          <ReactDropdown.Content>
            <ReactDropdown.Item>Profile</ReactDropdown.Item>
            <ReactDropdown.Item>Settings</ReactDropdown.Item>
            <ReactDropdown.Separator />
            <ReactDropdown.Item color='danger'>Sign out</ReactDropdown.Item>
          </ReactDropdown.Content>
        </ReactDropdown>
      ),
      code: `import { Dropdown } from '@vellira-ui/react';
import { ChevronDown } from '@vellira-ui/icons';
import { Button as ReactButton } from '@vellira-ui/react';

<Dropdown
  disabled
>
  <Dropdown.Trigger asChild>
    <ReactButton appearance='outline' color='neutral' iconEnd={<ChevronDown />}>Actions</ReactButton>
  </Dropdown.Trigger>
  <Dropdown.Content>
    <Dropdown.Item>Profile</Dropdown.Item>
    <Dropdown.Item>Settings</Dropdown.Item>
    <Dropdown.Separator />
    <Dropdown.Item color='danger'>Sign out</Dropdown.Item>
  </Dropdown.Content>
</Dropdown>`,
    },
  ] as const;

  const nativeExamples = [
    {
      title: 'Basic',
      description: 'Action menu with common items.',
      preview: (
        <NativeDropdown>
          <NativeDropdown.Trigger asChild>
            <NativeButton
              appearance='outline'
              color='neutral'
              iconEnd={<ChevronDown />}
            >
              Actions
            </NativeButton>
          </NativeDropdown.Trigger>
          <NativeDropdown.Content>
            <NativeDropdown.Item value='profile'>Profile</NativeDropdown.Item>
            <NativeDropdown.Item value='settings'>Settings</NativeDropdown.Item>
            <NativeDropdown.Separator />
            <NativeDropdown.Item value='sign-out' color='danger'>
              Sign out
            </NativeDropdown.Item>
          </NativeDropdown.Content>
        </NativeDropdown>
      ),
      code: `import { Dropdown } from '@vellira-ui/react-native';
import { ChevronDown } from '@vellira-ui/icons';
import { Button as NativeButton } from '@vellira-ui/react-native';

<Dropdown>
  <Dropdown.Trigger asChild>
    <NativeButton appearance='outline' color='neutral' iconEnd={<ChevronDown />}>Actions</NativeButton>
  </Dropdown.Trigger>
  <Dropdown.Content>
    <Dropdown.Item value='profile'>Profile</Dropdown.Item>
    <Dropdown.Item value='settings'>Settings</Dropdown.Item>
    <Dropdown.Separator />
    <Dropdown.Item value='sign-out' color='danger'>Sign out</Dropdown.Item>
  </Dropdown.Content>
</Dropdown>`,
    },
    {
      title: 'Groups and separators',
      description: 'Organizes related actions with labels and dividers.',
      preview: (
        <NativeDropdown>
          <NativeDropdown.Trigger asChild>
            <NativeButton
              appearance='outline'
              color='neutral'
              iconEnd={<ChevronDown />}
            >
              Actions
            </NativeButton>
          </NativeDropdown.Trigger>
          <NativeDropdown.Content>
            <NativeDropdown.Group>Account</NativeDropdown.Group>
            <NativeDropdown.Item value='profile'>Profile</NativeDropdown.Item>
            <NativeDropdown.Item value='settings'>Settings</NativeDropdown.Item>
            <NativeDropdown.Separator />
            <NativeDropdown.Item value='sign-out' color='danger'>
              Sign out
            </NativeDropdown.Item>
          </NativeDropdown.Content>
        </NativeDropdown>
      ),
      code: `import { Dropdown } from '@vellira-ui/react-native';
import { ChevronDown } from '@vellira-ui/icons';
import { Button as NativeButton } from '@vellira-ui/react-native';

<Dropdown>
  <Dropdown.Trigger asChild>
    <NativeButton appearance='outline' color='neutral' iconEnd={<ChevronDown />}>Actions</NativeButton>
  </Dropdown.Trigger>
  <Dropdown.Content>
    <Dropdown.Group>Account</Dropdown.Group>
    <Dropdown.Item value='profile'>Profile</Dropdown.Item>
    <Dropdown.Item value='settings'>Settings</Dropdown.Item>
    <Dropdown.Separator />
    <Dropdown.Item value='sign-out' color='danger'>Sign out</Dropdown.Item>
  </Dropdown.Content>
</Dropdown>`,
    },
    {
      title: 'Item adornments',
      description: 'Adds icons, badges, and shortcuts to clarify actions.',
      preview: (
        <NativeDropdown>
          <NativeDropdown.Trigger asChild>
            <NativeButton
              appearance='outline'
              color='neutral'
              iconEnd={<ChevronDown />}
            >
              Actions
            </NativeButton>
          </NativeDropdown.Trigger>
          <NativeDropdown.Content>
            <NativeDropdown.Item value='settings' icon={<Settings />}>
              Settings
            </NativeDropdown.Item>
            <NativeDropdown.Item value='download' icon={<Download />}>
              Download
            </NativeDropdown.Item>
            <NativeDropdown.Item value='unavailable' disabled>
              Unavailable
            </NativeDropdown.Item>
          </NativeDropdown.Content>
        </NativeDropdown>
      ),
      code: `import { Dropdown } from '@vellira-ui/react-native';
import { ChevronDown } from '@vellira-ui/icons';
import { Button as NativeButton } from '@vellira-ui/react-native';
import { Download, Settings } from '@vellira-ui/icons';

<Dropdown>
  <Dropdown.Trigger asChild>
    <NativeButton appearance='outline' color='neutral' iconEnd={<ChevronDown />}>Actions</NativeButton>
  </Dropdown.Trigger>
  <Dropdown.Content>
    <Dropdown.Item value='settings' icon={<Settings />}>Settings</Dropdown.Item>
    <Dropdown.Item value='download' icon={<Download />}>Download</Dropdown.Item>
    <Dropdown.Item value='unavailable' disabled>Unavailable</Dropdown.Item>
  </Dropdown.Content>
</Dropdown>`,
    },
    {
      title: 'Searchable',
      description: 'Filter menu items.',
      preview: (
        <NativeDropdown searchable>
          <NativeDropdown.Trigger asChild>
            <NativeButton
              appearance='outline'
              color='neutral'
              iconEnd={<ChevronDown />}
            >
              Actions
            </NativeButton>
          </NativeDropdown.Trigger>
          <NativeDropdown.Content>
            <NativeDropdown.Item value='profile'>Profile</NativeDropdown.Item>
            <NativeDropdown.Item value='settings'>Settings</NativeDropdown.Item>
            <NativeDropdown.Separator />
            <NativeDropdown.Item value='sign-out' color='danger'>
              Sign out
            </NativeDropdown.Item>
          </NativeDropdown.Content>
        </NativeDropdown>
      ),
      code: `import { Dropdown } from '@vellira-ui/react-native';
import { ChevronDown } from '@vellira-ui/icons';
import { Button as NativeButton } from '@vellira-ui/react-native';

<Dropdown
  searchable
>
  <Dropdown.Trigger asChild>
    <NativeButton appearance='outline' color='neutral' iconEnd={<ChevronDown />}>Actions</NativeButton>
  </Dropdown.Trigger>
  <Dropdown.Content>
    <Dropdown.Item value='profile'>Profile</Dropdown.Item>
    <Dropdown.Item value='settings'>Settings</Dropdown.Item>
    <Dropdown.Separator />
    <Dropdown.Item value='sign-out' color='danger'>Sign out</Dropdown.Item>
  </Dropdown.Content>
</Dropdown>`,
    },
    {
      title: 'Loading',
      description: 'Loading menu state.',
      preview: (
        <NativeDropdown loading>
          <NativeDropdown.Trigger asChild>
            <NativeButton
              appearance='outline'
              color='neutral'
              iconEnd={<ChevronDown />}
            >
              Actions
            </NativeButton>
          </NativeDropdown.Trigger>
          <NativeDropdown.Content>
            <NativeDropdown.Item value='profile'>Profile</NativeDropdown.Item>
            <NativeDropdown.Item value='settings'>Settings</NativeDropdown.Item>
            <NativeDropdown.Separator />
            <NativeDropdown.Item value='sign-out' color='danger'>
              Sign out
            </NativeDropdown.Item>
          </NativeDropdown.Content>
        </NativeDropdown>
      ),
      code: `import { Dropdown } from '@vellira-ui/react-native';
import { ChevronDown } from '@vellira-ui/icons';
import { Button as NativeButton } from '@vellira-ui/react-native';

<Dropdown
  loading
>
  <Dropdown.Trigger asChild>
    <NativeButton appearance='outline' color='neutral' iconEnd={<ChevronDown />}>Actions</NativeButton>
  </Dropdown.Trigger>
  <Dropdown.Content>
    <Dropdown.Item value='profile'>Profile</Dropdown.Item>
    <Dropdown.Item value='settings'>Settings</Dropdown.Item>
    <Dropdown.Separator />
    <Dropdown.Item value='sign-out' color='danger'>Sign out</Dropdown.Item>
  </Dropdown.Content>
</Dropdown>`,
    },
    {
      title: 'Disabled',
      description: 'Disabled trigger state.',
      preview: (
        <NativeDropdown disabled>
          <NativeDropdown.Trigger asChild>
            <NativeButton
              appearance='outline'
              color='neutral'
              iconEnd={<ChevronDown />}
            >
              Actions
            </NativeButton>
          </NativeDropdown.Trigger>
          <NativeDropdown.Content>
            <NativeDropdown.Item value='profile'>Profile</NativeDropdown.Item>
            <NativeDropdown.Item value='settings'>Settings</NativeDropdown.Item>
            <NativeDropdown.Separator />
            <NativeDropdown.Item value='sign-out' color='danger'>
              Sign out
            </NativeDropdown.Item>
          </NativeDropdown.Content>
        </NativeDropdown>
      ),
      code: `import { Dropdown } from '@vellira-ui/react-native';
import { ChevronDown } from '@vellira-ui/icons';
import { Button as NativeButton } from '@vellira-ui/react-native';

<Dropdown
  disabled
>
  <Dropdown.Trigger asChild>
    <NativeButton appearance='outline' color='neutral' iconEnd={<ChevronDown />}>Actions</NativeButton>
  </Dropdown.Trigger>
  <Dropdown.Content>
    <Dropdown.Item value='profile'>Profile</Dropdown.Item>
    <Dropdown.Item value='settings'>Settings</Dropdown.Item>
    <Dropdown.Separator />
    <Dropdown.Item value='sign-out' color='danger'>Sign out</Dropdown.Item>
  </Dropdown.Content>
</Dropdown>`,
    },
  ] as const;

  return (
    <ComponentExamples
      items={platform === 'react' ? reactExamples : nativeExamples}
    />
  );
}
