// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

'use client';

import type { ComponentPlatform } from '../../types';

import { ComponentAccessibility } from '../../shared/ComponentAccessibility';

type DropdownAccessibilityProps = {
  platform: ComponentPlatform;
};

export function DropdownAccessibility({
  platform,
}: DropdownAccessibilityProps) {
  const reactItems = [
    {
      title: 'Trigger naming',
      description:
        'Use trigger content that clearly communicates the menu purpose.',
      props: ['children', 'aria-label'],
    },
    {
      title: 'Keyboard menu behavior',
      description:
        'Preserve arrow-key navigation, Escape dismissal, and focus return to the trigger.',
      props: ['loop', 'modal', 'open'],
    },
    {
      title: 'Nested menu navigation',
      description:
        'Use the web submenu slots for related secondary actions. ArrowRight opens the active submenu, ArrowLeft closes it, and the submenu trigger exposes menu and expanded state semantics.',
      props: ['Dropdown.Sub', 'Dropdown.SubTrigger', 'Dropdown.SubContent'],
    },
    {
      title: 'Item states',
      description:
        'Use disabled and color state to communicate unavailable or destructive actions.',
      props: ['disabled', 'color'],
    },
    {
      title: 'Selection patterns',
      description:
        'Use checkbox and radio items only when menu selections remain understandable from their labels.',
      props: ['checked', 'value', 'onValueChange'],
    },
  ] as const;

  const nativeItems = [
    {
      title: 'Trigger naming',
      description:
        'Provide visible trigger text or accessibilityLabel for the menu trigger.',
      props: ['label', 'accessibilityLabel'],
    },
    {
      title: 'Presentation semantics',
      description:
        'Choose sheet, modal, or popover presentation based on screen size and interaction context.',
      props: ['presentation', 'placement'],
    },
    {
      title: 'Selection state',
      description:
        'Keep selected, disabled, and loading state reflected in item labels and accessibility state.',
      props: ['disabled', 'loading', 'onSelect'],
    },
  ] as const;

  return (
    <ComponentAccessibility
      items={platform === 'react' ? reactItems : nativeItems}
    />
  );
}
