// `.open-next/worker.js` is generated by `opennextjs-cloudflare build`.
import handler from './.open-next/worker.js';

const RSC_CACHE_CONTROL =
  'private, no-cache, no-store, max-age=0, must-revalidate';
const RSC_CACHE_MIGRATION_COOKIE = '__Host-vellira-rsc-cache-v1';
const RSC_CACHE_MIGRATION_MAX_AGE = 60 * 60 * 24 * 365;

function isRscRequest(request) {
  if (request.method !== 'GET') return false;

  return (
    request.headers.get('rsc') === '1' ||
    request.headers.has('next-router-prefetch') ||
    request.headers.has('next-router-segment-prefetch')
  );
}

function isDocumentRequest(request) {
  if (request.method !== 'GET' || isRscRequest(request)) return false;

  const acceptsHtml = request.headers.get('accept')?.includes('text/html');
  return request.headers.get('sec-fetch-dest') === 'document' || acceptsHtml;
}

function hasCookie(request, name) {
  const cookieHeader = request.headers.get('cookie') ?? '';
  return cookieHeader
    .split(';')
    .some((cookie) => cookie.trim().startsWith(`${name}=`));
}

function cloneResponse(response, headers) {
  return new Response(response.body, {
    status: response.status,
    statusText: response.statusText,
    headers,
  });
}

export default {
  async fetch(request, env, ctx) {
    const response = await handler.fetch(request, env, ctx);

    // App Router RSC/segment-prefetch payloads contain build-specific JS/CSS
    // references. Let OpenNext keep its server-side incremental cache, but do
    // not let the browser persist those payloads across deployments.
    if (isRscRequest(request)) {
      const headers = new Headers(response.headers);
      headers.set('Cache-Control', RSC_CACHE_CONTROL);
      return cloneResponse(response, headers);
    }

    // Browsers that visited staging before this fix can already have old RSC
    // payloads in their HTTP cache. Clear that legacy cache exactly once on a
    // secure top-level document response, then keep a durable marker cookie.
    // Future RSC responses are protected by the no-store policy above.
    if (
      new URL(request.url).protocol === 'https:' &&
      isDocumentRequest(request) &&
      !hasCookie(request, RSC_CACHE_MIGRATION_COOKIE)
    ) {
      const headers = new Headers(response.headers);
      headers.set('Clear-Site-Data', '"cache"');
      headers.append(
        'Set-Cookie',
        `${RSC_CACHE_MIGRATION_COOKIE}=1; Path=/; Max-Age=${RSC_CACHE_MIGRATION_MAX_AGE}; HttpOnly; Secure; SameSite=Lax`
      );
      return cloneResponse(response, headers);
    }

    return response;
  },
};
