// `.open-next/worker.js` is generated by `opennextjs-cloudflare build`.
import handler from './.open-next/worker.js';

const RSC_CACHE_CONTROL =
  'private, no-cache, no-store, max-age=0, must-revalidate';
const RSC_CACHE_MIGRATION_COOKIE = '__Host-vellira-rsc-cache-v1';
const RSC_CACHE_MIGRATION_MAX_AGE = 60 * 60 * 24 * 365;

function isRscRequest(request) {
  if (request.method !== 'GET') return false;

  return (
    request.headers.get('rsc') === '1' ||
    request.headers.has('next-router-prefetch') ||
    request.headers.has('next-router-segment-prefetch')
  );
}

function isBrowserDocumentNavigation(request) {
  return (
    request.method === 'GET' &&
    !isRscRequest(request) &&
    request.headers.get('sec-fetch-dest') === 'document' &&
    request.headers.get('sec-fetch-mode') === 'navigate'
  );
}

function hasCookie(request, name) {
  const cookieHeader = request.headers.get('cookie') ?? '';
  return cookieHeader
    .split(';')
    .some((cookie) => cookie.trim().startsWith(`${name}=`));
}

function cloneResponse(response, headers) {
  return new Response(response.body, {
    status: response.status,
    statusText: response.statusText,
    headers,
  });
}

function cacheMigrationRedirect(request) {
  const headers = new Headers();
  headers.set('Location', request.url);
  headers.set('Cache-Control', RSC_CACHE_CONTROL);
  headers.set('Clear-Site-Data', '"cache"');
  headers.append(
    'Set-Cookie',
    `${RSC_CACHE_MIGRATION_COOKIE}=1; Path=/; Max-Age=${RSC_CACHE_MIGRATION_MAX_AGE}; HttpOnly; Secure; SameSite=Lax`
  );

  return new Response(null, {
    status: 307,
    headers,
  });
}

export default {
  async fetch(request, env, ctx) {
    // Existing visitors can already have build-specific RSC payloads in their
    // browser HTTP cache. Clear that legacy cache before rendering the app,
    // then redirect the browser back to the exact same URL. Set-Cookie is
    // processed before the redirect is followed, so the second request goes
    // straight to the real document without requiring a manual reload.
    // Restrict this migration to real browser navigations so crawlers and API
    // clients are never put behind a cookie-dependent redirect.
    if (
      new URL(request.url).protocol === 'https:' &&
      isBrowserDocumentNavigation(request) &&
      !hasCookie(request, RSC_CACHE_MIGRATION_COOKIE)
    ) {
      return cacheMigrationRedirect(request);
    }

    const response = await handler.fetch(request, env, ctx);

    // App Router RSC/segment-prefetch payloads contain build-specific JS/CSS
    // references. Let OpenNext keep its server-side incremental cache, but do
    // not let the browser persist those payloads across deployments.
    if (isRscRequest(request)) {
      const headers = new Headers(response.headers);
      headers.set('Cache-Control', RSC_CACHE_CONTROL);
      return cloneResponse(response, headers);
    }

    return response;
  },
};
