// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

import type {
  ComponentApiProp,
  ComponentApiSection,
} from '../../shared/ComponentApi';

const reactButtonApiSections: readonly ComponentApiSection[] = [
  {
    name: 'Button',
    props: [
      {
        name: 'children',
        type: 'ReactNode',
        description: 'Visible button content.',
      },
      {
        name: 'appearance',
        type: "'solid' | 'outline' | 'ghost' | 'soft' | 'link' | 'bare'",
        defaultValue: "'solid'",
        description:
          'Visual appearance. `bare` preserves Button behavior while composition owns chrome and geometry.',
      },
      {
        name: 'iconStart',
        type: 'ReactNode',
        description: 'Icon rendered before the button content.',
      },
      {
        name: 'iconEnd',
        type: 'ReactNode',
        description: 'Icon rendered after the button content.',
      },
      {
        name: 'spinner',
        type: 'ReactNode',
        description: 'Custom loading indicator rendered while loading.',
      },
      {
        name: 'tooltip',
        type: 'string',
        description:
          'HTML title tooltip text for the button or composed child.',
      },
      {
        name: 'badge',
        type: 'ReactNode',
        description:
          'Compact badge rendered after the label when not icon-only.',
      },
      {
        name: 'shortcut',
        type: 'ReactNode',
        description:
          'Keyboard shortcut hint rendered after the label when not icon-only.',
      },
      {
        name: 'asChild',
        type: 'boolean',
        defaultValue: 'false',
        description:
          'Composes Button behavior and styling onto a single child element.',
      },
      {
        name: 'color',
        type: "'primary' | 'neutral' | 'success' | 'warning' | 'danger'",
        defaultValue: "'primary'",
        description: 'Visual tone for the button action.',
      },
      {
        name: 'size',
        type: "'sm' | 'md' | 'lg'",
        defaultValue: "'md'",
        description: 'Controls button height, padding, and typography scale.',
      },
      {
        name: 'shape',
        type: "'square' | 'rounded' | 'pill'",
        defaultValue: "'pill'",
        description: 'Corner shape for the button.',
      },
      {
        name: 'fullWidth',
        type: 'boolean',
        defaultValue: 'false',
        description: 'Makes the button fill its container width.',
      },
      {
        name: 'loading',
        type: 'boolean',
        defaultValue: 'false',
        description: 'Shows a loading indicator and disables interaction.',
      },
      {
        name: 'loadingText',
        type: 'string',
        description: 'Replaces visible content while loading.',
      },
      {
        name: 'disabled',
        type: 'boolean',
        defaultValue: 'false',
        description: 'Disables interaction and applies disabled styling.',
      },
      {
        name: 'iconOnly',
        type: 'boolean',
        defaultValue: 'false',
        description: 'Renders the button as an icon-only action.',
      },
    ],
  },
];

const nativeButtonApiSections: readonly ComponentApiSection[] = [
  {
    name: 'Button',
    props: [
      {
        name: 'children',
        type: 'ReactNode',
        description: 'Visible button content.',
      },
      {
        name: 'iconStart',
        type: 'ButtonIconElement',
        description: 'Icon rendered before the button content.',
      },
      {
        name: 'iconEnd',
        type: 'ButtonIconElement',
        description: 'Icon rendered after the button content.',
      },
      {
        name: 'badge',
        type: 'ReactNode',
        description:
          'Compact badge rendered after the label when not icon-only.',
      },
      {
        name: 'shortcut',
        type: 'ReactNode',
        description:
          'Keyboard shortcut hint rendered after the label when not icon-only.',
      },
      {
        name: 'iconSize',
        type: 'number',
        description: 'Overrides the size-derived icon size in pixels.',
      },
      {
        name: 'onPress',
        type: '((event: GestureResponderEvent) => void)',
        description: 'Called when the user presses the button.',
      },
      {
        name: 'style',
        type: 'StyleProp<ViewStyle>',
        description: 'Extra root style.',
      },
      {
        name: 'textStyle',
        type: 'StyleProp<TextStyle>',
        description: 'Extra text style.',
      },
      {
        name: 'accessibilityLabel',
        type: 'string',
        description: 'Accessible label for screen readers.',
      },
      {
        name: 'testID',
        type: 'string',
        description: 'Test identifier.',
      },
      {
        name: 'color',
        type: "'primary' | 'neutral' | 'success' | 'warning' | 'danger'",
        defaultValue: "'primary'",
        description: 'Visual tone for the button action.',
      },
      {
        name: 'appearance',
        type: "'solid' | 'outline' | 'ghost' | 'soft' | 'link'",
        defaultValue: "'solid'",
        description: 'Visual style for the button surface.',
      },
      {
        name: 'size',
        type: "'sm' | 'md' | 'lg'",
        defaultValue: "'md'",
        description: 'Controls button height, padding, and typography scale.',
      },
      {
        name: 'shape',
        type: "'square' | 'rounded' | 'pill'",
        defaultValue: "'pill'",
        description: 'Corner shape for the button.',
      },
      {
        name: 'fullWidth',
        type: 'boolean',
        defaultValue: 'false',
        description: 'Makes the button fill its container width.',
      },
      {
        name: 'loading',
        type: 'boolean',
        defaultValue: 'false',
        description: 'Shows a loading indicator and disables interaction.',
      },
      {
        name: 'loadingText',
        type: 'string',
        description: 'Replaces visible content while loading.',
      },
      {
        name: 'disabled',
        type: 'boolean',
        defaultValue: 'false',
        description: 'Disables interaction and applies disabled styling.',
      },
      {
        name: 'iconOnly',
        type: 'boolean',
        defaultValue: 'false',
        description: 'Renders the button as an icon-only action.',
      },
    ],
  },
];

const inheritedReactButtonApi: readonly ComponentApiProp[] = [
  {
    name: 'form',
    type: 'string',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'formAction',
    type: 'string | ((formData: FormData) => void | Promise<void>)',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'formEncType',
    type: 'string',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'formMethod',
    type: 'string',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'formNoValidate',
    type: 'boolean',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'formTarget',
    type: 'string',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'name',
    type: 'string',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'type',
    type: "'submit' | 'reset' | 'button'",
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'value',
    type: 'string | number | readonly string[]',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'defaultChecked',
    type: 'boolean',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'defaultValue',
    type: 'string | number | readonly string[]',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'suppressContentEditableWarning',
    type: 'boolean',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'suppressHydrationWarning',
    type: 'boolean',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'accessKey',
    type: 'string',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'autoCapitalize',
    type: '"off" | "none" | "on" | "sentences" | "words" | "characters" | (string & {})',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'autoFocus',
    type: 'boolean',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'className',
    type: 'string',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'contentEditable',
    type: 'Booleanish | "inherit" | "plaintext-only"',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'contextMenu',
    type: 'string',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'dir',
    type: 'string',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'draggable',
    type: 'Booleanish',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'enterKeyHint',
    type: "'enter' | 'done' | 'go' | 'next' | 'previous' | 'search' | 'send'",
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'hidden',
    type: 'boolean',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'id',
    type: 'string',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'lang',
    type: 'string',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'nonce',
    type: 'string',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'slot',
    type: 'string',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'spellCheck',
    type: 'Booleanish',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'style',
    type: 'CSSProperties',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'tabIndex',
    type: 'number',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'title',
    type: 'string',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'translate',
    type: "'yes' | 'no'",
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'radioGroup',
    type: 'string',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'role',
    type: 'AriaRole',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'about',
    type: 'string',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'content',
    type: 'string',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'datatype',
    type: 'string',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'inlist',
    type: 'any',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'prefix',
    type: 'string',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'property',
    type: 'string',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'rel',
    type: 'string',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'resource',
    type: 'string',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'rev',
    type: 'string',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'typeof',
    type: 'string',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'vocab',
    type: 'string',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'autoCorrect',
    type: 'string',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'autoSave',
    type: 'string',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'itemProp',
    type: 'string',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'itemScope',
    type: 'boolean',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'itemType',
    type: 'string',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'itemID',
    type: 'string',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'itemRef',
    type: 'string',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'results',
    type: 'number',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'security',
    type: 'string',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'unselectable',
    type: "'off' | 'on'",
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'popover',
    type: "'' | 'auto' | 'manual' | 'hint'",
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'popoverTargetAction',
    type: "'toggle' | 'show' | 'hide'",
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'popoverTarget',
    type: 'string',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'inert',
    type: 'boolean',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'inputMode',
    type: "'none' | 'search' | 'text' | 'tel' | 'url' | 'email' | 'numeric' | 'decimal'",
    description:
      'Hints at the type of data that might be entered by the user while editing the element or its contents',
  },
  {
    name: 'is',
    type: 'string',
    description:
      'Specify that a standard HTML element should behave like a defined custom built-in element',
  },
  {
    name: 'exportparts',
    type: 'string',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'part',
    type: 'string',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'aria-activedescendant',
    type: 'string',
    description:
      'Identifies the currently active element when DOM focus is on a composite widget, textbox, group, or application.',
  },
  {
    name: 'aria-atomic',
    type: 'Booleanish',
    description:
      'Indicates whether assistive technologies will present all, or only parts of, the changed region based on the change notifications defined by the aria-relevant attribute.',
  },
  {
    name: 'aria-autocomplete',
    type: "'none' | 'list' | 'inline' | 'both'",
    description:
      "Indicates whether inputting text could trigger display of one or more predictions of the user's intended value for an input and specifies how predictions would be\npresented if they are made.",
  },
  {
    name: 'aria-braillelabel',
    type: 'string',
    description:
      'Defines a string value that labels the current element, which is intended to be converted into Braille.',
  },
  {
    name: 'aria-brailleroledescription',
    type: 'string',
    description:
      'Defines a human-readable, author-localized abbreviated description for the role of an element, which is intended to be converted into Braille.',
  },
  {
    name: 'aria-busy',
    type: 'Booleanish',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'aria-checked',
    type: 'boolean | "true" | "false" | "mixed"',
    description:
      'Indicates the current "checked" state of checkboxes, radio buttons, and other widgets.',
  },
  {
    name: 'aria-colcount',
    type: 'number',
    description:
      'Defines the total number of columns in a table, grid, or treegrid.',
  },
  {
    name: 'aria-colindex',
    type: 'number',
    description:
      "Defines an element's column index or position with respect to the total number of columns within a table, grid, or treegrid.",
  },
  {
    name: 'aria-colindextext',
    type: 'string',
    description: 'Defines a human readable text alternative of aria-colindex.',
  },
  {
    name: 'aria-colspan',
    type: 'number',
    description:
      'Defines the number of columns spanned by a cell or gridcell within a table, grid, or treegrid.',
  },
  {
    name: 'aria-controls',
    type: 'string',
    description:
      'Identifies the element (or elements) whose contents or presence are controlled by the current element.',
  },
  {
    name: 'aria-current',
    type: 'boolean | "true" | "false" | "page" | "step" | "location" | "date" | "time"',
    description:
      'Indicates the element that represents the current item within a container or set of related elements.',
  },
  {
    name: 'aria-describedby',
    type: 'string',
    description:
      'Identifies the element (or elements) that describes the object.',
  },
  {
    name: 'aria-description',
    type: 'string',
    description:
      'Defines a string value that describes or annotates the current element.',
  },
  {
    name: 'aria-details',
    type: 'string',
    description:
      'Identifies the element that provides a detailed, extended description for the object.',
  },
  {
    name: 'aria-disabled',
    type: 'Booleanish',
    description:
      'Indicates that the element is perceivable but disabled, so it is not editable or otherwise operable.',
  },
  {
    name: 'aria-dropeffect',
    type: "'link' | 'none' | 'copy' | 'execute' | 'move' | 'popup'",
    description:
      'Indicates what functions can be performed when a dragged object is released on the drop target.',
  },
  {
    name: 'aria-errormessage',
    type: 'string',
    description:
      'Identifies the element that provides an error message for the object.',
  },
  {
    name: 'aria-expanded',
    type: 'Booleanish',
    description:
      'Indicates whether the element, or another grouping element it controls, is currently expanded or collapsed.',
  },
  {
    name: 'aria-flowto',
    type: 'string',
    description:
      "Identifies the next element (or elements) in an alternate reading order of content which, at the user's discretion,\nallows assistive technology to override the general default of reading in document source order.",
  },
  {
    name: 'aria-grabbed',
    type: 'Booleanish',
    description:
      'Indicates an element\'s "grabbed" state in a drag-and-drop operation.',
  },
  {
    name: 'aria-haspopup',
    type: 'boolean | "true" | "false" | "dialog" | "grid" | "listbox" | "menu" | "tree"',
    description:
      'Indicates the availability and type of interactive popup element, such as menu or dialog, that can be triggered by an element.',
  },
  {
    name: 'aria-hidden',
    type: 'Booleanish',
    description:
      'Indicates whether the element is exposed to an accessibility API.',
  },
  {
    name: 'aria-invalid',
    type: 'boolean | "true" | "false" | "grammar" | "spelling"',
    description:
      'Indicates the entered value does not conform to the format expected by the application.',
  },
  {
    name: 'aria-keyshortcuts',
    type: 'string',
    description:
      'Indicates keyboard shortcuts that an author has implemented to activate or give focus to an element.',
  },
  {
    name: 'aria-label',
    type: 'string',
    description: 'Defines a string value that labels the current element.',
  },
  {
    name: 'aria-labelledby',
    type: 'string',
    description:
      'Identifies the element (or elements) that labels the current element.',
  },
  {
    name: 'aria-level',
    type: 'number',
    description:
      'Defines the hierarchical level of an element within a structure.',
  },
  {
    name: 'aria-live',
    type: "'off' | 'assertive' | 'polite'",
    description:
      'Indicates that an element will be updated, and describes the types of updates the user agents, assistive technologies, and user can expect from the live region.',
  },
  {
    name: 'aria-modal',
    type: 'Booleanish',
    description: 'Indicates whether an element is modal when displayed.',
  },
  {
    name: 'aria-multiline',
    type: 'Booleanish',
    description:
      'Indicates whether a text box accepts multiple lines of input or only a single line.',
  },
  {
    name: 'aria-multiselectable',
    type: 'Booleanish',
    description:
      'Indicates that the user may select more than one item from the current selectable descendants.',
  },
  {
    name: 'aria-orientation',
    type: "'horizontal' | 'vertical'",
    description:
      "Indicates whether the element's orientation is horizontal, vertical, or unknown/ambiguous.",
  },
  {
    name: 'aria-owns',
    type: 'string',
    description:
      'Identifies an element (or elements) in order to define a visual, functional, or contextual parent/child relationship\nbetween DOM elements where the DOM hierarchy cannot be used to represent the relationship.',
  },
  {
    name: 'aria-placeholder',
    type: 'string',
    description:
      'Defines a short hint (a word or short phrase) intended to aid the user with data entry when the control has no value.\nA hint could be a sample value or a brief description of the expected format.',
  },
  {
    name: 'aria-posinset',
    type: 'number',
    description:
      "Defines an element's number or position in the current set of listitems or treeitems. Not required if all elements in the set are present in the DOM.",
  },
  {
    name: 'aria-pressed',
    type: 'boolean | "true" | "false" | "mixed"',
    description: 'Indicates the current "pressed" state of toggle buttons.',
  },
  {
    name: 'aria-readonly',
    type: 'Booleanish',
    description:
      'Indicates that the element is not editable, but is otherwise operable.',
  },
  {
    name: 'aria-relevant',
    type: "'text' | 'additions' | 'additions removals' | 'additions text' | 'all' | 'removals' | 'removals additions' | 'removals text' | 'text additions' | 'text removals'",
    description:
      'Indicates what notifications the user agent will trigger when the accessibility tree within a live region is modified.',
  },
  {
    name: 'aria-required',
    type: 'Booleanish',
    description:
      'Indicates that user input is required on the element before a form may be submitted.',
  },
  {
    name: 'aria-roledescription',
    type: 'string',
    description:
      'Defines a human-readable, author-localized description for the role of an element.',
  },
  {
    name: 'aria-rowcount',
    type: 'number',
    description:
      'Defines the total number of rows in a table, grid, or treegrid.',
  },
  {
    name: 'aria-rowindex',
    type: 'number',
    description:
      "Defines an element's row index or position with respect to the total number of rows within a table, grid, or treegrid.",
  },
  {
    name: 'aria-rowindextext',
    type: 'string',
    description: 'Defines a human readable text alternative of aria-rowindex.',
  },
  {
    name: 'aria-rowspan',
    type: 'number',
    description:
      'Defines the number of rows spanned by a cell or gridcell within a table, grid, or treegrid.',
  },
  {
    name: 'aria-selected',
    type: 'Booleanish',
    description: 'Indicates the current "selected" state of various widgets.',
  },
  {
    name: 'aria-setsize',
    type: 'number',
    description:
      'Defines the number of items in the current set of listitems or treeitems. Not required if all elements in the set are present in the DOM.',
  },
  {
    name: 'aria-sort',
    type: "'none' | 'ascending' | 'descending' | 'other'",
    description:
      'Indicates if items in a table or grid are sorted in ascending or descending order.',
  },
  {
    name: 'aria-valuemax',
    type: 'number',
    description: 'Defines the maximum allowed value for a range widget.',
  },
  {
    name: 'aria-valuemin',
    type: 'number',
    description: 'Defines the minimum allowed value for a range widget.',
  },
  {
    name: 'aria-valuenow',
    type: 'number',
    description: 'Defines the current value for a range widget.',
  },
  {
    name: 'aria-valuetext',
    type: 'string',
    description:
      'Defines the human readable text alternative of aria-valuenow for a range widget.',
  },
  {
    name: 'dangerouslySetInnerHTML',
    type: '{ __html: string | TrustedHTML; }',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onCopy',
    type: 'ClipboardEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onCopyCapture',
    type: 'ClipboardEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onCut',
    type: 'ClipboardEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onCutCapture',
    type: 'ClipboardEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onPaste',
    type: 'ClipboardEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onPasteCapture',
    type: 'ClipboardEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onCompositionEnd',
    type: 'CompositionEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onCompositionEndCapture',
    type: 'CompositionEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onCompositionStart',
    type: 'CompositionEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onCompositionStartCapture',
    type: 'CompositionEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onCompositionUpdate',
    type: 'CompositionEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onCompositionUpdateCapture',
    type: 'CompositionEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onFocus',
    type: 'FocusEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onFocusCapture',
    type: 'FocusEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onBlur',
    type: 'FocusEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onBlurCapture',
    type: 'FocusEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onChange',
    type: 'ChangeEventHandler<HTMLButtonElement, Element>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onChangeCapture',
    type: 'ChangeEventHandler<HTMLButtonElement, Element>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onBeforeInput',
    type: 'InputEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onBeforeInputCapture',
    type: 'InputEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onInput',
    type: 'InputEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onInputCapture',
    type: 'InputEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onReset',
    type: 'ReactEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onResetCapture',
    type: 'ReactEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onSubmit',
    type: 'SubmitEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onSubmitCapture',
    type: 'SubmitEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onInvalid',
    type: 'ReactEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onInvalidCapture',
    type: 'ReactEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onLoad',
    type: 'ReactEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onLoadCapture',
    type: 'ReactEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onError',
    type: 'ReactEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onErrorCapture',
    type: 'ReactEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onKeyDown',
    type: 'KeyboardEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onKeyDownCapture',
    type: 'KeyboardEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onKeyPress',
    type: 'KeyboardEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onKeyPressCapture',
    type: 'KeyboardEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onKeyUp',
    type: 'KeyboardEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onKeyUpCapture',
    type: 'KeyboardEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onAbort',
    type: 'ReactEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onAbortCapture',
    type: 'ReactEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onCanPlay',
    type: 'ReactEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onCanPlayCapture',
    type: 'ReactEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onCanPlayThrough',
    type: 'ReactEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onCanPlayThroughCapture',
    type: 'ReactEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onDurationChange',
    type: 'ReactEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onDurationChangeCapture',
    type: 'ReactEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onEmptied',
    type: 'ReactEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onEmptiedCapture',
    type: 'ReactEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onEncrypted',
    type: 'ReactEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onEncryptedCapture',
    type: 'ReactEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onEnded',
    type: 'ReactEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onEndedCapture',
    type: 'ReactEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onLoadedData',
    type: 'ReactEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onLoadedDataCapture',
    type: 'ReactEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onLoadedMetadata',
    type: 'ReactEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onLoadedMetadataCapture',
    type: 'ReactEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onLoadStart',
    type: 'ReactEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onLoadStartCapture',
    type: 'ReactEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onPause',
    type: 'ReactEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onPauseCapture',
    type: 'ReactEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onPlay',
    type: 'ReactEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onPlayCapture',
    type: 'ReactEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onPlaying',
    type: 'ReactEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onPlayingCapture',
    type: 'ReactEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onProgress',
    type: 'ReactEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onProgressCapture',
    type: 'ReactEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onRateChange',
    type: 'ReactEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onRateChangeCapture',
    type: 'ReactEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onSeeked',
    type: 'ReactEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onSeekedCapture',
    type: 'ReactEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onSeeking',
    type: 'ReactEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onSeekingCapture',
    type: 'ReactEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onStalled',
    type: 'ReactEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onStalledCapture',
    type: 'ReactEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onSuspend',
    type: 'ReactEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onSuspendCapture',
    type: 'ReactEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onTimeUpdate',
    type: 'ReactEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onTimeUpdateCapture',
    type: 'ReactEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onVolumeChange',
    type: 'ReactEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onVolumeChangeCapture',
    type: 'ReactEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onWaiting',
    type: 'ReactEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onWaitingCapture',
    type: 'ReactEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onAuxClick',
    type: 'MouseEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onAuxClickCapture',
    type: 'MouseEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onClick',
    type: 'MouseEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onClickCapture',
    type: 'MouseEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onContextMenu',
    type: 'MouseEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onContextMenuCapture',
    type: 'MouseEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onDoubleClick',
    type: 'MouseEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onDoubleClickCapture',
    type: 'MouseEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onDrag',
    type: 'DragEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onDragCapture',
    type: 'DragEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onDragEnd',
    type: 'DragEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onDragEndCapture',
    type: 'DragEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onDragEnter',
    type: 'DragEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onDragEnterCapture',
    type: 'DragEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onDragExit',
    type: 'DragEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onDragExitCapture',
    type: 'DragEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onDragLeave',
    type: 'DragEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onDragLeaveCapture',
    type: 'DragEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onDragOver',
    type: 'DragEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onDragOverCapture',
    type: 'DragEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onDragStart',
    type: 'DragEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onDragStartCapture',
    type: 'DragEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onDrop',
    type: 'DragEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onDropCapture',
    type: 'DragEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onMouseDown',
    type: 'MouseEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onMouseDownCapture',
    type: 'MouseEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onMouseEnter',
    type: 'MouseEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onMouseLeave',
    type: 'MouseEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onMouseMove',
    type: 'MouseEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onMouseMoveCapture',
    type: 'MouseEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onMouseOut',
    type: 'MouseEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onMouseOutCapture',
    type: 'MouseEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onMouseOver',
    type: 'MouseEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onMouseOverCapture',
    type: 'MouseEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onMouseUp',
    type: 'MouseEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onMouseUpCapture',
    type: 'MouseEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onSelect',
    type: 'ReactEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onSelectCapture',
    type: 'ReactEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onTouchCancel',
    type: 'TouchEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onTouchCancelCapture',
    type: 'TouchEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onTouchEnd',
    type: 'TouchEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onTouchEndCapture',
    type: 'TouchEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onTouchMove',
    type: 'TouchEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onTouchMoveCapture',
    type: 'TouchEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onTouchStart',
    type: 'TouchEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onTouchStartCapture',
    type: 'TouchEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onPointerDown',
    type: 'PointerEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onPointerDownCapture',
    type: 'PointerEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onPointerMove',
    type: 'PointerEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onPointerMoveCapture',
    type: 'PointerEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onPointerUp',
    type: 'PointerEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onPointerUpCapture',
    type: 'PointerEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onPointerCancel',
    type: 'PointerEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onPointerCancelCapture',
    type: 'PointerEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onPointerEnter',
    type: 'PointerEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onPointerLeave',
    type: 'PointerEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onPointerOver',
    type: 'PointerEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onPointerOverCapture',
    type: 'PointerEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onPointerOut',
    type: 'PointerEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onPointerOutCapture',
    type: 'PointerEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onGotPointerCapture',
    type: 'PointerEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onGotPointerCaptureCapture',
    type: 'PointerEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onLostPointerCapture',
    type: 'PointerEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onLostPointerCaptureCapture',
    type: 'PointerEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onScroll',
    type: 'UIEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onScrollCapture',
    type: 'UIEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onScrollEnd',
    type: 'UIEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onScrollEndCapture',
    type: 'UIEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onWheel',
    type: 'WheelEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onWheelCapture',
    type: 'WheelEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onAnimationStart',
    type: 'AnimationEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onAnimationStartCapture',
    type: 'AnimationEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onAnimationEnd',
    type: 'AnimationEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onAnimationEndCapture',
    type: 'AnimationEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onAnimationIteration',
    type: 'AnimationEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onAnimationIterationCapture',
    type: 'AnimationEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onToggle',
    type: 'ToggleEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onBeforeToggle',
    type: 'ToggleEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onTransitionCancel',
    type: 'TransitionEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onTransitionCancelCapture',
    type: 'TransitionEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onTransitionEnd',
    type: 'TransitionEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onTransitionEndCapture',
    type: 'TransitionEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onTransitionRun',
    type: 'TransitionEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onTransitionRunCapture',
    type: 'TransitionEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onTransitionStart',
    type: 'TransitionEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'onTransitionStartCapture',
    type: 'TransitionEventHandler<HTMLButtonElement>',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'href',
    type: 'string',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'target',
    type: 'HTMLAttributeAnchorTarget',
    description: 'Forwarded React DOM prop.',
  },
  {
    name: 'download',
    type: 'any',
    description: 'Forwarded React DOM prop.',
  },
];

const inheritedNativeButtonApi: readonly ComponentApiProp[] = [
  {
    name: 'hitSlop',
    type: 'number | Insets | null',
    description:
      'Additional distance outside of this view in which a press is detected.',
  },
  {
    name: 'id',
    type: 'string',
    description: 'Used to reference react managed views from native code.',
  },
  {
    name: 'needsOffscreenAlphaCompositing',
    type: 'boolean',
    description:
      "Whether this view needs to rendered offscreen and composited with an alpha in order to preserve 100% correct colors and blending behavior.\nThe default (false) falls back to drawing the component and its children\nwith an alpha applied to the paint used to draw each element instead of rendering the full component offscreen and compositing it back with an alpha value.\nThis default may be noticeable and undesired in the case where the View you are setting an opacity on\nhas multiple overlapping elements (e.g. multiple overlapping Views, or text and a background).\n\nRendering offscreen to preserve correct alpha behavior is extremely expensive\nand hard to debug for non-native developers, which is why it is not turned on by default.\nIf you do need to enable this property for an animation,\nconsider combining it with renderToHardwareTextureAndroid if the view contents are static (i.e. it doesn't need to be redrawn each frame).\nIf that property is enabled, this View will be rendered off-screen once,\nsaved in a hardware texture, and then composited onto the screen with an alpha each frame without having to switch rendering targets on the GPU.",
  },
  {
    name: 'onLayout',
    type: '((event: LayoutChangeEvent) => void)',
    description:
      'Invoked on mount and layout changes with\n\n{nativeEvent: { layout: {x, y, width, height}}}.',
  },
  {
    name: 'pointerEvents',
    type: "'box-none' | 'none' | 'box-only' | 'auto'",
    description:
      "\nIn the absence of auto property, none is much like CSS's none value. box-none is as if you had applied the CSS class:\n\n.box-none {\n  pointer-events: none;\n}\n.box-none * {\n  pointer-events: all;\n}\n\nbox-only is the equivalent of\n\n.box-only {\n  pointer-events: all;\n}\n.box-only * {\n  pointer-events: none;\n}\n\nBut since pointerEvents does not affect layout/appearance, and we are already deviating from the spec by adding additional modes,\nwe opt to not include pointerEvents on style. On some platforms, we would need to implement it as a className anyways. Using style or not is an implementation detail of the platform.",
  },
  {
    name: 'removeClippedSubviews',
    type: 'boolean',
    description:
      '\nThis is a special performance property exposed by RCTView and is useful for scrolling content when there are many subviews,\nmost of which are offscreen. For this property to be effective, it must be applied to a view that contains many subviews that extend outside its bound.\nThe subviews must also have overflow: hidden, as should the containing view (or one of its superviews).',
  },
  {
    name: 'nativeID',
    type: 'string',
    description: 'Used to reference react managed views from native code.',
  },
  {
    name: 'collapsable',
    type: 'boolean',
    description:
      "Views that are only used to layout their children or otherwise don't draw anything\nmay be automatically removed from the native hierarchy as an optimization.\nSet this property to false to disable this optimization and ensure that this View exists in the native view hierarchy.",
  },
  {
    name: 'collapsableChildren',
    type: 'boolean',
    description:
      'Setting to false prevents direct children of the view from being removed\nfrom the native view hierarchy, similar to the effect of setting\n`collapsable={false}` on each child.',
  },
  {
    name: 'onBlur',
    type: '((event: NativeSyntheticEvent<TargetedEvent>) => void) | null',
    description: 'Called after the element loses focus.',
  },
  {
    name: 'onFocus',
    type: '((event: NativeSyntheticEvent<TargetedEvent>) => void) | null',
    description: 'Called after the element is focused.',
  },
  {
    name: 'renderToHardwareTextureAndroid',
    type: 'boolean',
    description:
      "Whether this view should render itself (and all of its children) into a single hardware texture on the GPU.\n\nOn Android, this is useful for animations and interactions that only modify opacity, rotation, translation, and/or scale:\nin those cases, the view doesn't have to be redrawn and display lists don't need to be re-executed. The texture can just be\nre-used and re-composited with different parameters. The downside is that this can use up limited video memory, so this prop should be set back to false at the end of the interaction/animation.",
  },
  {
    name: 'focusable',
    type: 'boolean',
    description:
      'Whether this `View` should be focusable with a non-touch input device, eg. receive focus with a hardware keyboard.',
  },
  {
    name: 'tabIndex',
    type: '0 | -1',
    description:
      'Indicates whether this `View` should be focusable with a non-touch input device, eg. receive focus with a hardware keyboard.\nSee https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex\nfor more details.\n\nSupports the following values:\n-  0 (View is focusable)\n- -1 (View is not focusable)',
  },
  {
    name: 'shouldRasterizeIOS',
    type: 'boolean',
    description:
      "Whether this view should be rendered as a bitmap before compositing.\n\nOn iOS, this is useful for animations and interactions that do not modify this component's dimensions nor its children;\nfor example, when translating the position of a static view, rasterization allows the renderer to reuse a cached bitmap of a static view\nand quickly composite it during each frame.\n\nRasterization incurs an off-screen drawing pass and the bitmap consumes memory.\nTest and measure when using this property.",
  },
  {
    name: 'isTVSelectable',
    type: 'boolean',
    description:
      '*(Apple TV only)* When set to true, this view will be focusable\nand navigable using the Apple TV remote.',
  },
  {
    name: 'hasTVPreferredFocus',
    type: 'boolean',
    description:
      '*(Apple TV only)* May be set to true to force the Apple TV focus engine to move focus to this view.',
  },
  {
    name: 'tvParallaxShiftDistanceX',
    type: 'number',
    description:
      '*(Apple TV only)* May be used to change the appearance of the Apple TV parallax effect when this view goes in or out of focus.  Defaults to 2.0.',
  },
  {
    name: 'tvParallaxShiftDistanceY',
    type: 'number',
    description:
      '*(Apple TV only)* May be used to change the appearance of the Apple TV parallax effect when this view goes in or out of focus.  Defaults to 2.0.',
  },
  {
    name: 'tvParallaxTiltAngle',
    type: 'number',
    description:
      '*(Apple TV only)* May be used to change the appearance of the Apple TV parallax effect when this view goes in or out of focus.  Defaults to 0.05.',
  },
  {
    name: 'tvParallaxMagnification',
    type: 'number',
    description:
      '*(Apple TV only)* May be used to change the appearance of the Apple TV parallax effect when this view goes in or out of focus.  Defaults to 1.0.',
  },
  {
    name: 'onStartShouldSetResponder',
    type: '((event: GestureResponderEvent) => boolean)',
    description:
      'Does this view want to become responder on the start of a touch?',
  },
  {
    name: 'onMoveShouldSetResponder',
    type: '((event: GestureResponderEvent) => boolean)',
    description:
      'Called for every touch move on the View when it is not the responder: does this view want to "claim" touch responsiveness?',
  },
  {
    name: 'onResponderEnd',
    type: '((event: GestureResponderEvent) => void)',
    description:
      'If the View returns true and attempts to become the responder, one of the following will happen:',
  },
  {
    name: 'onResponderGrant',
    type: '((event: GestureResponderEvent) => void)',
    description:
      'The View is now responding for touch events.\nThis is the time to highlight and show the user what is happening',
  },
  {
    name: 'onResponderReject',
    type: '((event: GestureResponderEvent) => void)',
    description:
      'Something else is the responder right now and will not release it',
  },
  {
    name: 'onResponderMove',
    type: '((event: GestureResponderEvent) => void)',
    description: 'The user is moving their finger',
  },
  {
    name: 'onResponderRelease',
    type: '((event: GestureResponderEvent) => void)',
    description: 'Fired at the end of the touch, ie "touchUp"',
  },
  {
    name: 'onResponderStart',
    type: '((event: GestureResponderEvent) => void)',
    description: 'Forwarded React Native prop.',
  },
  {
    name: 'onResponderTerminationRequest',
    type: '((event: GestureResponderEvent) => boolean)',
    description:
      'Something else wants to become responder.\nShould this view release the responder? Returning true allows release',
  },
  {
    name: 'onResponderTerminate',
    type: '((event: GestureResponderEvent) => void)',
    description:
      'The responder has been taken from the View.\nMight be taken by other views after a call to onResponderTerminationRequest,\nor might be taken by the OS without asking (happens with control center/ notification center on iOS)',
  },
  {
    name: 'onStartShouldSetResponderCapture',
    type: '((event: GestureResponderEvent) => boolean)',
    description:
      'onStartShouldSetResponder and onMoveShouldSetResponder are called with a bubbling pattern,\nwhere the deepest node is called first.\nThat means that the deepest component will become responder when multiple Views return true for *ShouldSetResponder handlers.\nThis is desirable in most cases, because it makes sure all controls and buttons are usable.\n\nHowever, sometimes a parent will want to make sure that it becomes responder.\nThis can be handled by using the capture phase.\nBefore the responder system bubbles up from the deepest component,\nit will do a capture phase, firing on*ShouldSetResponderCapture.\nSo if a parent View wants to prevent the child from becoming responder on a touch start,\nit should have a onStartShouldSetResponderCapture handler which returns true.',
  },
  {
    name: 'onMoveShouldSetResponderCapture',
    type: '((event: GestureResponderEvent) => boolean)',
    description:
      'onStartShouldSetResponder and onMoveShouldSetResponder are called with a bubbling pattern,\nwhere the deepest node is called first.\nThat means that the deepest component will become responder when multiple Views return true for *ShouldSetResponder handlers.\nThis is desirable in most cases, because it makes sure all controls and buttons are usable.\n\nHowever, sometimes a parent will want to make sure that it becomes responder.\nThis can be handled by using the capture phase.\nBefore the responder system bubbles up from the deepest component,\nit will do a capture phase, firing on*ShouldSetResponderCapture.\nSo if a parent View wants to prevent the child from becoming responder on a touch start,\nit should have a onStartShouldSetResponderCapture handler which returns true.',
  },
  {
    name: 'onTouchStart',
    type: '((event: GestureResponderEvent) => void)',
    description: 'Forwarded React Native prop.',
  },
  {
    name: 'onTouchMove',
    type: '((event: GestureResponderEvent) => void)',
    description: 'Forwarded React Native prop.',
  },
  {
    name: 'onTouchEnd',
    type: '((event: GestureResponderEvent) => void)',
    description: 'Forwarded React Native prop.',
  },
  {
    name: 'onTouchCancel',
    type: '((event: GestureResponderEvent) => void)',
    description: 'Forwarded React Native prop.',
  },
  {
    name: 'onTouchEndCapture',
    type: '((event: GestureResponderEvent) => void)',
    description: 'Forwarded React Native prop.',
  },
  {
    name: 'onPointerEnter',
    type: '((event: PointerEvent) => void)',
    description: 'Forwarded React Native prop.',
  },
  {
    name: 'onPointerEnterCapture',
    type: '((event: PointerEvent) => void)',
    description: 'Forwarded React Native prop.',
  },
  {
    name: 'onPointerLeave',
    type: '((event: PointerEvent) => void)',
    description: 'Forwarded React Native prop.',
  },
  {
    name: 'onPointerLeaveCapture',
    type: '((event: PointerEvent) => void)',
    description: 'Forwarded React Native prop.',
  },
  {
    name: 'onPointerMove',
    type: '((event: PointerEvent) => void)',
    description: 'Forwarded React Native prop.',
  },
  {
    name: 'onPointerMoveCapture',
    type: '((event: PointerEvent) => void)',
    description: 'Forwarded React Native prop.',
  },
  {
    name: 'onPointerCancel',
    type: '((event: PointerEvent) => void)',
    description: 'Forwarded React Native prop.',
  },
  {
    name: 'onPointerCancelCapture',
    type: '((event: PointerEvent) => void)',
    description: 'Forwarded React Native prop.',
  },
  {
    name: 'onPointerDown',
    type: '((event: PointerEvent) => void)',
    description: 'Forwarded React Native prop.',
  },
  {
    name: 'onPointerDownCapture',
    type: '((event: PointerEvent) => void)',
    description: 'Forwarded React Native prop.',
  },
  {
    name: 'onPointerUp',
    type: '((event: PointerEvent) => void)',
    description: 'Forwarded React Native prop.',
  },
  {
    name: 'onPointerUpCapture',
    type: '((event: PointerEvent) => void)',
    description: 'Forwarded React Native prop.',
  },
  {
    name: 'accessible',
    type: 'boolean',
    description:
      'When true, indicates that the view is an accessibility element.\nBy default, all the touchable elements are accessible.',
  },
  {
    name: 'accessibilityActions',
    type: 'readonly Readonly<{ name: AccessibilityActionName | string; label?: string; }>[]',
    description:
      'Provides an array of custom actions available for accessibility.',
  },
  {
    name: 'aria-label',
    type: 'string',
    description:
      'Alias for accessibilityLabel  https://reactnative.dev/docs/view#accessibilitylabel\nhttps://github.com/facebook/react-native/issues/34424',
  },
  {
    name: 'aria-busy',
    type: 'boolean',
    description:
      'alias for accessibilityState\n\nsee https://reactnative.dev/docs/accessibility#accessibilitystate',
  },
  {
    name: 'aria-checked',
    type: 'boolean | "mixed"',
    description: 'Forwarded React Native prop.',
  },
  {
    name: 'aria-disabled',
    type: 'boolean',
    description: 'Forwarded React Native prop.',
  },
  {
    name: 'aria-expanded',
    type: 'boolean',
    description: 'Forwarded React Native prop.',
  },
  {
    name: 'aria-selected',
    type: 'boolean',
    description: 'Forwarded React Native prop.',
  },
  {
    name: 'accessibilityHint',
    type: 'string',
    description:
      'An accessibility hint helps users understand what will happen when they perform an action on the accessibility element when that result is not obvious from the accessibility label.',
  },
  {
    name: 'accessibilityValue',
    type: 'AccessibilityValue',
    description:
      "Represents the current value of a component. It can be a textual description of a component's value, or for range-based components, such as sliders and progress bars,\nit contains range information (minimum, current, and maximum).",
  },
  {
    name: 'aria-valuemax',
    type: 'number',
    description: 'Forwarded React Native prop.',
  },
  {
    name: 'aria-valuemin',
    type: 'number',
    description: 'Forwarded React Native prop.',
  },
  {
    name: 'aria-valuenow',
    type: 'number',
    description: 'Forwarded React Native prop.',
  },
  {
    name: 'aria-valuetext',
    type: 'string',
    description: 'Forwarded React Native prop.',
  },
  {
    name: 'onAccessibilityAction',
    type: '((event: AccessibilityActionEvent) => void)',
    description:
      'When `accessible` is true, the system will try to invoke this function when the user performs an accessibility custom action.',
  },
  {
    name: 'importantForAccessibility',
    type: "'auto' | 'yes' | 'no' | 'no-hide-descendants'",
    description:
      '[Android] Controlling if a view fires accessibility events and if it is reported to accessibility services.',
  },
  {
    name: 'aria-hidden',
    type: 'boolean',
    description:
      'A value indicating whether the accessibility elements contained within\nthis accessibility element are hidden.',
  },
  {
    name: 'aria-modal',
    type: 'boolean',
    description: 'Forwarded React Native prop.',
  },
  {
    name: 'role',
    type: "'link' | 'none' | 'alert' | 'alertdialog' | 'application' | 'article' | 'banner' | 'button' | 'cell' | 'checkbox' | 'columnheader' | 'combobox' | 'complementary' | 'contentinfo' | 'definition' | 'dialog' | 'directory' | 'document' | 'feed' | 'figure' | 'form' | 'grid' | 'group' | 'heading' | 'img' | 'list' | 'listitem' | 'log' | 'main' | 'marquee' | 'math' | 'menu' | 'menubar' | 'menuitem' | 'meter' | 'navigation' | 'note' | 'option' | 'presentation' | 'progressbar' | 'radio' | 'radiogroup' | 'region' | 'row' | 'rowgroup' | 'rowheader' | 'scrollbar' | 'searchbox' | 'separator' | 'slider' | 'spinbutton' | 'status' | 'summary' | 'switch' | 'tab' | 'table' | 'tablist' | 'tabpanel' | 'term' | 'timer' | 'toolbar' | 'tooltip' | 'tree' | 'treegrid' | 'treeitem'",
    description:
      'Indicates to accessibility services to treat UI component like a specific role.',
  },
  {
    name: 'accessibilityLabelledBy',
    type: 'string | string[]',
    description:
      'Identifies the element that labels the element it is applied to. When the assistive technology focuses on the component with this props,\nthe text is read aloud. The value should should match the nativeID of the related element.',
  },
  {
    name: 'aria-labelledby',
    type: 'string',
    description:
      'Identifies the element that labels the element it is applied to. When the assistive technology focuses on the component with this props,\nthe text is read aloud. The value should should match the nativeID of the related element.',
  },
  {
    name: 'accessibilityLiveRegion',
    type: "'none' | 'polite' | 'assertive'",
    description:
      'Indicates to accessibility services whether the user should be notified\nwhen this view changes. Works for Android API >= 19 only.',
  },
  {
    name: 'aria-live',
    type: "'polite' | 'assertive' | 'off'",
    description:
      'Indicates to accessibility services whether the user should be notified\nwhen this view changes. Works for Android API >= 19 only.',
  },
  {
    name: 'screenReaderFocusable',
    type: 'boolean',
    description:
      'Enables the view to be screen reader focusable, not keyboard focusable.',
  },
  {
    name: 'accessibilityElementsHidden',
    type: 'boolean',
    description:
      'A Boolean value indicating whether the accessibility elements contained within this accessibility element\nare hidden to the screen reader.',
  },
  {
    name: 'accessibilityViewIsModal',
    type: 'boolean',
    description:
      'A Boolean value indicating whether VoiceOver should ignore the elements within views that are siblings of the receiver.',
  },
  {
    name: 'onAccessibilityEscape',
    type: '(() => void)',
    description:
      'When accessible is true, the system will invoke this function when the user performs the escape gesture (scrub with two fingers).',
  },
  {
    name: 'onAccessibilityTap',
    type: '(() => void)',
    description:
      'When `accessible` is true, the system will try to invoke this function when the user performs accessibility tap gesture.',
  },
  {
    name: 'onMagicTap',
    type: '(() => void)',
    description:
      'When accessible is true, the system will invoke this function when the user performs the magic tap gesture.',
  },
  {
    name: 'accessibilityIgnoresInvertColors',
    type: 'boolean',
    description:
      'https://reactnative.dev/docs/accessibility#accessibilityignoresinvertcolorsios',
  },
  {
    name: 'accessibilityLanguage',
    type: 'string',
    description:
      "By using the accessibilityLanguage property, the screen reader will understand which language to use while reading the element's label, value and hint. The provided string value must follow the BCP 47 specification (https://www.rfc-editor.org/info/bcp47).\nhttps://reactnative.dev/docs/accessibility#accessibilitylanguage-ios",
  },
  {
    name: 'accessibilityShowsLargeContentViewer',
    type: 'boolean',
    description:
      'A Boolean value that indicates whether or not to show the item in the large content viewer.\nAvailable on iOS 13.0+\nhttps://reactnative.dev/docs/accessibility#accessibilityshowslargecontentviewer',
  },
  {
    name: 'accessibilityLargeContentTitle',
    type: 'string',
    description:
      'When `accessibilityShowsLargeContentViewer` is set, this string will be used as title for the large content viewer.\nhttps://reactnative.dev/docs/accessibility#accessibilitylargecontenttitle',
  },
  {
    name: 'accessibilityRespondsToUserInteraction',
    type: 'boolean',
    description:
      'Blocks the user from interacting with the component through keyboard while still allowing\nscreen reader to interact with it if this View is still accessible.',
  },
  {
    name: 'onHoverIn',
    type: '((event: MouseEvent) => void) | null',
    description:
      'Called when the hover is activated to provide visual feedback.',
  },
  {
    name: 'onHoverOut',
    type: '((event: MouseEvent) => void) | null',
    description:
      'Called when the hover is deactivated to undo visual feedback.',
  },
  {
    name: 'onPressIn',
    type: '((event: GestureResponderEvent) => void) | null',
    description: 'Called when a touch is engaged before `onPress`.',
  },
  {
    name: 'onPressMove',
    type: '((event: GestureResponderEvent) => void) | null',
    description: 'Called when the press location moves.',
  },
  {
    name: 'onPressOut',
    type: '((event: GestureResponderEvent) => void) | null',
    description: 'Called when a touch is released before `onPress`.',
  },
  {
    name: 'onLongPress',
    type: '((event: GestureResponderEvent) => void) | null',
    description: 'Called when a long-tap gesture is detected.',
  },
  {
    name: 'cancelable',
    type: 'boolean | null',
    description:
      'Whether a press gesture can be interrupted by a parent gesture such as a\nscroll event. Defaults to true.',
  },
  {
    name: 'delayHoverIn',
    type: 'number | null',
    description: 'Duration to wait after hover in before calling `onHoverIn`.',
  },
  {
    name: 'delayHoverOut',
    type: 'number | null',
    description:
      'Duration to wait after hover out before calling `onHoverOut`.',
  },
  {
    name: 'delayLongPress',
    type: 'number | null',
    description:
      'Duration (in milliseconds) from `onPressIn` before `onLongPress` is called.',
  },
  {
    name: 'pressRetentionOffset',
    type: 'number | Insets | null',
    description:
      'Additional distance outside of this view in which a touch is considered a\npress before `onPressOut` is triggered.',
  },
  {
    name: 'android_disableSound',
    type: 'boolean | null',
    description: "If true, doesn't play system sound on touch.",
  },
  {
    name: 'android_ripple',
    type: 'PressableAndroidRippleConfig | null',
    description: 'Enables the Android ripple effect and configures its color.',
  },
  {
    name: 'testOnly_pressed',
    type: 'boolean | null',
    description:
      'Used only for documentation or testing (e.g. snapshot testing).',
  },
  {
    name: 'unstable_pressDelay',
    type: 'number',
    description:
      'Duration (in milliseconds) to wait after press down before calling onPressIn.',
  },
];

export const buttonApi = {
  react: {
    sections: reactButtonApiSections,
    inheritedProps: inheritedReactButtonApi,
  },
  'react-native': {
    sections: nativeButtonApiSections,
    inheritedProps: inheritedNativeButtonApi,
  },
} as const;
